### ISSUE TITLE
Please add a way to use without Node

### ISSUE THREAD

**Issue by worldoptimizer** [darkroomengineering/lenis#1]
Would be great to have a precompiled version to use without node or multiple imports.

**Comment by arzafran** [comment]
Hello @worldoptimizer PRs are welcome, we've talked about bundling it but ended up thinking that should be a task for the bundler in the project instead.. we may be wrong but i'd love to learn more about your use case to understand if it makes sense for us to precompile it or not.

the main intention is to keep the lib lightweight if we precompile it it's going to need a ton of polyfills that users may not need..

i'm just thinking out loud

**Comment by arzafran** [comment]
fixed on de9282c3827e69f7265927e2da5128a250b066c0

**Comment by diegoliv** [comment]
I think that one of the use cases here is when you want to use this library on a no-code project for example. Say that I have a page built in Webflow that I want to use Lenis for smooth scroll. I can embed custom JS code there, but I can't use node or bundlers there.

So, if we had a precompiled version of Lenis that could be hosted on a CDN for example, then all we would need to do is include the script tag and initialize Lenis.

**Comment by clementroche** [comment]
#4 fix this
