### ISSUE TITLE
~20px jump at the end of the scroll

### ISSUE THREAD

**Issue by wtem-design** [darkroomengineering/lenis#104]
Hi, I get a sudden jump at the end of each scroll at the website https://boleslaw-farion.webflow.io/archiwum The exact jump is velocity based.

I believe that wasn't the case when I last touched anything on that site in the beginning of December. Not using @latest.

**Comment by clementroche** [comment]
Can you show us how you initialize Lenis and which version are you using ?

**Comment by wtem-design** [comment]
Sure. I use v2.28 but tried 2.26 and latest with no change in the effect.

const lenis = new Lenis({
  duration: 1,
  easing: (t) => Math.min(1, 1.001 - Math.pow(9, -1.2 * t)), // https://www.desmos.com/calculator/brs54l4xou
  direction: 'vertical', // vertical, horizontal
  gestureDirection: 'vertical', // vertical, horizontal, both
  smooth: true,
  mouseMultiplier: 0.5,
  smoothTouch: false,
  touchMultiplier: 2,
  infinite: false,
})

**Comment by clementroche** [comment]
Where did you get this easing function ? `Math.min(1, 1.001 - Math.pow(9, -1.2 * t))`

**Comment by wtem-design** [comment]
I've built on top of the function from the docs to get the easing I was looking for, using desmos calculator. Is there something wrong?

**Comment by wtem-design** [comment]
Same thing happens if I use the exact function from the docs, but if I use both the default function and mouseMultiplier there is no jump.

**Comment by clementroche** [comment]
it's wrong because easing function should match f(1) = 1, see [functions](https://www.desmos.com/calculator/bnqi9xgfwi) comparision. Internally when Lenis reaches the duration it will automatically set `scroll` value to `targetScroll`, visually it creates a jump. 

If you don't notice any jump [on this codepen](https://codepen.io/ClementRoche/pen/ExpwWwp) it means your implementation is wrong in some ways

**Comment by clementroche** [comment]
is it clear enough @wtem-design  ?

**Comment by wtem-design** [comment]
Yes, it does. Thank you.
