### ISSUE TITLE
Overflow Scroll elements are not working

### ISSUE THREAD

**Issue by Chakradhari97** [darkroomengineering/lenis#105]
Smooth scroll is working on entire page but for the overflow scroll item the scroll is getting disabled.

**Comment by clementroche** [comment]
Which version are you using ? And please reproduce it using [this codepen](https://codepen.io/ClementRoche/pen/ExpwWwp)

**Comment by Chakradhari97** [comment]
Lenis 0.2.28

We faced this issue today morning.
I am using it in webflow.

**Comment by clementroche** [comment]
Please reproduce it on codpen

**Comment by Chakradhari97** [comment]
Hey clementroche,
I don't know who to reproduce on codepen but I can share link to the page where you can see the issue - https://geists.webflow.io/geist-crowlers

**Comment by clementroche** [comment]
Unfortunatelly I'm not able to fix your issue based on a full website, the issue can come from anywhere in your code, meaning your implementation can be wrong and cause the issue. That's why minimal codepen reproduction is needed, if the bug is visible then the source code of Lenis is causing the issue.

**Comment by Chakradhari97** [comment]
Ok I get your point but website is being build in Webflow, which is a no-coding platform so I don't have I any idea how will I add the code to it plus there is CMS data linked with the content.
Is there any other way we can manage this.
Also I made one dummy page adding cms content and trying the same thing and it still didn't work.
You can check this also - https://genrobotics-trials.webflow.io/trials

**Comment by clementroche** [comment]
add `data-lenis-prevent` attribute to your element.

**Comment by Chakradhari97** [comment]
Thanks it works fine now.
Thank you.
