### ISSUE TITLE
On touch device, scroll event direction is set to 0 instead of 1 or -1

### ISSUE THREAD

**Issue by Charlene-Bx** [darkroomengineering/lenis#106]
**Describe the bug**
On Desktop device, the parameter "direction" in the scroll listener is set to 1 for a scroll up and -1 for a scroll down. Even with a pad. But on Touch device as Iphone or Ipad, the direction is always set to 0. No way to know if the user swipe from the top to the bottom or reverse...

**Comment by clementroche** [comment]
which version of lenis are you using ?

**Comment by Charlene-Bx** [comment]
@clementroche Lenis "^0.2.10"

**Comment by clementroche** [comment]
Try 0.2.28

**Comment by zulik-digital** [comment]
Hello @clementroche - I'm using 0.2.28 and encountering the same issue, direction property is always returning 0 on touch devices.

**Comment by clementroche** [comment]
You can try using [1.0.0-dev.5](https://www.npmjs.com/package/@studio-freight/lenis/v/1.0.0-dev.5)

**Comment by clementroche** [comment]
any news @Charlene-Bx, does that fix your issue ?

**Comment by zulik-digital** [comment]
1.0.0-dev.5 works for me, thanks @clementroche!

**Comment by clementroche** [comment]
1.0.0-dev.8 is available
