### ISSUE TITLE
Unsubscribe from event emitter (remove event listener callback)

### ISSUE THREAD

**Issue by oguilleux** [darkroomengineering/lenis#110]
Hi Clément, first thanks for your work, love the experience !

I'm using it doing webGL + barba.js.

When I change page I'd like to remove this callback (without destroying the whole lenis instance) : 

```
lenis.on('scroll', this.scrollHandler.bind(this));
```

I tried doing this :
```
lenis.off('scroll', this.scrollHandler);
``` 
or this
```
lenis.wrapperNode.removeEventListener('scroll', this.scrollHandler);
``` 

But nothing worked. Could you point out what I'm doing wrong here please ?

Cheers.

**Comment by clementroche** [comment]
hey, your code seems to be wrong, can you try with this instead ?

```
this.scrollHandler = this.scrollHandler.bind(this)
lenis.on('scroll', this.scrollHandler);
```

```
lenis.off('scroll', this.scrollHandler);
```

**Comment by oguilleux** [comment]
Awesome didn't think that binding would be the trouble. Thanks !
