### ISSUE TITLE
Is there an addition of [data-speed] animation?

### ISSUE THREAD

**Issue by heyadeivan** [darkroomengineering/lenis#113]
I use scrollTrigger to create data-speed, but how to make the element that has left the viewport stop moving, I see the inspector code transform3d value of the element that has left the viewport continues to move, maybe here someone can help...

https://codepen.io/adeivan/pen/OJwBomP

**Comment by clementroche** [comment]
https://codepen.io/ClementRoche/pen/dyjwxmK?editors=0110
