### ISSUE TITLE
Prevent interface resize on mobile devices

### ISSUE THREAD

**Issue by vervelover** [darkroomengineering/lenis#119]
Hi,

thank you for this great module. I only have an issue with it on mobile devices, where it doesn't prevent the mobile browser interface from resizing on scroll up/down like Scrolltrigger.normalizeScroll(true) does. Since Scrolltrigger normalizescroll doesn't play well with lenis (it makes lenis scrolling super fast when enabled) I still need to disable lenis completely on mobile devices, would be nice to see this resolved,

Thanks!
Alessio

**Comment by clementroche** [comment]
Do you use `smoothTouch` option ?

**Comment by vervelover** [comment]
I wasn't, that fixed it, thanks!
