### ISSUE TITLE
FR: Receive virtual scroll events while stopped

### ISSUE THREAD

**Issue by RafaelKr** [darkroomengineering/lenis#121]
My goal is to have a site which has some sections which are Sliders with 100vh height. I'd like to "lock" the scroll when these sections are reached and translate the "scroll" events (wheel, touchmove) into slide events.

So I'd like to be able to call `lenis.stop()` and still be able to receive the underlying events, maybe with a `lenis.on('virtual-scroll', cb)`.
Longterm I think it would be even great to get the velocity and direction in that event, but this isn't a requirement for me for now.

**Comment by clementroche** [comment]
@RafaelKr you certainly need CSS Sticky property. Here is an example https://codepen.io/ClementRoche/pen/RwBvWoK

**Comment by RafaelKr** [comment]
@clementroche It's not about the snapping, it's that there are no scroll events triggered after `lenis.stop()` is called.

**Comment by clementroche** [comment]
This example is not relevant for you ? This is what I call "to lock" sections. Stop the scroll after reaching a certain point and still listen to scroll doesn't have any sense since the scroll length of your page will be wrong. But maybe you can provide a codepen example or a video or anything to show what you want to achieve.

**Comment by RafaelKr** [comment]
Basically I want to implement something like this: https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html

I already accomplished what I wanted with locomotive after I patched it with a `virtualScrollInterceptor`:
https://github.com/vi-brand-studios/locomotive-scroll/commit/b511b1cc463507a26042fbeb45ad281dff232ee2

Basically I get all events from their internal virtual-scroll first and if I return `false` it does no scroll. And, that's what is important, I still get the `wheel` and `touchmove` events after I called `locomotive.stop()`. I need this to "translate" these events to go to the next or previous slides.

But I want to get rid of locomotives because their smooth was working on mobile. This is why I'm now trying to switch to lenis.

**Comment by clementroche** [comment]
Yes i would definitly do this using CSS sticky as I showed on my codepen. Then I would seek for the progress in order to put the current inner slide in the middle of the screen using transform: translateX( x )

```
const currentSlideIndex = Math.round((sectionHeight/slideHeight) * progress)
const x = currentSlideIndex * slideWidth
```

That's much better to keep native page scroll length and accessibility

**Comment by RafaelKr** [comment]
Okay, thanks for clarifying.

**Comment by RafaelKr** [comment]
@clementroche Thanks for the heads up. The non-blocking solution based on scroll progress is definitely much nicer. I used [ScrollMagic](https://scrollmagic.io/) for that and it works like a charm!

This is all it needs:
```js
const slideCount = swiper.slides.length
const slideToggleFraction = 1 / slideCount

const scene = new Scene({
  triggerElement: projectSection,
  triggerHook: 0,
  duration: (slideCount * 100) + '%',
  reverse: true,
})
  .setPin(projectSection)
  .addTo(scrollmagicController)

scene.on('progress', (e) => {
  const slideIndex = Math.floor(e.progress / slideToggleFraction)
  swiper.slideTo(slideIndex)
})
```

btw `Math.floor` is better than `Math.round` in this case. Else the first slide is shown for only half the scroll progress amount. That amount would be shifted to the last slide.
