### ISSUE TITLE
iOS Safari, Content Jumps on Scroll

### ISSUE THREAD

**Issue by AlexandraKlein** [darkroomengineering/lenis#122]
**Describe the bug**
On iOS Safari, the scroll content jumps when changing direction (up/down) because of the address bar growing and shrinking.

**To Reproduce**
View [https://lenis.studiofreight.com/](https://lenis.studiofreight.com/) on iOS Safari.

The following screen recording is from:

iOS Version: 16.1.2
Model Name: iPhone 14

https://user-images.githubusercontent.com/6663760/219507483-a700c103-453f-420b-a54e-932836799071.mov

**Comment by aboutluca** [comment]
Also on safari desktop content jumps...

**Comment by AlexandraKlein** [comment]
> Also on safari desktop content jumps...

Hmm, I'm not seeing this particular issue on Safari desktop.

**Comment by aboutluca** [comment]
Yes, sorry solved updating safari from 15.4 to 15.6 monterey

**Comment by haroldao** [comment]
seems like it's because of the bottom bar 👀

**Comment by AlexandraKlein** [comment]
I believe this issue is because of the use of `window.innerHeight` throughout the website, either directly or from **react-use**'s [useWindowSize](https://github.com/streamich/react-use/blob/master/src/useWindowSize.ts) hook. When I use `window.outerHeight` to calculate `progress` of sections, the iOS jump goes away. 

Consider the following code:

```javascript
  useEffect(() => {
    const onResize = () => {
      setWindowHeight(window.outerHeight) // window.innerHeight has been changed to window.outerHeight
    }

    window.addEventListener('resize', onResize, false)
    onResize()

    return () => {
      window.removeEventListener('resize', onResize, false)
    }
  }, [])
```

```javascript
  useScroll(({ scroll }) => {
    const start = wrapperRect.top - windowHeight
    const end = wrapperRect.top + wrapperRect.height - windowHeight

    let progress = mapRange(start, end, scroll, 0, 1)
    progress = clamp(0, progress, 1)

    setProgress(progress)
    ...
  })
```

If I use `window.outerHeight` to calculate `progress` instead of `window.innerHeight`, there is no "jump" when changing scroll direction on iOS as the height always includes the expanded height of the Safari address bar.

This does not seem to be a problem with Lenis, but an bug that occurs when implementing Lenis with progress that is calculated by `window.innerHeight`. I imagine similar bugs can occur when using `100vh` instead of `100svh` and the like.

**Comment by maxschulmeister** [comment]
i encountered the same issue, but it's related to updating a state with a value coming from lenis. e.g.
```
const [scrollDirection, setScrollDirection] = useState(null);
const [scrollY, setScrollY] = useState(null);

  useLenis((lenis) => {
    setScrollDirection(lenis.direction);
    setScrollY(lenis.targetScroll);
  });
```

i combined the 2 values into 1 state, which the issue almost go away, but it's still not a good solution imo.

**Comment by clementroche** [comment]
It should be fixed now !

**Comment by AlexandraKlein** [comment]
> It should be fixed now !

The jumping is, indeed, fixed! However, scrolling on iOS Safari is painfully sluggish now...

**Comment by clementroche** [comment]
i've reworked the smoothTouch option to be more accurate. I'm now working on a touchSync to mimic the native smooth scroll as much as possible while providing full sync

**Comment by AlexandraKlein** [comment]
@clementroche Could you tell me what the solution for that content jump on iOS? Is there a PR that I can look at?

**Comment by clementroche** [comment]
@AlexandraKlein those two commits:
https://github.com/studio-freight/lenis/commit/0d50f60b0c4534db3b7a6c3ce02af8f84e1859ee
https://github.com/studio-freight/lenis/commit/d76238f4950832c0294cb5835d6d69ec69b8a14e

**Comment by Eric-llos** [comment]
I think this is still happening in the lenis website.

iPhone 15 - iOS 17.0

https://github.com/studio-freight/lenis/assets/85624552/b0d871dc-4fb4-42e1-b05b-1c600c4c37a8
