### ISSUE TITLE
No longer respects position sticky in webflow

### ISSUE THREAD

**Issue by capokrzywa** [darkroomengineering/lenis#123]
Hey there, so I was using this lenis code in the body of my webflow site because it was one of the few libraries that actually worked on pages with elements that use position sticky.

Here's the code
```
<!-- Smooth scrolling -->
<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.28/bundled/lenis.js"></script>

<script>
const lenis = new Lenis({
  duration: 1.2,
  easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // https://www.desmos.com/calculator/brs54l4xou
  direction: 'vertical', // vertical, horizontal
  gestureDirection: 'vertical', // vertical, horizontal, both
  smooth: true,
  mouseMultiplier: 1,
  smoothTouch: false,
  touchMultiplier: 2,
  infinite: false,
})

//get scroll value
lenis.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
  console.log({ scroll, limit, velocity, direction, progress })
})

function raf(time) {
  lenis.raf(time)
  requestAnimationFrame(raf)
}

requestAnimationFrame(raf)
</script>
```

Everything was working perfectly for about a month or so. However, as of today I noticed it's no longer respecting position sticky. In other words, elements with the position of 'sticky' just scroll as any other element and don't stick to the page.

**Comment by clementroche** [comment]
Look at [this codepen](https://codepen.io/ClementRoche/pen/ExpwWwp), the sticky works as expected. It means your implementation is wrong in some way. You have maybe added an overflow hidden to an ancestor or have forget to add top:0

**Comment by capokrzywa** [comment]
Shoot, somehow the overflow prop got reset to hidden for one of my sections. Sorry for the easy mistake! Thanks.
