### ISSUE TITLE
Using lenis on `position: fixed;` elements.

### ISSUE THREAD

**Issue by shashwtd** [darkroomengineering/lenis#125]
Hey, 

I am working on a project where I have a div that has position fixed and inside that is all the content. I want to implement lenis scroll but I'm not sure how to make it work. It works without lenis and when I add lenis it doesn't scroll at all.

**Comment by BleXor** [comment]
Can you share a codepen with this issue?

**Comment by emm3ttarmstrong** [comment]
Not a codepen, but I have a webflow site with the same issue. The team popups towards the bottom of the page have some overflow, and I can't figure out how to allow Lenis to scroll the popup overflow when the modal is open. 

I wrote some custom JS to call lenis.stop() and lenis.start() when the item is visible, which is nice. 

https://modera-phase-1.webflow.io/

**Comment by shashwtd** [comment]
Here is the codepen you requested for... The issue is that when position is set to fixed there is no scroll at all. If you remove the `position: fixed` style from the main element the scroll works just fine.

[Lenis not working on `position: fixed`](https://codepen.io/shashwt/pen/wvEgQgE)

PS: Can someone explain to me how can I use lenis on multiple elements?

**Comment by clementroche** [comment]
@shashwtt, with `position: fixed` on main element you're erasing native browser scroll behavior. By default Lenis targets window scroll so you should fill wrapper and content options accordingly.

```
const lenis = new Lenis({
  wrapper: NodeElement, // element which has overflow
  content: NodeElement, // usually wrapper's direct child
})
```

or you can simply remove the `position: fixed`, I'm pretty sure you don't need it

**Comment by clementroche** [comment]
> Not a codepen, but I have a webflow site with the same issue. The team popups towards the bottom of the page have some overflow, and I can't figure out how to allow Lenis to scroll the popup overflow when the modal is open.
> 
> I wrote some custom JS to call lenis.stop() and lenis.start() when the item is visible, which is nice.
> 
> https://modera-phase-1.webflow.io/

https://github.com/studio-freight/lenis#use-data-lenis-prevent-attribute-on-nested-scroll-elements-in-addition-we-advise-you-to-add-overscroll-behavior-contain-on-this-element

**Comment by shashwtd** [comment]
```
const lenis = new Lenis({ 
  wrapper: NodeElement, // element which has overflow 
  content: NodeElement, // usually wrapper's direct child 
})
```

what should be the wrapper and content in my case. can you please explain? I can't seem to get it right.

**Comment by clementroche** [comment]
https://codepen.io/ClementRoche/pen/OJojYgG

**Comment by shashwtd** [comment]
Thank you! 
my issue has been resolved.
