### ISSUE TITLE
Can't import on Vue3

### ISSUE THREAD

**Issue by leogenot** [darkroomengineering/lenis#126]
Hey I can't seem to be able to `'import Lenis from "@studio-freight/lenis";`
in the script of my Vue3 project :
`GET http://127.0.0.1:5173/node_modules/.vite/deps/@studio-freight_lenis.js?t=1677429057021&v=c4126824 net::ERR_ABORTED 504 (Gateway Timeout)`

Feels like it is not finding Lenis

**Comment by clementroche** [comment]
Can you reproduce this on a codesandbox ?

**Comment by leogenot** [comment]
Hey sorry for the late reply, here is a [CodeSandbox link](https://codesandbox.io/p/github/leogenot/vue-template/draft/optimistic-surf?file=%2Fsrc%2Ftemplates%2Flayout%2FTheBase.vue&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A142%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A142%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clepf551p002cg8ga3drchnvc%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fsrc%252Ftemplates%252Flayout%252FTheContent.vue%2522%252C%2522%252Fsrc%252Ftemplates%252Flayout%252FTheBase.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clepf58mk00153n6i5bho48b8%2522%253A%257B%2522key%2522%253A%2522clepf58mk00153n6i5bho48b8%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clepf5m0c00963n6ib14e4be9%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clepf5k94006p3n6iz0ing16c%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clepf58mk00153n6i5bho48b8%2522%252C%2522spacesOrder%2522%253A%255B%2522clepf58mk00153n6i5bho48b8%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

weirdly enough it just doesn't load (as before) but there isn't any error in console as in real dev environment on browser

**Comment by clementroche** [comment]
@leogenot there is an error in the console

![image](https://user-images.githubusercontent.com/28361254/222107588-bed7f19b-0e81-41e0-9532-12ea6fcef722.png)

**Comment by leogenot** [comment]
Yes, if I remove the import everything is fine that's why I don't understand what is causing this

**Comment by leogenot** [comment]
Seems it was an issue with my repo and some weird cached files sorry
