### ISSUE TITLE
Scroll is not working on the overlay when we use lenis smooth scroll.

### ISSUE THREAD

**Issue by ChiragSarvaiya4** [darkroomengineering/lenis#127]
Hello guys, 
First of all thank you for creating this lenis smooth scroll js. It is working smoothly and nicely.

When I open the overlay and in this overlay I need to scroll. But it is not working when I open the overlay. Inside the overlay I can not scroll the content. On a normal body scroll is working smooth and fine. Overlay have position fixed.

Can you please help me out with this issue. 

I have one more question. How can we stop lenis js when we open the overlay and when we close the overlay it will work again? And Overlay opens on click just normal click event.

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis#use-data-lenis-prevent-attribute-on-nested-scroll-elements-in-addition-we-advise-you-to-add-overscroll-behavior-contain-on-this-element

**Comment by ChiragSarvaiya4** [comment]
Thank you @clementroche. It is working fine :)
