### ISSUE TITLE
Missing types with `lenis.on` and other methods + suggestions

### ISSUE THREAD

**Issue by ghost** [darkroomengineering/lenis#130]
Hi all! 

I've been fascinated with this smooth scroll library and I love it! One major drawback is that it's lacking any TypeScript support, as I copy-pasted the basic setup code block to my project and I got an error:

![](https://user-images.githubusercontent.com/94678583/223311512-b762ae88-88b6-458f-adc7-a93f7a8c55c9.png)

Upon looking at dev tools, the params from the `lenis.on()` callback all return the number type from the console.

I got around this error by adding an interface:

```ts
interface LenisCallback {
    scroll?: number
    limit?: number
    velocity?: number
    direction?: number
    progress?: number
}

lenis.on("scroll", ({ scroll, limit, velocity, direction, progress }: LenisCallback) => {
    console.log({ scroll, limit, velocity, direction, progress })
})

/* Doesn't throw an error here either since I made the params optional */
lenis.on("scroll", ({ scroll, direction, progress }: LenisCallback) => {
    /* ... */
})
```

It works, and the error's gone, however, I personally don't find this to be practical and it adds unnecessary typing to the codebase.

Since the callback params from `lenis.on()` (and from other methods too) only return numbers when destructured from an object, I was considering prepending these said types like this:

```ts
/* I know tiny-emitter is a library, but this is a part of my proposition */
export declare class TinyEmitter {
  on(
    event: string,
    callback: (Partial<{ 
       scroll: number,
       limit: number,
       velocity: number,
       direction: number,
       progress: number,
    }>) => void,
    ctx?: any
   ): this;
  /** and others here as well */
}
```
That way, this would highly benefit those, including myself, that has a strongly typed codebase that relies on this library!

Moreover, I've been snooping around the repo for some time now and I noticed that your team is lacking confidence with TS, and I would be happy to open a PR that fixes these changes and accompany them with JSDocs as well—so feel free to correct me if there are problems with my approach!

**Comment by clementroche** [comment]
Can you use [lenis v1](https://www.npmjs.com/package/@studio-freight/lenis/v/1.0.0-dev.8) instead ? Does it fix your issue ?

**Comment by ghost** [comment]
Oh right, v0.2.28 didn't have those typings - my bad!
