### ISSUE TITLE
Scrolling stops completely on CSM items

### ISSUE THREAD

**Issue by drejday** [darkroomengineering/lenis#133]
Hello!

I use your product religiously but now i have run into a problem using CMS items. Check out the link below. The scroll seems to stop two thirds down the page. It only happens on CMS items.

Appreciate you guys!

https://btas.webflow.io/our-work/archie-rose

**Comment by clementroche** [comment]
margin-top: 140vh; is causing trouble with the content height, remove it or use padding top instead
