### ISSUE TITLE
Lenis website scroll bug

### ISSUE THREAD

**Issue by theusmabit** [darkroomengineering/lenis#135]
Hello, I have a problem with the scroll.
When I use the mouse scroll, the site scrolls down to 98%, a small part of the site is missing to get to the end, just by clicking on the scrollbar, using the down arrow or using the scroll button of the mouse and pushing down that I can go to the end.

I will show the problem with a GIF below

[https://imgur.com/B8kechc](url)

**Comment by clementroche** [comment]
You have a margin-top on first element or any other content overflowing the body (usually in the footer). That cause to compute a wrong scroll limit internally, find this element and it's gonna be fixed.

**Comment by theusmabit** [comment]
It worked, thanks!
