### ISSUE TITLE
GSAP Ticker jumping

### ISSUE THREAD

**Issue by jackkemmish** [darkroomengineering/lenis#136]
**Describe the bug**
Hi there, I see you added the below to your GSAP ScrollTrigger integration:
```javascript
gsap.ticker.add((time) => {
  lenis.raf(time * 1000)
})
```

I have tested this on my ongoing project and there is large amounts of jumping. I was previoulsy only using `lenis.on('scroll', ScrollTrigger.update)` and things seemed to work fine. Is there a need for this addition?

I see you are doing this in one of your other projects which I assume is overriding the GSAP ticker? [https://github.com/studio-freight/satus/blob/aa2a712093de0270f334c7e5dd5d2e54ffeaeb55/pages/_app.js#L30](https://github.com/studio-freight/satus/blob/aa2a712093de0270f334c7e5dd5d2e54ffeaeb55/pages/_app.js#L30)

**Comment by clementroche** [comment]
Can you provide a codepen example please ?

**Comment by jackkemmish** [comment]
Ah the place I am seeing it on is a horizontal scroll section.

I'd need time to replicate in CodePen to show you.

Watch this space!

Jack

**Comment by TomSmedley** [comment]
https://github.com/studio-freight/lenis/discussions/140

Interesting, I noticed this too. I found it was smoother without overriding the ticker and everything seems to be working for me correctly.

**Comment by clementroche** [comment]
We are aware of this issue. I'm closing this one in favor of https://github.com/studio-freight/lenis/issues/112 which provides examples

**Comment by emamoah** [comment]
Hi @clementroche I found myself here because I was facing a similar issue. Reading through your references, I don't actually see the question answered. Is the code that adds to the gsap ticker no longer necessary? Was there a reason for it being there? The answer you referenced doesn't seem to touch on that part of the code. Or are you implicitly telling us we can safely get rid of it?

**Comment by clementroche** [comment]
@emamoah 

The correct integration with GSAP ScrollTrigger is the following:
be sure gsap version is >=3.11.5

```
const lenis = new Lenis()

lenis.on("scroll", ScrollTrigger.update);

gsap.ticker.add((time) => {
  lenis.raf(time * 1000)
})
```

**Comment by emamoah** [comment]
@clementroche My gsap version is `3.12.2`. But for some reason, with the ticker code added, when I leave the window for a while and come back, the scroll is no longer smooth, and becomes a bit janky.

When I inspect the document, I see that anytime I try to scroll, the `lenis-scrolling` class appears very briefly on the html element, then disappears.

After a while when I leave and return again, the page just doesn't scroll anymore, the `lenis-scrolling` class stays on the html element, and when I log the event from `lenis.on('scroll')`, I realise it keeps logging itself infinitely until I refresh the page.

**Comment by clementroche** [comment]
Please provide a reproduction link.

Can you try adding `gsap.ticker.lagSmoothing(0)` ?

**Comment by emamoah** [comment]
@clementroche Adding `gsap.ticker.lagSmoothing(0)` seems to fix the issue. Could you provide an explanation, though?

Here's the reproduction link, by the way: https://codepen.io/emamoah/pen/poQwroL

Steps to reproduce:
1. Load the page.
2. Try scrolling (smoothing works).
3. Leave the tab for about 3 seconds.
4. Come back and try scrolling (smoothing still works).
5. Leave tab for another 3 seconds.
6. Come back and try scrolling (smoothing may not work anymore).
7. If smoothing still works in step 6, repeat steps 5 and 6. It wouldn't work this time.

Extra: Try leaving window for some time after the smoothing stops and do something else. Coming back you may notice that the page just doesn't scroll anymore. And then check the console.

**Comment by clementroche** [comment]
explaination: https://greensock.com/docs/v3/GSAP/gsap.ticker

**Comment by emamoah** [comment]
@clementroche Just checking in to find out if you verified the reproduction.

**Comment by clementroche** [comment]
@emamoah you told me it works using `gsap.ticker.lagSmoothing(0)` so i consider this issue fixed

**Comment by emamoah** [comment]
Well, I guess you could. I just have a slight unease seeing that I'm _adding_ code to fix the issue, rather than finding what actually was wrong with what _should_ have worked fine. My misgivings are due to the fact that the code added _could_ affect something else in the future. I normally like to keep things clean.

**Comment by clementroche** [comment]
You're calling 2 times lenis.raf(), once using requestAnimationFrame, the second using gsap ticker. You have to pick one, both cannot be used at the same time. In a GSAP context i would advise you to use GSAP ticker.

**Comment by emamoah** [comment]
Oohh...💡 I think this is what I'm looking for!

So I took out the first code that calls `lenis.raf()`, and used just the gsap ticker. Without the `lagSmoothing` "hack", it works fine now!

Specifically, here's how the code looks now:

```
const lenis = new Lenis();

// function raf(time) {         <----+-- This group commented out
//   lenis.raf(time);                |
//   requestAnimationFrame(raf);     |
// }                                 |
// requestAnimationFrame(raf);  <----'

lenis.on('scroll', ScrollTrigger.update);

gsap.ticker.add(time => {
  lenis.raf(time * 1000);
});
```

I would love for this to be clarified in the README if possible... Just for those who may find themselves in this situation.
Well, maybe they will just find this thread.

But either way, thank you for your help. Much appreciated, @clementroche !
