### ISSUE TITLE
Scroll not working on some sites

### ISSUE THREAD

**Issue by learyjk** [darkroomengineering/lenis#138]
Hey Team! Some folks are telling me that sites using Lenis aren't scrolling. I'm thinking the update to 1.0.1 might have broken something?

Is there a suggested version folks should try rolling back to?

Thanks!
Keegan

**Comment by learyjk** [comment]
Someone suggested a workaround on Twitter:
Yes I did, just find a workaround on twitter, importing the previous script version but through a txt file imported to Webflow and mentioning the link to this text file in the <script> file in the code. This solution worked out, but it seems temporary 

Like this : <script src="[uploads-ssl.webflow.com/637853f6f3d6aacb22fa97db/6410ba6944626800ddea55cb_txt.txt](http://uploads-ssl.webflow.com/637853f6f3d6aacb22fa97db/6410ba6944626800ddea55cb_txt.txt)"></script>

**Comment by clementroche** [comment]
v1 introduced major breaking changes. You have two options:
- keep v0 by using https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.28/bundled/lenis.js
- update your Lenis implementation

now default wrapper is html but webflow uses html: height: 100% (which doesn't make sense), just use html { height:auto; }

please take time to read documentation next time https://github.com/studio-freight/lenis#keep-html-elements-default-sized-this-is-necessary-for-webflow-implementation-see-issue

**Comment by learyjk** [comment]
Thanks for the prompt response! I was just in the documentation a week or two ago and didn't recall seeing that so I must have missed it.

I think some Webflow folks might be grabbing the version with @latest so figured that's what did it.
