### ISSUE TITLE
Basic setup no longer works

### ISSUE THREAD

**Issue by samsostudios** [darkroomengineering/lenis#139]
Hello,

The basic setup via both the cdn and npm doesn't seem to be working. Ive tried both routes with a Webflow page and the page does not scroll. I added this console statement:

`//get scroll value
  lenis.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
    console.log({ scroll, limit, velocity, direction, progress });
  });`

and returns this:

`{scroll: 0, limit: 0, velocity: 0, direction: 0, progress: NaN}`

I also tried setting 'wrapper' and 'content' manually but had no effect.

**Comment by clementroche** [comment]
Lenis v1 is working as expected: https://codepen.io/ClementRoche/pen/VwxgZEP

https://github.com/studio-freight/lenis/issues/138#issuecomment-1468678686
