### ISSUE TITLE
Overflow: auto on fixed div

### ISSUE THREAD

**Issue by dusanstojanovic** [darkroomengineering/lenis#14]
How can I make fixed positioned div actually scroll? It works without Lenis
Pen: https://codepen.io/stdusan/pen/YzLzZgg

**Comment by clementroche** [comment]
Hi, actually your issue is not related to `position: fixed`.
Unfortunately Lenis catches all wrapper `wheel` events so it obviously blocks children scroll too. To fix that you have to manually bind a wheel event listener to your scrolling element and then stop the propagation to parent, take a look into the [source code](https://github.com/studio-freight/lenis/blob/dd123be8c256edbe92d809eb3482eaaa3aed79dc/docs/container.html#L40).

`<div class="fixed" onwheel="event.stopPropagation()">`

It's necessary for now but we hope to find a seamless in the future.

**Comment by gyurmey2** [comment]
Hi, I don't know how to make this work for [CookieConsent modal](https://codepen.io/gyurmey2/pen/NWMErqQ) (Manage preferences). Or maybe there is already a solution to it?

**Comment by clementroche** [comment]
```js
const modal = document.querySelector('#cc-main')
modal.addEventListener('wheel',(e)=>{
  e.stopPropagation()
})
```

**Comment by gyurmey2** [comment]
Thank you. I tried in a similar way, but [it doesn't work](https://codepen.io/gyurmey2/pen/NWMErqQ).

**Comment by clementroche** [comment]
Your modal is loaded/injected after the document ready so you must add a setTimeout or listen to script load event.

**Comment by gyurmey2** [comment]
You're right. Thank you very much.

**Comment by gyurmey2** [comment]
@clementroche , [in this issue](https://github.com/orestbida/cookieconsent/issues/397#issuecomment-1287159201), @orestbida suggests that implement an “exclusions list” option. Is it even possible?

**Comment by clementroche** [comment]
@gyurmey2 v0.2.17 is out, you can now use `data-lenis-prevent` attribute instead. ([see docs](https://github.com/studio-freight/lenis/blob/main/README.md#use-data-lenis-prevent-attribute-on-nested-scroll-elements-in-addition-we-advice-you-to-add-overscroll-behavior-contain-on-this-element))

**Comment by gyurmey2** [comment]
@clementroche, thank you for your commitment.
I added an attribute ([JS => line 53](https://codepen.io/gyurmey2/pen/NWMErqQ)) but it doesn't work.

**Comment by clementroche** [comment]
i don't see any modal in your codepen

**Comment by gyurmey2** [comment]
Sorry, I didn't update `lenis` to the latest version before. Now it should be OK.

**Comment by clementroche** [comment]
@gyurmey2 your code is never entering the condition modalName === "preferenceModal"

![image](https://user-images.githubusercontent.com/28361254/197548202-9df4eac5-7ced-45a5-ac34-dc49f20a804a.png)

Sorry, but once again that's not a Lenis related issue, i can't keep helping you. Please be sure your code is valid and you questionned your implementation before submitting issues again.

**Comment by gyurmey2** [comment]
Of course. Thank you for your help so far.
