### ISSUE TITLE
Typescript Error

### ISSUE THREAD

**Issue by TomSmedley** [darkroomengineering/lenis#149]
**Describe the bug**
` Property 'onComplete' is missing in type '{ immediate: true; }'`

onComplete is required when using `immediate` see:
`$lenis?.scrollTo(0, { immediate: true })`

**Comment by clementroche** [comment]
i don't understand the issue, can you explain it in depth and ideally provide a codesandbox ?

**Comment by TomSmedley** [comment]
Hi @clementroche 

Thie issue is that when using `immediate` on `scrollTo` Typescript reports that `onComplete` is a required property.

![image](https://user-images.githubusercontent.com/95056193/226646030-f834d5fb-f273-4538-b288-8bbe237e1a7b.png)

It should be `onComplete?: () => void | undefined` I believe

**Comment by arzafran** [comment]
this should be fixed in v1.0.4
