### ISSUE TITLE
Anchor Tag Href Not Working as Expected During Active Scrolling

### ISSUE THREAD

**Issue by kyrregjerstad** [darkroomengineering/lenis#150]
### **Description**
When clicking on an anchor tag while the page is actively scrolling, the expected behaviour of jumping to the specified href location does not occur. The page only navigates to the desired location once the scrolling has come to a complete stop.

#### **Steps to Reproduce**

1. Visit this [Codepen](https://codepen.io/kyrregjerstad/pen/ZEMmBmO).
2. Scroll down to the bottom of the page.
3. Click on the "Back to Top" anchor tag **while the page is still scrolling**.
4. Observe that the page does not jump to the top until the scrolling motion stops.

#### **Expected Behavior**
The page should immediately navigate to the specified href location upon clicking the anchor tag, even during active scrolling.

#### **Actual Behavior**
The page only navigates to the href location when there is no active scrolling motion detected.

**Comment by clementroche** [comment]
Yes that's how Lenis works, while scrolling Lenis prevent native "scroll" events, that's not a choice but a need.

To fix your issue you have to manually call lenis.scroll(anchor) on click on this link. I know that's not ideal but this is the only way.

**Comment by kyrregjerstad** [comment]
Hello @clementroche, thank you for explaining the behaviour of Lenis and suggesting the solution of using lenis.scroll(anchor). I appreciate your prompt response!

Regarding the issue, I understand that this is how Lenis works, and I will try your suggested fix.
Perhaps it could be beneficial to consider stopping the lenis scroll event when the page reaches the bottom of the screen and the scroll direction is downwards. Don't know if this is possible, just a thought.

This issue may be more pronounced for users with a mouse such as the Logitech MX Master, or any other mouse with a free-spinning scroll wheel that continues to spin after reaching the bottom of the page.

**Comment by 1ucay** [comment]
Hi, also have Logitech MX Master and this would be great
_Perhaps it could be beneficial to consider stopping the lenis scroll event when the page reaches the bottom of the screen and the scroll direction is downwards. Don't know if this is possible, just a thought._
