### ISSUE TITLE
Can't scroll when using lenis

### ISSUE THREAD

**Issue by Nevvees** [darkroomengineering/lenis#155]
Hello devs,
I was using lenis with webflow since december 2022 and it worked perfectly, I was doing it through the CDN link:
<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@latest/bundled/lenis.js"></script>

But some weeks ago I couldn't even scroll from the hero of the website and since I'm using webflow I can't test with other versions with local install, must be through a CDN link.

I've also tried to use this CDN link:
<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.0/bundled/lenis.js"></script>

Do you have any idea of why this is happening?

Thanks.

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis/issues/138#issuecomment-1468678686
