### ISSUE TITLE
Unable to scroll if the user scrolls before Lenis is initialized 

### ISSUE THREAD

**Issue by SamCharpentier** [darkroomengineering/lenis#157]
If you scroll as soon as the page start loading, then once Lenis is initialized, the user can't scroll anymore. 
You can replicate it by scrolling on this site, as soon as it starts loading, then you are stuck on the hero section: https://shelbykay.dev/

There's probably a solution to this, since websites from Studio Freight does not hav this bug

**Comment by clementroche** [comment]
can you try v1.0.6 ?

**Comment by flayks** [comment]
@SamCharpentier @clementroche indeed it seems to fix the issue with the 1.0.6! Thanks for the bug report anyway 😄
