### ISSUE TITLE
Lenis on iFrames

### ISSUE THREAD

**Issue by SamCharpentier** [darkroomengineering/lenis#158]
Hello! This is not a bug, because I know Lenis is not supposed to work on embeded iframes, but I was wondering if there's a solution, or a workaround to make it a bit better? I am building a website with a lot of embeded forms, and I might remove the lenis smooth scroll because it's very buggy :( 
See here: https://sponsored-united.webflow.io/demo

**Comment by clementroche** [comment]
You could try with this css snippet https://github.com/studio-freight/lenis/issues/95#issuecomment-1493194888

```
.lenis-scrolling iframe {
   pointer-events: none;
} 
```

**Comment by clementroche** [comment]
any news @SamCharpentier ?

**Comment by SamCharpentier** [comment]
@clementroche the pointer-events solutions works well for now!

**Comment by javierdebug** [comment]
> You could try with this css snippet [#95 (comment)](https://github.com/studio-freight/lenis/issues/95#issuecomment-1493194888)
> 
> ```
> .lenis-scrolling iframe {
>    pointer-events: none;
> } 
> ```

Hey, I have a similar issue. This fix works for desktops but doesn't work for mobiles since there's no `lenis-scrolling` class when moving around the page on mobile. Do you have a similar fix for mobile? 

Let me know if I should open a new issue instead of commenting on this old (but similar) one.

**Comment by clementroche** [comment]
please provide a reproduction link @javierdebug 

lenis does provide a lenis-scrolling class while touch scrolling when syncTouch is enabled

**Comment by javierdebug** [comment]
@clementroche Thank you for the quick reply. 

Very nice that option. Enabling `syncTouch` does add the `lenis-scrolling` class when moving on mobile but unfortunately it doesn't add it when one tries to touch scroll and the cursor is above the `<iframe>`. I'll provide an example so it's easier to understand.
