### ISSUE TITLE
Horizontal scrolling doesn't work with macbook trackpad

### ISSUE THREAD

**Issue by jeremypetrequin** [darkroomengineering/lenis#159]
Hi,

Thank for your great work!

**Describe the bug**
I've tried to implement an horizontal scroll, it works fine with mouse, but can't make it work with the trackpad on my apple macbook - Chrome v111, Monterey macOS 
It scroll a little bit and goes back to start

**To Reproduce**
It seems to work with the version 0.2.9, here: 
https://codepen.io/jeremypetrequin/pen/gOBpvvX
(I retaken sample from another issue here)

But with v1.0.0 I can't make it work, I don't know if i'am a doing anything wrong?
See here: https://codepen.io/jeremypetrequin/pen/dygoObY

I don't know if you have access to a macbook to test? I can make a screencast if it helps.

Have a great day

**Comment by arzafran** [comment]
Here's an example on how to make it work with v1+
https://codesandbox.io/s/horizontal-scroll-forked-e9c081?file=/src/App.js

I'll take a look on what's failing on your codepens in depth later today.

**Comment by clementroche** [comment]
you must use `gestureOrientation: 'horizontal'`

**Comment by jeremypetrequin** [comment]
Thank both for your very quick response!

I missed the `display: table;` on html.
I didn't see it in the doc i think?

Have a great day, thank
