### ISSUE TITLE
Scrolling ultra slow, then speeds up

### ISSUE THREAD

**Issue by csimlinger** [darkroomengineering/lenis#162]
**Description**
When scrolling on the page, the scrolling starts extremely slow.
Then it suddenly speeds up. Does makes smooth scrolling impossible.

**To Reproduce**
I uploaded an example here: https://juj.at/krt/
When removing the CSS from the page, the smooth scrolling works like intended.
Therefore I conclude, that the bug comes from some CSS rules that are not compatible with Lenis.

Any idea how to solve that issue?

Thanks!

**Comment by clementroche** [comment]
`scroll-behavior: smooth;` is to blame

**Comment by csimlinger** [comment]
Thanks!
