### ISSUE TITLE
Scroll gets stuck close to the end of the page

### ISSUE THREAD

**Issue by CHR-onicles** [darkroomengineering/lenis#164]
**Describe the bug**
Scrolling works well sometimes in localhost and I'm able to scroll through the entire page, but after deployment I can only scroll to a little above the end of the page unless I refresh the browser. Even after refreshing it's a 50/50 chance it scrolls to the end. Tried this on chrome(v 112.0.5615.138), firefox(v112.0.1) and Edge(v112.0.1722.58). Even on a different computer, the problem persists.

I'm using Lenis v1.0.10

**My lenis config**
```ts
  const lenis = new Lenis({ lerp: 0.5, duration: 2 });

  function raf(time: number) {
    lenis.raf(time);
    requestAnimationFrame(raf);
  }

  requestAnimationFrame(raf);
```

**Demo**

https://user-images.githubusercontent.com/44934037/233796446-96cca3a0-124b-4ed5-a93e-b498aabeb7fd.mp4

**To Reproduce**
No idea how to reproduce

**Comment by clementroche** [comment]
remove `height: 100%` on html

https://github.com/studio-freight/lenis#keep-html-elements-default-sized-this-is-necessary-for-webflow-implementation-see-issue
