### ISSUE TITLE
Lenis with bootstrap 

### ISSUE THREAD

**Issue by execOQ** [darkroomengineering/lenis#166]
**Describe the bug**
i found text scrolling animation but scrolling with mouse wheel breaks if bootstrap css code is imported. And it breaks, as I understand it, only if the javascript file contains this code:
```
const lenis = new Lenis({
    duration: 1.2,
    easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t))
});
```

**To Reproduce**
https://codepen.io/execOQ/pen/vYVJvoq

**Comment by clementroche** [comment]
remove "scroll-behavior: smooth" on html

**Comment by execOQ** [comment]
Maybe I can't see it, but where did you find this piece of code on the codepen?

**Comment by clementroche** [comment]
it's coming from boostrap, you must use 

`
.lenis.lenis-smooth {
  scroll-behavior: auto;
}`


it's written in the [documentation](https://github.com/studio-freight/lenis#recommended-css) please read it before filling issues

**Comment by execOQ** [comment]
Thank you)
