### ISSUE TITLE
Scroll position jumps when dragging scrollbar after wheel

### ISSUE THREAD

**Issue by TheoGil** [darkroomengineering/lenis#168]
**Describe the bug**

The scroll position keeps jumping back to its previous value while dragging the native scrollbar. Jumping back and forth between its previous position and its desired position, ultimately going back to its previous position, preventing user from scrolling by dragging the browser scrollbar.

**To Reproduce**

It is subtle but reproducible on the [minimal lenis setup codepen](https://codepen.io/ClementRoche/pen/VwxgZEP), the issue is even more obvious on the [Lenis demo page](https://lenis.studiofreight.com/) (see screencasts below) : 

1. Scroll a little bit using the mouse wheel. The scroll must ends between its minimum and maximum position. Bug does not appear when scrolling all the way down or all the way up.
2. Try to scroll by grabbing the browser scrollbar.

Additional information : 
- The issue happens whether or not I've waited for the scroll position to stabilise after the wheel. Unlike https://github.com/studio-freight/lenis/issues/65
- The issue also happens when use the space key to scroll after a wheel.

My intuition is that the wheel triggered scroll position tween never completes, thus keeping the scroll position in a locked state (?) 🤔

I'm using Chrome 112 on OS X 10 : https://www.whatsmybrowser.org/b/G7TID.

On Safari 16.2 on OS X 10, the scrollbar does not move at all when trying to drag it.

Potentially related issues : https://github.com/studio-freight/lenis/issues/107 https://github.com/studio-freight/lenis/issues/65

See screencasts below : 

https://user-images.githubusercontent.com/8545893/236219160-d8dae9f7-d4f4-4c3d-a04d-3d3b618dae49.mp4

https://user-images.githubusercontent.com/8545893/236223686-e0f48285-74d7-48df-b368-f117cb5496fc.mp4

**Comment by TheoGil** [comment]
It does indeed look like this condition https://github.com/studio-freight/lenis/blob/main/src/animate.js#L13 could never be truthy in my case since `this.to` is not an integer and will never be equal to anything coming out of `Math.round` 🤔 

I've yet to succeed debugging it locally but will investigate further and will submit a PR if I manage to fix it.

<img width="975" alt="Capture d’écran 2023-05-04 à 16 30 41" src="https://user-images.githubusercontent.com/8545893/236241422-4a082174-80d0-4ad6-a504-9366495166b6.png">

**Comment by TheoGil** [comment]
Here a PR : seems almost _too_ easy to be true but it does seems to work : https://github.com/studio-freight/lenis/pull/169

**Comment by clementroche** [comment]
Thank you for your issue, i wish every issue to be described this good.
I think it's coming from this line https://github.com/studio-freight/lenis/blob/main/src/index.js#L333

**Comment by clementroche** [comment]
it should be fixed on v1.0.12

**Comment by TheoGil** [comment]
It is fixed, thanks! 🙏

**Comment by Hiei16** [comment]
Hello, this issue seems to be back in version 1.0.42. I have it and the [demo website](https://lenis.darkroom.engineering/) has it too.
