### ISSUE TITLE
How to use in Nuxt

### ISSUE THREAD

**Issue by vickykeen** [darkroomengineering/lenis#17]
Hi Mr Clementroche,

First of all thank you for this great smooth scroll which is open source really appreciated i have a question 
How do i use in nuxt, i tried but when route change the scroll position is didn't go top it stick to the same position as the previous page.
hope you understand my problem please guide me on this  thank you.

**Comment by clementroche** [comment]
Hi, have you tried to manually `window.scrollTo(0,0)` on page change ? I think this is not specific to lenis but this is the default Nuxt behavior, see [scrollToTop property](https://nuxtjs.org/docs/components-glossary/scrolltotop/) or [scrollBehavior](https://nuxtjs.org/docs/configuration-glossary/configuration-router#scrollbehavior).

**Comment by vickykeen** [comment]
> Hi, have you tried to manually `window.scrollTo(0,0)` on page change ? I think this is not specific to lenis but this is the default Nuxt behavior, see [scrollToTop property](https://nuxtjs.org/docs/components-glossary/scrolltotop/) or [scrollBehavior](https://nuxtjs.org/docs/configuration-glossary/configuration-router#scrollbehavior).

I have tried it seems like not working as well seems like when i scroll then route change the other page scroll all the way to the bottom

**Comment by clementroche** [comment]
you must destroy lenis on page destroy and create it again on page mount

**Comment by sethzindler** [comment]
Below works for me.

Add `transpile: "@studio-freight/lenis"` to your build configuration in `nuxt.config.js` and then add the following in your `default.vue` layout:

`if (process.browser) {
  require("@studio-freight/lenis")
}
import Lenis from "@studio-freight/lenis"`

Then add the Lenis configuration in a `mounted` hook.

**Comment by vickykeen** [comment]
> you must destroy lenis on page destroy and create it again on page mount

Ok i will do that thank you very much for  guiding me

**Comment by vickykeen** [comment]
> > you must destroy lenis on page destroy and create it again on page mount
> 
> Ok i will do that thank you very much for guiding me

Hi its Still the same even after i destroy it

**Comment by vickykeen** [comment]
Thank you for the help really appreciated 👍

**Comment by wolfie90** [comment]
@vickykeen You probably already fixed this but for anyone reading this issue, for getting it to work in Nuxt 3 (with scroll to top on route change) you can create a `Lenis.client.js` in the plugins folder and add the following:

```import Lenis from '@studio-freight/lenis'

const lenis = new Lenis({
    duration: 1.2,
    easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // https://www.desmos.com/calculator/brs54l4xou
    direction: 'vertical', // vertical, horizontal
    gestureDirection: 'vertical', // vertical, horizontal, both
    smooth: true,
    mouseMultiplier: 1,
    smoothTouch: false,
    touchMultiplier: 2,
    infinite: false,
  })

// //get scroll value
// lenis.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
//     console.log({ scroll, limit, velocity, direction, progress })
// })

const raf = (time) => {
    lenis.raf(time)
    requestAnimationFrame(raf)
}

requestAnimationFrame(raf)

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.provide("lenis", lenis);

    // scroll to top on route change
    nuxtApp.$router.afterEach((to, from) => {
        if (to.path !== from.path) {
            lenis.scrollTo('.app', { // your container class or id
                offset: 0,
                duration: 0,
                easing: () => {},
                immediate: true
            })
        }
   })
});

**Comment by vickykeen** [comment]
Hi
Thank you very much for the solution. I really appreciate it.

**Comment by snowiewdev** [comment]
> @vickykeen You probably already fixed this but for anyone reading this issue, for getting it to work in Nuxt 3 (with scroll to top on route change) you can create a `Lenis.client.js` in the plugins folder and add the following:
> 
> ```
> 
> const lenis = new Lenis({
>     duration: 1.2,
>     easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // https://www.desmos.com/calculator/brs54l4xou
>     direction: 'vertical', // vertical, horizontal
>     gestureDirection: 'vertical', // vertical, horizontal, both
>     smooth: true,
>     mouseMultiplier: 1,
>     smoothTouch: false,
>     touchMultiplier: 2,
>     infinite: false,
>   })
> 
> // //get scroll value
> // lenis.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
> //     console.log({ scroll, limit, velocity, direction, progress })
> // })
> 
> const raf = (time) => {
>     lenis.raf(time)
>     requestAnimationFrame(raf)
> }
> 
> requestAnimationFrame(raf)
> 
> export default defineNuxtPlugin((nuxtApp) => {
>     nuxtApp.provide("lenis", lenis);
> 
>     // scroll to top on route change
>     nuxtApp.$router.afterEach((to, from) => {
>         if (to.path !== from.path) {
>             lenis.scrollTo('.app', { // your container class or id
>                 offset: 0,
>                 duration: 0,
>                 easing: () => {},
>                 immediate: true
>             })
>         }
>    })
> });
> ```

Love you!! This saves my life:'D

My following solution for pals in Nuxt 2, in `default.vue`
```
    watch: {
        $route(to, from) {
            // Fix lenis + page change does not scroll to top automatically
            if (to.path !== from.path) {
                this.lenis.scrollTo(".layout-container", {.   // your container class or id
                    offset: 0,
                    duration: 0,
                    easing: () => {},
                    immediate: true,
                });
            }
        },
    },
```

**Comment by Slgoetz** [comment]
https://www.npmjs.com/package/nuxt-lenis

**Comment by vickykeen** [comment]
Thank you very much Simon, really appreciate it.

**Comment by KamiAmiga** [comment]
> @vickykeen You probably already fixed this but for anyone reading this issue, for getting it to work in Nuxt 3 (with scroll to top on route change) you can create a `Lenis.client.js` in the plugins folder and add the following:
> 
> ```
> 
> const lenis = new Lenis({
>     duration: 1.2,
>     easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), // https://www.desmos.com/calculator/brs54l4xou
>     direction: 'vertical', // vertical, horizontal
>     gestureDirection: 'vertical', // vertical, horizontal, both
>     smooth: true,
>     mouseMultiplier: 1,
>     smoothTouch: false,
>     touchMultiplier: 2,
>     infinite: false,
>   })
> 
> // //get scroll value
> // lenis.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
> //     console.log({ scroll, limit, velocity, direction, progress })
> // })
> 
> const raf = (time) => {
>     lenis.raf(time)
>     requestAnimationFrame(raf)
> }
> 
> requestAnimationFrame(raf)
> 
> export default defineNuxtPlugin((nuxtApp) => {
>     nuxtApp.provide("lenis", lenis);
> 
>     // scroll to top on route change
>     nuxtApp.$router.afterEach((to, from) => {
>         if (to.path !== from.path) {
>             lenis.scrollTo('.app', { // your container class or id
>                 offset: 0,
>                 duration: 0,
>                 easing: () => {},
>                 immediate: true
>             })
>         }
>    })
> });
> ```


Hello !

I know this subject is quite old now, but I just wanted to share a variation of this implementation that works with Nuxt3 in Typescript.

In a `plugins/lenis.client.ts` add the following : 
```
import Lenis from "lenis";

const lenis = new Lenis(
  // your options here
)

const raf = (time: number) => {
  lenis.raf(time)
  requestAnimationFrame(raf)
}

requestAnimationFrame(raf)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide("lenis", lenis);
  nuxtApp.hook('page:finish', () => {
    lenis.scrollTo('body', {
      offset: 0,
      duration: 0,
      immediate: true
    })
  })
});
```
