### ISSUE TITLE
How to implement in Angular?

### ISSUE THREAD

**Issue by kiptu-labs** [darkroomengineering/lenis#172]
Hey, i implemented Lenis with GSAP in Angular like in the following code.

But when the first page that gets loaded is a short one and i change to a long one, i can't scroll any further than where the end of the previous page would be. So i somehow have to refresh lenis on a route change, but i don't know how. Any help is appreciated!

```ts
import { Component, OnInit } from '@angular/core';
import Lenis from '@studio-freight/lenis';
import { gsap } from "gsap";
import { ScrollTrigger } from 'gsap/ScrollTrigger';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  public lenis: Lenis = new Lenis();

  constructor() {
    gsap.registerPlugin(ScrollTrigger);
  }

  ngOnInit(): void {
    this.lenis.on('scroll', ScrollTrigger.update);

    gsap.ticker.add((time) => {
      this.lenis.raf(time * 1000);
    });
  }
}
```

**Comment by kiptu-labs** [comment]
I was trying to create a stackblitz to show the issue, but it somehow worked. So i found out i had a set height on the body element.

**Comment by irfanghat** [comment]
Glad you found a working solution. I was thinking you could try listening to any route change events. Maybe using an event emitter then create a new service to handle the communication between your components. Thanks for sharing the snippet. Will look into it further.
