### ISSUE TITLE
Typescript Types Not Being Resolved In A Vite Typecript Project

### ISSUE THREAD

**Issue by DevYemi** [darkroomengineering/lenis#174]
**Describe the bug**

Hi there, i just tried using the lenis package in a vite-typescript project and after instaling when i tried importing it into my project i got this error 
![lenis-error](https://github.com/studio-freight/lenis/assets/68167320/b5878e31-0fc6-4392-b557-4e7649b7bba2)

Sorry i couldn't sucessfully reproduce it in codePen

**Comment by clementroche** [comment]
Wich version of Lenis are you using ?

**Comment by DevYemi** [comment]
> Wich version of Lenis are you using ?

I'm using version 1.0.12

**Comment by valentingnt** [comment]
Reproducing it, I don't have the types recognized 👍

**Comment by clementroche** [comment]
I'm not using Typescript at all, any idea how i can solve it ?

**Comment by DevYemi** [comment]
> I'm not using Typescript at all, any idea how i can solve it ?

This is actually a typescript error, typescript is complaining that it can’t find the types of the package (lenis) at the right place, I believe you shouldn’t be having this error if you ain’t using typescript in your project.


Can you provide more details on your error.

**Comment by clementroche** [comment]
> > I'm not using Typescript at all, any idea how i can solve it ?
> 
> This is actually a typescript error, typescript is complaining that it can’t find the types of the package (lenis) at the right place, I believe you shouldn’t be having this error if you ain’t using typescript in your project.
> 
> Can you provide more details on your error.

I'm the maintainer of Lenis, i'm just asking if someone knows how to fix the package because i'm not familiar with TypeScript

**Comment by Lutymane** [comment]
It's because of missing `types` field in exports #181
