### ISSUE TITLE
ScrollTrigger use with horizontal orientation

### ISSUE THREAD

**Issue by jeromeroudaut** [darkroomengineering/lenis#175]
Hello!

I am trying to use Lenis horizontal scrolling with ScrollTrigger to achieve a parallax effect based on the [data-speed] attribute like #113.
The issue I have is that ScrollTrigger doesn't recognize the scroller therefore it can't properly run the animation: https://codepen.io/jeromeroudaut/pen/poxgLMv

Of course, I could use ScrollTrigger's horizontal scroll. However, it doesn't run as smooth as Lenis and kills sticky positioning.

Any idea?

Thank you for your time and dedication 🙏

**Comment by clementroche** [comment]
This is not related to Lenis, you must add `horizontal: true` to ScrollTrigger

```
scrollTrigger: {
  horizontal:true
}
```

**Comment by jeromeroudaut** [comment]
@clementroche Doh, what an idiot I was not to have thought about that line. Lenis is dope! Thank you 🙌
