### ISSUE TITLE
Angular Server-Side-Rendering "window is not defined"

### ISSUE THREAD

**Issue by kiptu-labs** [darkroomengineering/lenis#177]
Everything is working fine when i use lenis in a normal Angular app. But when i use Angular SSR which uses node.js and express to prerender the pages i get the following error:
```
ERROR ReferenceError: window is not defined
    at constructor (./node_modules/@studio-freight/lenis/dist/lenis.modern.mjs:1:4137)
    at constructor (./src/app/app.component.ts:12:25)
```

Obviously one can't use the window object in a server environment, so what can i do now? Also it says SSR-Proof in the documentation but i checked if i have any reference to window but this isn't the case so i guess it has something to do with lenis.

**Comment by kiptu-labs** [comment]
### How to reproduce:
1. Create new angular project: `ng new lenis-test`
2. Navigate to the newly created project and install lenis `npm i @studio-freight/lenis`
3. Replace app.component.ts with:
```ts
import { Component, NgZone, OnInit } from '@angular/core';
import Lenis from '@studio-freight/lenis';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'test';

  public lenis: Lenis = new Lenis();

  constructor(private ngZone: NgZone) { }

  ngOnInit(): void {
    this.lenis.on('scroll', () => {
      console.log('lenis working');
    });

    this.ngZone.runOutsideAngular(() => {
      let raf = (time: any) => {
        this.lenis.raf(time);
        requestAnimationFrame(raf);
      }

      requestAnimationFrame(raf);
    });
  }
}
```
#### If we now run `ng serve` everything is working fine and lenis is working since there is no angular ssr yet
1. Now install Angular SSR package with `ng add @nguniversal/express-engine`
2. Now running SSR in dev mode with `npm run dev:ssr` or in prod with `npm run build:ssr && npm run serve:ssr` throws the following error:
```
ERROR ReferenceError: window is not defined
    at constructor (./node_modules/@studio-freight/lenis/dist/lenis.modern.mjs:1:4137)
    at constructor (./src/app/app.component.ts:12:25)
```

**Comment by clementroche** [comment]
Can't you just conditionally call new Lenis only on client side ?

**Comment by kiptu-labs** [comment]
Yes you are right, i am using ssr for the first time and i tought the packages have to be optimized for server side. I just wrapped it in `isPlatformBrowser` from angular.
