### ISSUE TITLE
Lenis scroll can't reach the footer

### ISSUE THREAD

**Issue by MarinBk** [darkroomengineering/lenis#182]
Hi everyone👋

I tried to apply Lenis scroll on my Webflow website. But when I do it, I am unable to reach the bottom of the page. The scrolling stops before I can reach the footer. So I was wondering if you can help me figure out the reason why.

Here are the website link (where you can see what I mean), and the read-only webflow link

https://marinkurir.webflow.io/

https://preview.webflow.com/preview/marinkurir?utm_medium=preview_link&utm_source=designer&utm_content=marinkurir&preview=e33ca123eedffd24b0896414fdc940ff&workflow=preview

I am also attaching short vid of the problem

https://github.com/studio-freight/lenis/assets/135424930/d5f7b6e9-4bb5-4e08-97b9-c4e3ff4f06cc

So yeah, hopefully you can help with this:) 

Thanks again,
Marin

**Comment by clementroche** [comment]
html {
height: auto;
}

please read the documentation

**Comment by MarinBk** [comment]
Hi @clementroche 👋

Not sure I understand what you mean (I'm not really proficient when it comes to coding 😁)
Where should I insert the code? And what documentation are you referring to?

If you could explain more thoroughly, that would be great 🙏

Thanks again

Marin

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis#keep-html-elements-default-sized-this-is-necessary-for-webflow-implementation-see-issue

**Comment by LeoSeyers** [comment]
> 

He refers to this : https://github.com/studio-freight/lenis#keep-html-elements-default-sized-this-is-necessary-for-webflow-implementation-see-issue

You may look at Webflow own documentation to know how to inject styles
