### ISSUE TITLE
Switch between horizontal and vertical scroll on desktop and mobile.

### ISSUE THREAD

**Issue by rhizodigital** [darkroomengineering/lenis#183]
Iv tried a lot of ways to achieve this, I get it to work, but sometimes the scroll freezes after reloading page. I would like to have horizontal scroll on desktops and vertical on mobile. Im using with gsap and scrolltrigger, is there any way to achieve this? Thank you

**Comment by clementroche** [comment]
just reinit Lenis on media-query change 
https://css-tricks.com/working-with-javascript-media-queries/
