### ISSUE TITLE
Lenis scroll stops working in webflow project with pagination

### ISSUE THREAD

**Issue by teresamtz** [darkroomengineering/lenis#184]
Hi, 

I'm a designer who has stepped into the no-code world so please bear with me since I'm no coding expert.

I designed and developed the following site a few months ago. 
For context: At "[Producciones" section](https://manuel-cabezali-website-38da89672f5745a.webflow.io/producciones), which loads a collection list of +170 elements, webflow automatically creates a pagination every 100 elements. But I didn't want a pagination so I implemented [finsweet's CMS load attribute](https://finsweet.com/attributes/cms-load) to create an infinite scroll.
So far so good. Then, I searched multiple options to have a smooth scroll until I found (and fell in love with) Lenis, which I implemented on the site too. And it worked like a charm for a few months up until recently when I observed the problem that is happening now.

As you can see when you scroll down, right at the point where the page has loaded 100 items the scroll stops working and the only way to move further down is to manually drag the scroll bar. It happens on every browser that I've tested, but only on desktop, it doesn't happen on mobile.

When I remove Lenis' script, the infinite scroll works fine again (you can [check it here](https://www.manuelcabezali.com/producciones))

What bugs me is that it used to work well for the past 7 months. I didn't update Lenis code nor did any other thing to the website, in fact I only noticed the bug because a friend told me.

Anyone can point me in any possible directions? What I've done for now is removing Lenis but I loved having it on the site and would like to be able to keep it.

Many thanks.

**Comment by clementroche** [comment]
Hi, see this issue: https://github.com/studio-freight/lenis/issues/182, you must add `html {height:auto}` to your custom CSS

**Comment by teresamtz** [comment]
Thanks @clementroche. Actually I realized there was a new version of the script and the issue just disappeared when updating the script src to <script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js"></script>

In case it helps anyone else.
