### ISSUE TITLE
PSA for safari users

### ISSUE THREAD

**Issue by mattiacoll** [darkroomengineering/lenis#187]
This isn't really a bug but a general information (might be useful to maybe add a paragraph to the README to le people know about this issue).

I've found out that sometimes the page does not scroll correctly or just hangs while scrolling in Safari on Macos (16.4.1/16.5 were the versions i tested). 

**The issue is not caused by this library but from Safari itself not always firing the `wheel` event (which this library internally relies on)**

The closest issues i could find on bugzilla are [this](https://bugs.webkit.org/show_bug.cgi?id=256582) and [this](https://bugs.webkit.org/show_bug.cgi?id=226080) which seem to be in apple's radar but there is currently no ETA for when they will be fixed.

**Comment by clementroche** [comment]
i think it's the same for iOS

**Comment by Voltra** [comment]
iOS browsers internally all use iOS Safari's rendering engine, so that would make sense

**Comment by clementroche** [comment]
closing this in favor of https://github.com/studio-freight/lenis/issues/103
