### ISSUE TITLE
position:fixed children with scrollbar not working

### ISSUE THREAD

**Issue by adamsbk** [darkroomengineering/lenis#189]
Is there any simple way to fix the following issue?

**how to reproduce child element scrollbar issue:** Page contains child element that has `position:fixed` then `overflow-y:auto|scroll` and the content is overflowing. It is not possible to scroll within the child element. Tested on mac - Safari, Firefox, Chrome

**Example:** e.g. mobile navigation here https://www.dragonfly.xyz/

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis#use-the-data-lenis-prevent-attribute-on-nested-scroll-elements-in-addition-we-advise-you-to-add-overscroll-behavior-contain-on-this-element
