### ISSUE TITLE
Using ScrollTrigger within a nested scroll provider

### ISSUE THREAD

**Issue by joebentaylor1995** [darkroomengineering/lenis#190]
Hi, im wanting to create a specific animation so that when i change pages the entire page rotates and swipes down at an angle.

Without creating a wrapping <div> with a set height and overflow, and just adding the animations, the entire page at the full length, rotates and looks nasty, therefore a parent div is needed to fix this globally across all pages.

However, this is where my issue comes to light - when i target lenis to use the parent div, none f the gsap animations work and are no longer tied to the lenis scroll.

How do i fix this?

**Comment by clementroche** [comment]
this is not related to Lenis, please read [ScrollTrigger documentation](https://greensock.com/docs/v3/Plugins/ScrollTrigger). You have to specify to Scrolltrigger that you gonna use another element.

scrolltrigger: {
 scroller: your_element
}


if you think that's an error please provide a codepen or reproduction link

**Comment by joebentaylor1995** [comment]
What do you mean its not related to lenis? It only breaks when specifying lenis to a different wrapper

**Comment by joebentaylor1995** [comment]
Without even integrating scrolltrigger at this point and just making lenis use a different scroll container, i can no longer scroll the page
