### ISSUE TITLE
Using Lenis on anything but the window and body element breaks

### ISSUE THREAD

**Issue by joebentaylor1995** [darkroomengineering/lenis#191]
When giving lenis a different wrapper and content other than the defaults, the scroll of the page completely breaks and you cannot scroll the page.

Example code:
```
const initSmoothScrolling = () => {
  lenis = new Lenis({
    lerp: 0.04,
    wrapper: wrapperRef.current,
    content: contentRef.current,
    wheelEventsTarget: wrapperRef.current,
  });

  const scrollFn = (time) => {
    lenis.raf(time);
    requestAnimationFrame(scrollFn);
  };
  
  requestAnimationFrame(scrollFn);
};
```

Return...
```
<div ref={wrapperRef}  style={{ height: '100vh' }}>
    <div ref={contentRef}>{children}</div>
</div>
```

**Comment by jakewhiteley** [comment]
Did you add the css required to have a window height scrollable child?

**Comment by joebentaylor1995** [comment]
I tried both with and with no luck

**Comment by joh-sch** [comment]
I'm experiencing a similar issue. 

When I provide some DOM element as the instance wrapper, the instance can only be scrolled a short distance and it can only be scrolled further by clicking and dragging the scrollbar.

EDIT: This started happening after I updated from v1.0.11 to v1.0.16. (it works when going back to 1.0.11)

https://github.com/studio-freight/lenis/assets/39758027/d4163f0e-0c0a-43c6-a7d9-e829ec9bf736

**Comment by clementroche** [comment]
it works on my side, i think you're missing something. Can you provide a codepen ? @joh-sch @joebentaylor1995 

 reproduction: https://codepen.io/ClementRoche/pen/YzRWwxo

**Comment by joh-sch** [comment]
@clementroche you're right, I only set the `wrapper` but forgot to set the `content` element, everything works as expected now. Thanks for weighing in on this
