### ISSUE TITLE
Skipping/jumping when scrolling with Trackpad in Safari

### ISSUE THREAD

**Issue by tobimori** [darkroomengineering/lenis#198]
**Describe the bug**
When using the Trackpad in Safari with Lenis, and going back and forth, elements are jumping around which looks very buggy.
![CleanShot 2023-07-05 at 11 44 31](https://github.com/studio-freight/lenis/assets/29142128/06be9471-e390-48aa-b0ed-0e741f621b11)

Everything works fine, so this issue is probably in regard on how macOS/Safari accelerates scrolling via Trackpad. I assume the easiest way to fix it would be if we can disable Lenis similar to mobile devices when the trackpad is used?

I assume we can use the non-standard [GestureEvent](https://developer.mozilla.org/en-US/docs/Web/API/GestureEvent) API to detect so.

**To Reproduce**
Use Safari on this [codepen](https://codepen.io/ClementRoche/pen/VwxgZEP) and try to scroll with a trackpad.

**Comment by clementroche** [comment]
Which version of safari/macos are you using ?

**Comment by tobimori** [comment]
> Which version of safari/macos are you using ?

17 / Sonoma

okay, just checked: can't reproduce it on non-sonoma. god lord 😂 
will re-open if it comes to stable.
