### ISSUE TITLE
How to hide Lenis.js from Wappalyzer

### ISSUE THREAD

**Issue by lucacv** [darkroomengineering/lenis#199]
Hi, 

I'm trying to figure out how to hide Lenis.js from Tools like Wappalyzer.
I have my Lenis.js library in my folder.

Huge thanks all.

**Comment by clementroche** [comment]
Can i ask you why do you want to achieve this ?

**Comment by lucacv** [comment]
To avoid the curious knowing that I use Lenis as a library :)

**Comment by arzafran** [comment]
I still don't understand why you would want that, but i'll close the issue because we can't provide support for that.
