### ISSUE TITLE
Can't get this running

### ISSUE THREAD

**Issue by ghost** [darkroomengineering/lenis#2]
Hi @studio,

./ path and folder problems in Visual Code, can't get this module running. 
Are there other ways to import this .js ?

Thank you

**Comment by clementroche** [comment]
yo @freieradikale, can you explain a bit more your issue, are you trying to import Lenis in your project or just run the repository locally ?

**Comment by ghost** [comment]
Sure,

i'am trying to run it locally. `import Lenis from '@studio-freight/lenis/'` in a index.js file. I am getting this:
Uncaught TypeError: Failed to resolve module specifier "@studio-freight/lenis/". Relative references must start with either "/", "./", or "../".

'/node_modules/@studio-freight/lenis/'`
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Hope you can help me.
Andreas

**Comment by clementroche** [comment]
i'm not sure to understand but to run the repository locally you don't need to `import lenis from @studio-freight/lenis`, it's already in /src/lenis.js. See how it's imported in the [documentation](https://github.com/studio-freight/lenis/blob/main/docs/index.js). 
If you're trying to import lenis in your app you should first run `npm i @studiofreight/lenis` in your terminal then use `import lenis from @studio-freight/lenis` in your .js file

**Comment by ghost** [comment]
Doesn't work for me. Sorry.
