### ISSUE TITLE
Parallax!!!

### ISSUE THREAD

**Issue by vickykeen** [darkroomengineering/lenis#20]
Hi its not an issue but just an enquiry is there any inbuilt parallax available for this smooth scroll
thank you

**Comment by ffdead** [comment]
Please don't bloat this scrollbar with parallax. People can implement their own parallax on top IMHO 😇

**Comment by clementroche** [comment]
Hi, there is no plan to add built-in parallax system. As @ffdead mentioned you should use your own animation system on top of Lenis. I recommand you GSAP Scrolltrigger but it's just a matter of preference.
