### ISSUE TITLE
Title: How can I make the browser UI auto-hide with smooth touch enabled ?

### ISSUE THREAD

**Issue by Aaryan121** [darkroomengineering/lenis#200]
Description:
Hello,

I'm currently working on a web project and I'm using the Lenis library for UI development. I want to implement a feature where the browser UI (such as the address bar and navigation buttons) automatically hides when the user scrolls down, and smoothly reappears when the user touches the screen. I believe this behavior can greatly enhance the user experience.

I would appreciate any guidance or code examples on how to achieve this using the Lenis library. Thank you in advance for your help!

**Comment by clementroche** [comment]
you should use `syncTouch` instead of `smoothTouch`

**Comment by Aaryan121** [comment]
same issue still the browser UI is not hiding

**Comment by Aaryan121** [comment]
still looking for a workaround ? or is this a feature in latest version ?

**Comment by clementroche** [comment]
no status

**Comment by iamlinkus** [comment]
@Aaryan121 unless you're doing something like webgl where you need to sync your webgl canvas objects to the scroll position, I'd not use the syncTouch (or the old smoothTouch if you're on the older version of Lenis). Apart from scroll direction, this will keep lenis working, but revert to native scrolling on touch devices (which is always better for touch users, unless, as I mentioned, you need to sync your scroll to webgl).

**Comment by clementroche** [comment]
it seems there is no way to show/hide address bar programmatically and this is unrelated with Lenis.
