### ISSUE TITLE
pull-to-refresh on mobile jumps

### ISSUE THREAD

**Issue by paschneider** [darkroomengineering/lenis#203]
**Description**
Pull-to-refresh on mobile devices does not work correctly. 
If you pull down, lenis homepage you can see it.

**To Reproduce**
Open https://lenis.studiofreight.com/  on iOS with chrome (v 114.0.5735.124)  - here it is flickering.

On iOS with Safari it works one time and after that, you can not scroll anymore.

Tested on:
iOS Version: 16.5.1
iPhone 12 Pro

The error only occurs if `syncTouch: true`

Screencast chrome:
https://github.com/studio-freight/lenis/assets/4271565/e48535a6-149d-4eba-9361-e23f467d5c3c

Thanks for supporting this!

**Comment by clementroche** [comment]
Hi @paschneider, are you using `syncTouch` option ? If so can you tweak `__iosNoInertiaSyncTouchLerp` using 1.0.17 until you find the right value, 1 should be the ideal (it works prefectly on Android) but iOS is random (as always). It's currently using 0.4, the closest to 1 the better it is. It would be very useful for everybody using Lenis if you're able to find the right value.

https://github.com/studio-freight/lenis/releases/tag/1.0.17
