### ISSUE TITLE
Uncaught ReferenceError: smooth is not defined

### ISSUE THREAD

**Issue by balramxyadav** [darkroomengineering/lenis#208]
Uncaught ReferenceError: smooth is not defined

Suddenly without doing anything, I am getting this error on my website.

I don't have any other code I just have the basic setup.

I tried to replicate it in Codepen and it gives the same error so I think it's an issue with the lib can anyone tell me how to fix it or if there is an older version that would work?

https://codepen.io/veuxon/pen/NWEzNGZ

**Comment by arzafran** [comment]
that codepen seems to work ok, no errors are logged in the console.

**Comment by balramxyadav** [comment]
Try to run it in a live view. The little external link button at the bottom it logs that error

**Comment by balramxyadav** [comment]
> that codepen seems to work ok, no errors are logged in the console.

Hey, can you please help me with it?

**Comment by Jman80** [comment]
This has happened to me too. "Uncaught ReferenceError: smooth is not defined". Was just working on this last night, everything was fine and woke up to this message....

**Comment by jeanleroy64** [comment]
Same here "Uncaught ReferenceError: smooth is not defined". Was working fine until yesterday evening.

**Comment by clementroche** [comment]
the codepen you shared works without any error logged, please share it again with more context.

In the last Lenis version i removed legacy options (from v0) such as `smooth`, `direction`, `gestureDirection` and `mouseMultiplier`. If you used one of them, please refer to the documentation or stick lenis to @1.0.16 instead of @latest

**Comment by jackkemmish** [comment]
Can confirm i'm seeing the same issue. I'm referencing the CDN link in the README "<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js"></script>" and have just this config:
`const lenis = new Lenis({
	lerp: 1,
	duration: 2
});

lenis.on("scroll", ScrollTrigger.update);

gsap.ticker.add((time) => {
	lenis.raf(time * 1000);
});

gsap.ticker.lagSmoothing(0);`

**Comment by swann19** [comment]
Hi!
Same problem here! Everything was perfect last night and this morning "smooth is not defined". 

I didn't change anything on my code.

If somebody has a tip, please share it :-)

**Comment by jeanleroy64** [comment]
> Hi! Same problem here! Everything was perfect last night and this morning "smooth is not defined".
> 
> I didn't change anything on my code.
> 
> If somebody has a tip, please share it :-)

Try switching back to lenis @1.0.16, it did the trick for me

**Comment by clementroche** [comment]
None of you is able to provide a codepen where the error appears ?

**Comment by Jman80** [comment]
I guess we are all liars wasting our time coming here to let you know your plugin is not working. You have given access to the public domain to use this plugin the least you can do is take our word for it.

An update has clearly happened and broken code down our end, something which is terrible as we have cantered our design/code around this clearly temperamental plugin. I suggest we look for another alternative guys cuz I can see this happening again.

**Comment by swann19** [comment]
> None of you is able to provide a codepen where the error appears ?

Dont know if it can help, but there's a live exemple where the bug appears => [here](https://www.maws.studio/)

Hope you can see something i didn't.

**Comment by clementroche** [comment]
@Jman80 thank you for your message, it's very kind from you. You selfish, you rely on OSS and it's fully free for everybody and you still complaining, you don't even imagine how webflow users are demanding on this library. If you want a special support just pay me and i'll be available asap to fix it. If not i'm spending my time on important tasks i have to do in my day. 

I provided a fix like 3 hours ago, use "https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.16/bundled/lenis.min.js" while i'm finding the solution. I mentioned couple of time that webflow users should stick lenis version while using it, otherwise it's gonna happen again and again.

**Comment by swann19** [comment]
@clementroche Sorry Clément! I didn't wrote the right path to fix at 1.0.16!

Thanks for your tip and that very good pluggin!

**Comment by clementroche** [comment]
can you try with https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.19/bundled/lenis.min.js @swann19

**Comment by Jman80** [comment]
@clementroche I appreciate the fix you did 3hrs ago and I did see this , I just think you need to be a bit more polite and understand that we are not here to mess you about, we all came here for help. Cheers.

**Comment by swann19** [comment]
> https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.19/bundled/lenis.min.js

@clementroche 

Tested in local and web : That works!

Thanks!

**Comment by clementroche** [comment]
https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js has been fixed but you should always stick a version using <script>
