### ISSUE TITLE
Horizontal scroll is not working

### ISSUE THREAD

**Issue by DaniAcu** [darkroomengineering/lenis#209]
**Describe the bug**
When you try to use lenis in a horizontal scrolled it doesn't work. I tried to use inside a section and as global scroll, but the wheel doen't have any effect.

**To Reproduce**
Codesanbox: https://codesandbox.io/s/lenis-horizontal-scroll-gfcxq9?file=/index.html

scroll down with the wheel and nothing happens

**Comment by rollakal** [comment]
With using  `gestureOrientation: "both"` its working.  Don't know if it's intended to be like this. With a quick look every example seems to use this setting. 

Checkout https://codesandbox.io/s/react-lenis-horizontal-scroll-wh50q7 @arzafran react example to get some informations.

**Comment by clementroche** [comment]
@DaniAcu please update lenis version, it works for me https://codesandbox.io/s/mp5ygx

**Comment by DaniAcu** [comment]
It doesn't work in your example. But the example of [rollakal](https://github.com/rollakal) it works. I dont know why, but I will check it

**Comment by DaniAcu** [comment]
**gestureOrientataion** should be **_"both"_** to make it work.
