### ISSUE TITLE
Unable to scroll

### ISSUE THREAD

**Issue by ericderid** [darkroomengineering/lenis#212]
I tried to install Lenis with the basic setup but now I'm unable to scroll at all. Scrolling is only possible with the scrollbar, not the mouse or trackpad. In the html I can see that Lenis is installed (it adds the classes when scrolling). I don't see errors in the console. Do you have any idea what the issue could be? 

I already tried:
-Turning off all CSS
-Turning off al Javascript except Lenis.
-Different browsers

**Comment by clementroche** [comment]
please provide a codepen/codesandbox

**Comment by ericderid** [comment]
I had some trouble setting up a codesandbox (lots of files and folders). But here is a link you can inspect, hope that also works to take a look? https://phpstack-798670-3765821.cloudwaysapps.com/ 
 On Android and IOS it works normally but on desktop (mac) it does not scroll.
 Thanks in advance for a reply!

**Comment by clementroche** [comment]
since this minimal setup works https://codepen.io/ClementRoche/pen/VwxgZEP, you might do something wrong somewhere else. Can you share your Lenis implementation ?
Are you using JavaScript somewhere ?
