### ISSUE TITLE
Smooth is not defined

### ISSUE THREAD

**Issue by SamCharpentier** [darkroomengineering/lenis#224]
I see this error on the console of my website:

Uncaught ReferenceError: smooth is not defined
    at new t (lenis.min.js:2:233)

What is weird is that it's only happening on the live domain, on the webflow subdomain there's no error. But it's using exactly the same code:
https://www.skytree.eu/
https://skytree.webflow.io/

I see this error on some of my sites using Lenis but not all
    
<img width="620" alt="Capture d’écran, le 2023-09-05 à 22 56 10" src="https://github.com/studio-freight/lenis/assets/79227753/329631f3-bf58-403a-8653-ab6ed0eeaab2">

I use this Lenis version:
https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js

**Comment by bolk-studio** [comment]
I can report the same issue on my website: https://decent-dao-2023-rd-before-transfer.webflow.io/

<img width="345" alt="Capture d’écran 2023-09-06 à 09 05 52" src="https://github.com/studio-freight/lenis/assets/103668998/dcce3fb9-09b0-4a30-90e2-e268a5973784">
<img width="474" alt="Capture d’écran 2023-09-06 à 09 06 04" src="https://github.com/studio-freight/lenis/assets/103668998/81a953f2-098e-4f87-a0bc-0740af456479">

We also use this Lenis version:
https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js

**Comment by bolk-studio** [comment]
On my end, using this file https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.22/bundled/lenis.min.js instead of https://cdn.jsdelivr.net/gh/studio-freight/lenis@1/bundled/lenis.min.js fixed the problem.

**Comment by clementroche** [comment]
Just use https://cdn.jsdelivr.net/gh/studio-freight/lenis@1.0.22/bundled/lenis.min.js as @bolk-studio mentioned.
I fixed the @1 anyway, it now redirects to @1.0.22 correctly
