### ISSUE TITLE
Problems with latest version 1.0.22

### ISSUE THREAD

**Issue by abren93** [darkroomengineering/lenis#226]
I spent the last couple of days trying to figure out why the scrolling is not working on my macbook.
Also, I compared and adapted the html and css with one of the sites using lenis and still faced the same issue.
Since I got this library working in the past, I wanted to give another version (1.0.7) a try, which works.

I would like to use the latest version if possible.
Since I do believe someone tested this version before publishing it, I'll try to give as much details as possible:

MacOs Monterey 12.2.1
Chrome 111.0 
Firefox 117.0
Both scrolling with mouse and touchpad are not working.
Mobile device mode and swiping on iphone and android work.

I noticed that the "lenis-scrolling" class is added once and never removed even if the scrolling stopped.

Thank you

**Comment by clementroche** [comment]
please provide a codesandbox

**Comment by clementroche** [comment]
i'm closing the issue because lack of activity
