### ISSUE TITLE
Issue with Finsweet TOC attributes in Webflow

### ISSUE THREAD

**Issue by ED-Saurabh** [darkroomengineering/lenis#228]
In a project, if you use Finsweet's Table of Contents the lenis code doesn't work correctly.

We have a library for TOC functionality 
https://finsweet.com/attributes/table-of-contents

Which uses this script file - https://cdn.jsdelivr.net/npm/@finsweet/attributes-toc@1/toc.js

and the functionality of TOC is with attributes on the rich text with CMS.

When we use this on the website the Lenis seems not to work properly

The issue on this website - https://founderscupid.webflow.io/articles/10-things-nobody-told-you-about-web-design

**Comment by clementroche** [comment]
First of all, please update Lenis to the latest version.
Then as mentionned in the Lenis [documentation](https://github.com/studio-freight/lenis#manually-use-lenisscrolltoanchor-on-anchor-link-click-see-issue), anchor links need `onclick="lenis.scrollTo('#anchor')"`

This snippet should work
```js
const anchorLinks = document.querySelectorAll("a[href]").filter((element)=>element.getAttribute("href").includes('#'))

anchorLinks.forEach((link)=>{
const anchor = link.getAttribute("href")
link.addEventListener('click', (e)=>{
  e.preventDefault()
  lenis.scrollTo(anchor)
})
})
```

**Comment by ED-Saurabh** [comment]
Hey, sorry if I didn't explain it clearly, but it's not an anchor link issue.
The entire page scroll is not working, here a loom video - https://www.loom.com/share/1316b3ae0ee84b3cbcfccc0f69dfef66?sid=24ac25b0-5374-41f4-95f6-bedd3c15cde4

Can you check and tell me what should I change or consider changing?
Plus this only happens when I am using TOC from Finsweet, if I remove the script file, it works perfectly fine.

**Comment by clementroche** [comment]
`scroll-behavior: smooth;` is being added, just remove it.

```css
.lenis.lenis-smooth {
  scroll-behavior: auto !important;
}
```
