### ISSUE TITLE
Error with Lenis constructor types in Typescript

### ISSUE THREAD

**Issue by Cronoz1994** [darkroomengineering/lenis#229]
**Error**
When running a project with Angular v13, the Lenis constructor types gives an error and does not allow you to continue. When that line is deleted everything works correctly.

![image](https://github.com/studio-freight/lenis/assets/17599017/11211184-2d5c-432d-9dbb-2f5b156de04d)

**Comment by clementroche** [comment]
fixed in v1.0.24
