### ISSUE TITLE
NextJs example

### ISSUE THREAD

**Issue by sniperyork** [darkroomengineering/lenis#23]
First of all, thanks for the fantastic plugin.
I wonder if there's an example demonstrating how to correctly implement it in a NextJs project? I followed the doc's basic setup and put it inside a useEffect hook with a return func that destroys the instance on route change, but it seems like nothing works. Any pointers would be greatly appreciated!

here's my setup:

```
import Lenis from "@studio-freight/lenis";

export default function Home(){

  useEffect(() => {
    if (!lenis) return;
    const lenis = new Lenis({
      duration: 1.2,
      easing: (t) => (t === 1 ? 1 : 1 - Math.pow(2, -10 * t)), // https://easings.net
      smooth: true,
      direction: "vertical",
    });

    const scrollFn = () => {
      lenis.raf();
      requestAnimationFrame(scrollFn);
    };
    requestAnimationFrame(scrollFn);

    return () => {
      if (lenis) {
        lenis.destroy();
      }
    };
  }, []);
}

```

**Comment by clementroche** [comment]
Hi yes you can check our implementation on our Next.js Starter [Satus](https://github.com/studio-freight/satus/blob/main/layouts/default/index.js).

Btw, it seems like your looking for `lenis` variable which doesn't exist yet so it can't work.
