### ISSUE TITLE
scroll in other dialogs trigger lenis 

### ISSUE THREAD

**Issue by nort3x** [darkroomengineering/lenis#231]
i  have two other dialogs:
* orbit control of threejs
* map dialog
these components consume scroll and behave accordingly,  
but when i use `lenis` in my parent component not only they react to that scroll but also my main page scrolls,  
i couldn't find anything in documents  
currently i was able to avoid this by `lenis.stop() lenis.start()` based on whether or not that component is active but this tedious and i'm not sure i'm in the right path

- best regards

**Comment by clementroche** [comment]
please provide a codesandbox

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis#use-the-data-lenis-prevent-attribute-on-nested-scroll-elements-in-addition-we-advise-you-to-add-overscroll-behavior-contain-on-this-element
