### ISSUE TITLE
gestureOrientation: 'both' blocks click event on mobile

### ISSUE THREAD

**Issue by joh-sch** [darkroomengineering/lenis#234]
## **Describe the bug**

When creating a Lenis instance with the config. `gestureOrientation: 'both'`, click events on DOM elements inside the instance’s `scrollContent` element seem to be blocked »on mobile«.

To clarify what »on mobile« means in this context: An event handler assigned to the `click` event (or any other mouse event) on an element inside the Lenis instance el. is triggered when executing the click in a regular browser window (tested in Chrome); when switching to Chrome’s Device Mode, the event and/or the handler is no longer being triggered. This seems congruent with the behavior on an actual mobile device (tested in Safari on an iPhone 12 Mini). This issue seems to only occur when the `gestureOrientation` option is set to `both`.

## **To Reproduce**

I've created a simple, reduced test case to demonstrate the issue described above: https://codepen.io/schmoll-studio/pen/yLGvREd

In this test case, the Lenis instance contains a number of sections. Clicks on each section are being listened to and upon a click occurring, a count displayed in the section element is incremented. The count increments as expected when clicking a section in a regular browser window, not however when switching to the device mode/mobile view. When setting the `gestureOrientation` to `vertical`, the click handler is triggered in both, the regular and the device mode.

Here’s a video showing the behavior to go along with the Codepen:
https://github.com/studio-freight/lenis/assets/39758027/b0b1cab2-dffb-4965-8693-9229d6e42f86

**Comment by clementroche** [comment]
fixed on v1.0.25

https://codepen.io/ClementRoche/full/eYbKzQp
