### ISSUE TITLE
Disable lenis on html elements programmatically (alternative to data-lenis-prevent)

### ISSUE THREAD

**Issue by Amaca** [darkroomengineering/lenis#239]
Hello, I am using barba.js to manage transitions between pages and lenis for smooth scroll. My site is working as a one page application in javascript so I have to manage all the scripts initialization when I change pages, adding/deleting listeners, parsing the dom to make all works. I was wondering if I can programmatically prevent lenis on html element in same way.

 I need the same behavior of data-lenis-prevent but programmatically or I would like to know if exist a method to parse the dom to find data-lenis-prevent elements and start again the script to prevent that.

if not, do you know what exactly do the data-lenis-prevent attribute? Maybe I can make on my own with some indications. Thanks

_Originally posted by @Amaca in https://github.com/studio-freight/lenis/discussions/238_

**Comment by clementroche** [comment]
Do you want to prevent the scroll while page transition ?

**Comment by Amaca** [comment]
No, I don’t have problems on transitions. I used the attribute on modals or fixed panels toggled by user where I need a default scrollbar.

 I think that lenis check data-lenis-prevent elements only on lenis init. When I change the page, the dom is recreated by javascript then the data-lenis-prevent elements of the new current page are not readed from the first initialization. So I should find a way to make the prevent elements works after a page change. 

I need something like a refresh method that find again the prevent items of the current updated dom without reinitializing lenis.

**Comment by clementroche** [comment]
`data-lenis-prevent` is 100% dynamic, it simply prevents the wheel events that passed through the given element. It doesn't need to be reinit, you're certainly doing something wrong. Please provide a codepen

**Comment by clementroche** [comment]
closing this issue because the lack of activity
