### ISSUE TITLE
[QUESTION] GSAP ScrollTrigger integration still required?

### ISSUE THREAD

**Issue by LucaArgentieri** [darkroomengineering/lenis#243]
[GSAP ScrollTrigger integration](https://github.com/studio-freight/lenis#gsap-scrolltrigger-integration) still required?
I tried using the ScrollTrigger without [this integration](https://github.com/studio-freight/lenis#gsap-scrolltrigger-integration) and it works very well.
is it still necessary to use it?

**Comment by clementroche** [comment]
Can you provide a codepen ?

**Comment by LucaArgentieri** [comment]
> Can you provide a codepen ?

Sure, sorry I didn’t send it to you earlier
https://stackblitz.com/edit/github-ayiujq?file=app.vue

**Comment by LucaArgentieri** [comment]
Maybe I’m making a mistake
Integration only serves when using lenis data with the ScrollTrigger
Can you confirm that?

**Comment by clementroche** [comment]
Your example is pretty simple and doesn't need any "perfect sync" to work visually. 
[GSAP ScrollTrigger integration](https://github.com/studio-freight/lenis#gsap-scrolltrigger-integration) is not mandatory but highly recommended if you want a perfect sync and better performance
