### ISSUE TITLE
Setting velocity does not seem to have any effect

### ISSUE THREAD

**Issue by GaelPQCQ** [darkroomengineering/lenis#246]
I would like to reduce the velocity when a specific item is visible but doing `lenis.velocity = 0;` does not seem to have any effect.

Do you have any idea on how to achieve this effect?

**Comment by clementroche** [comment]
`velocity` is only a getter. From what I understand you want to reduce the "speed" of lenis on the fly ?

There is not built-in solution for that but you can try to update `lenis.options.lerp`, it should work.

**Comment by GaelPQCQ** [comment]
Ah maybe we should add "(getter)" to velocity in the readme.

Updating lerp is a good idea thank you, will try!
