### ISSUE TITLE
Lenis is lagging with GSAP in Nextjv13 Page Router

### ISSUE THREAD

**Issue by dhavalveera** [darkroomengineering/lenis#250]
Hey All,

recently I came across the Lenis for Smooth Scrolling along with GSAP, and I am using Lenis directly from `import Lenis from '@studio-freight/lenis'` but when I load my Nextjs Page, and try to scroll down with mouse scroll, it's lagging tooo much and all of a sudden it scroll somewhere down, and below is my Code, and I was trying multiple & all possible solutions from Google/Internet

```js
useIsomorphicLayoutEffect(() => {
    // initialize lenis smooth scrolling
    const lenis = new Lenis({
      lerp: 0.07, // animation smoothness (between 0 & 1)
      wheelMultiplier: 0.7, // scrolling speed for mouse wheel
      touchMultiplier: 0.7, // scrolling speed for touch events
      smoothWheel: true, // smooth scrolling for while events
      smoothTouch: true, // smooth scrolling for touche events
      orientation: 'vertical', // orientation of the scrolling (vertical/horizontal)
      gestureOrientation: 'vertical', // orientation of the gestures (vertical/horizontal)
      normalizeWheel: false, // Normalize wheel inputs
      infinite: false, // infinite scroll
      autoResize: true,
    })

    function raf(time) {
      lenis.raf(time)
      requestAnimationFrame(raf)
      gsap.ticker.fps(60)
    }
    requestAnimationFrame(raf)

    const ctx = gsap.context(() => {
      const timeln = gsap.timeline({ paused: true })

      timeln.to(ImgInnerRef.current, {
        width: '100vw',
        borderRadius: '00px',
        duration: 1000,
        // ease: 'none',
        scrollTrigger: {
          start: 'top center',
          end: '+=120%',
          scrub: true,
        },
      })
    })

    return () => ctx.revert()
  }, [])
```

I've also tried to destroy the lenis in the clear up function of `useEffect()` like `return () => { lenis.destory() }` but unfortunately that also didn't worked for me.

any one can please help me to resolve this issue?

**Comment by arzafran** [comment]
Hey @dhavalveera, thanks for reaching out, i have two questions, first, have you tried using [react-lenis](https://github.com/studio-freight/react-lenis)? do you have the same issue with it?
second, could you provide a codesandbox that replicates the issue?

**Comment by dhavalveera** [comment]
Hello @arzafran, Thanks for replying on my issue.

1. I tried to check [react-lenis](https://github.com/studio-freight/react-lenis), but didn't found the proper documentation to use it.
2. it's my Company Project, so I can't make a codesandbox of it, I'm Sorry for that


Also, @arzafran , does in CSS Code, if I've following properties, then does it can make issue?

```css
html, body, * {
scroll-behavior: smooth;
}

**Comment by clementroche** [comment]
remove `scroll-behavior: smooth;` @dhavalveera
