### ISSUE TITLE
smoothWheel's default value is `true` and not `false` as stated in the README

### ISSUE THREAD

**Issue by Allaoua9** [darkroomengineering/lenis#258]
https://github.com/studio-freight/lenis/blob/f359368b1aeb2b5cc5ca5b750bcbb74b4122d4f3/README.md?plain=1#L67C60-L67C60

PS: thanks for this amazing lib :)
Scroll hijacking might be bad, but it feels so damn good to hijack it ! cause right now, scrolling customization options in the web is just mediocre to say the least

**Comment by clementroche** [comment]
it's fixed, thanks
