### ISSUE TITLE
Back swipe gesture not available

### ISSUE THREAD

**Issue by MatteoGauthier** [darkroomengineering/lenis#26]
Hey I wanted to know if it's possible to enable browser touchpad swipe gesture in order to trigger back / next navigation ? It's caused by `scroll-behavior: initial;`

**Comment by clementroche** [comment]
Hi, actually this seems not caused by `scroll-behavior: initial;` because we don't even use it on the [website](https://lenis.studiofreight.com/). But i can reproduce anyway so something else is causing it, I'm looking for a fix.

**Comment by clementroche** [comment]
It's caused by `overscroll-behavior: none`, it's up to you to enable or disable it. Anyway i enabled it back on the website.

**Comment by MatteoGauthier** [comment]
@clementroche Ok thanks for your answer

**Comment by MatteoGauthier** [comment]
but how can I keep the browser swipe gesture ?

**Comment by clementroche** [comment]
Maybe i'm missing something but as i told you above, just make sure you removed `overscroll-behavior` property from `html` and `body`
