### ISSUE TITLE
scrollTo sometimes produces -1px offset on top when given HTMLElement as target

### ISSUE THREAD

**Issue by Allaoua9** [darkroomengineering/lenis#261]
This happens probably because of the Math.round :

https://github.com/studio-freight/lenis/blob/f359368b1aeb2b5cc5ca5b750bcbb74b4122d4f3/src/index.js#L332

Passing manually the scroll position and using Math.floor resolves this issue for me
```
const position = Math.floor(
        target.getBoundingClientRect().top + lenis.animatedScroll,
      );
lenis.scrollTo(position, {
        force: true,
        lock: true,
      });
```

**Comment by clementroche** [comment]
do you have a reproduction link ?

**Comment by Allaoua9** [comment]
sorry no, I didn't have time to. I'll try and create a reproduction link

**Comment by clementroche** [comment]
i'm closing this because lack of activity
