### ISSUE TITLE
Weird mousewheel behaviour

### ISSUE THREAD

**Issue by ccrch** [darkroomengineering/lenis#265]
Basic setup, minimal css but somehow the scroll doesn't react to mousewheel eventhough it's registering events
Example here: http://gsaplayground.test.vettvangur.info/sticky-sections/

**Comment by clementroche** [comment]
That's not a "basic setup", your page has a lot of CSS and JS involved, it's almost impossible to debug.
Try to remove all your CSS and JS and add it again line by line to notice where it fails.
