### ISSUE TITLE
"background-attachment" property causes janky scrolling on Safari

### ISSUE THREAD

**Issue by AaronMassingham** [darkroomengineering/lenis#266]
**Describe the bug**
More of a PSA - I'm aware that `position:fixed` is on the radar but take care when using the `background-attachment: fixed` property too. This can cause a janky experience while scrolling.

**To Reproduce**
Device: MacBook Pro 15" 2018
Browser ver: Safari v17.0
iOS: Sonoma v14.0

**Comment by clementroche** [comment]
closing this in favour of issue #103

**Comment by 23d1** [comment]
What was the issue, the linked issue is 404...?

**Comment by feledori** [comment]
@23d1 fixed the link

**Comment by 23d1** [comment]
@feledori thanks! Hmm, it seems to potentially be a slightly different topic.

The issue I'm running into is with gsap scrolltrigger and counteracting the smooth scroll with background-position to emulate background-attachment: fixed. Scrolling sort of grabs those elements, similar to how a page would work when touch scrolling on an iDevice. It's still smooth, but sort of springs out of place and back into into place with every scroll up and down, and then jitters into place across the easing. This is the case across Chrome and Safari.

**Comment by feledori** [comment]
hmm, @clementroche you know more.

**Comment by clementroche** [comment]
@23d1 please provide a reproduction link
