### ISSUE TITLE
Problem scrolling on the blog

### ISSUE THREAD

**Issue by zadesign** [darkroomengineering/lenis#268]
I have been using this JS for a long time. Now I have the problem that "only" on my blog I can not scroll to the end of site. 

When scrolling with the mouse I get stuck at about 3/4. I have deleted and tested all my JS and CSS files. It's definitely Leni's JS. I delete all Margin Top. Same Problem.

I have tested it with Chrome, Safari, Firefox. Everywhere the same Issue.

If I manually reduce the height of the browser window, I can scroll to the end again.

Do you already know this issue?

Thank you.

**Comment by clementroche** [comment]
We need a reproduction link

**Comment by zadesign** [comment]
Thank you

> We need a reproduction link

**Comment by clementroche** [comment]
Your content has `position: absolute`, just remove it. I'm closing this issue since it's not related to Lenis but about your CSS.
