### ISSUE TITLE
Application error when scroll up on iOS

### ISSUE THREAD

**Issue by haidave** [darkroomengineering/lenis#27]
Hi there!

There is an `Application error: a client-side exception has occurred)` when you scroll to the top on iOS (Safari).

Demo:

https://user-images.githubusercontent.com/34862272/190872325-44a37a44-d62e-4fd6-bf83-a538db374ad7.MP4

**Comment by arzafran** [comment]
This is fixed on latest versions of the website/library. thanks for the heads up!
