### ISSUE TITLE
Scrolling does not work in native dialog boxes

### ISSUE THREAD

**Issue by Blakeinstein** [darkroomengineering/lenis#270]
**Describe the bug**
Upon showing a dialog, lenis continues to scroll the top layer

**To Reproduce**
https://svelte.dev/repl/0444f20c2d97446a9fcc0bb6627a8886

Since I am using svelte, I have a REPL ready to reproduce this behaviour.

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis#nested-scroll
