### ISSUE TITLE
scrollTo sometimes does not complete when using a touchpad 

### ISSUE THREAD

**Issue by ivan-pixels** [darkroomengineering/lenis#271]
Hi, Im trying to implement something like scroll snap with lenis, I used the plugin f linked in the readme as a starting point, and it works great with mouse scrolling, but im having an issue with it while using a touchpad, the scrollTo almost never completes (and the onComplete function is never called.

I can get around this by using lock: true, but I like how it works without lock: true on a scroll wheel. I assume this is happening because on the momentum? Is there anyway around this? 

Here is a codepen showint the issus https://codepen.io/hadashi/pen/eYxLbeG

Thanks

**Comment by clementroche** [comment]
Can you isolate your issue as much as possible ? This seems too complex to be fixed as it is now, it may not be an actual "issue" but more related to what you're trying to achieve.
