### ISSUE TITLE
Is it possible to use two instances of Lenis? One in the body and another inside a modal?

### ISSUE THREAD

**Issue by Javier2x** [darkroomengineering/lenis#273]
**Describe the bug**

**To Reproduce**
Try to reproduce your issue by forking this [codepen](https://codepen.io/ClementRoche/pen/VwxgZEP). 
If you can't reproduce it, it means there is something wrong on your initial environment.

**Comment by clementroche** [comment]
Of course, just call `new Lenis( { wrapper, content } )` using modals elements.
