### ISSUE TITLE
ScrollTo smooth scroll not working on anchors

### ISSUE THREAD

**Issue by sushantgwr87** [darkroomengineering/lenis#277]
Firstly, this is a great package which I have used before with Next.js Page routing.

## Overview and Tested Options
Now since introduction of App Routing in Next.js, issues are arising in scrolling anchors. Well after reading documentation it was mentioned for anchor links scroll, use `lenis.scrollTo()`.

Also checked this issue [#217](https://github.com/studio-freight/lenis/issues/217) but didn't helped much.

## Problem
I want to smooth scroll to anchor link, I added lenis separately without wrapping the app, used this [codesandbox](https://codesandbox.io/p/devbox/wonderful-field-t35tm8?file=%2Fcomponents%2Flenis-scroller.tsx%3A36%2C1) example for setup, found it here - issue #170 .

Here is a short version I created:
[codesandbox devbox](https://codesandbox.io/p/devbox/qtxymh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqpionas0006356d18pvnxud%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqpionar0002356dhhx785x3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqpionas0003356d18j7qbm5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqpionas0005356d92k9y4gd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqpionar0002356dhhx785x3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpionar0001356d50e43akn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqpionar0002356dhhx785x3%2522%252C%2522activeTabId%2522%253A%2522clqpionar0001356d50e43akn%2522%257D%252C%2522clqpionas0005356d92k9y4gd%2522%253A%257B%2522id%2522%253A%2522clqpionas0005356d92k9y4gd%2522%252C%2522activeTabId%2522%253A%2522clqpjfkux00yn356di8csjmxr%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqpjfkux00yn356di8csjmxr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2523about%2522%257D%255D%257D%252C%2522clqpionas0003356d18j7qbm5%2522%253A%257B%2522id%2522%253A%2522clqpionas0003356d18j7qbm5%2522%252C%2522activeTabId%2522%253A%2522clqpjfbou00w3356dv9ju0f4r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpjfbou00w3356dv9ju0f4r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqpjfbql0017efk5brgn9tf0%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Would like to know correct variation or work around this.

**Comment by clementroche** [comment]
So you're asking how to have smooth anchor scrolling within a react server component ?

You could use a generic function that select all <a> using an anchor link as href

```js
const anchorLinks = [...document.querySelectorAll("a[href]")]
  .filter((a) => a.href.includes('/#'))
  .forEach((a) => {
    a.addEventListener('click', (e) => {
      e.preventDefault()
      const href = '#' + a.href?.split('/#').at(-1)

      lenis.scrollTo(href)
    })
  })
```

**Comment by sushantgwr87** [comment]
> So you're asking how to have smooth anchor scrolling within a react server component ?

Yes. 😅 Though not well versed with this app routing and server side yet. Also thanks for quick response.

I added this generic function by creating a client side wrapper component like this:
```
"use client";
import { useEffect } from "react";
import Lenis from "@studio-freight/lenis";

const Wrapper = ({ children }) => {
  const lenis = new Lenis();

  useEffect(() => {
    const anchorLinks = [...document.querySelectorAll("a[href]")];
    anchorLinks
      .filter((a) => a.href.includes("/#"))
      .forEach((a) => {
        a.addEventListener("click", (e) => {
          e.preventDefault();
          const href = "#" + a.href?.split("/#").at(-1);
          console.log(href);
          lenis.scrollTo(href);
        });
      });
  }, []);

  return <div>{children}</div>;
};

export default Wrapper;
```

And Navbar link is like this:
```
<a
      href={"/#about"}
      className="relative text-inherit"
>
      About
 </a>
```

Though still not working as expected, I can see hashes in console.log but don't understand what is going wrong here as onClicking the link nothing works. I have updated the [codesandbox](https://codesandbox.io/p/devbox/lenis-anchor-test-forked-fz3t7k?file=%2Fsrc%2Fcomponents%2FWrapper%2Findex.js%3A1%2C1-25%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqpionas0006356d18pvnxud%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqpionar0002356dhhx785x3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqpionas0003356d18j7qbm5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqpionas0005356d92k9y4gd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqpionar0002356dhhx785x3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpionar0001356d50e43akn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqq56bib002h3b6aegzpoocq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A42%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A42%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FLenisScroller%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqq5wndf00023b6avzpq20vp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FWrapper%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqpionar0002356dhhx785x3%2522%252C%2522activeTabId%2522%253A%2522clqq5wndf00023b6avzpq20vp%2522%257D%252C%2522clqpionas0005356d92k9y4gd%2522%253A%257B%2522id%2522%253A%2522clqpionas0005356d92k9y4gd%2522%252C%2522activeTabId%2522%253A%2522clqq5x3t9002i3b6ali2xmsc2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqq5x3t9002i3b6ali2xmsc2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqpionas0003356d18j7qbm5%2522%253A%257B%2522id%2522%253A%2522clqpionas0003356d18j7qbm5%2522%252C%2522activeTabId%2522%253A%2522clqpjfbou00w3356dv9ju0f4r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqpjfbou00w3356dv9ju0f4r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqpjfbql0017efk5brgn9tf0%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) here.

**Comment by clementroche** [comment]
Codesandbox is just a nightmare working with Next.js...
You shouldn't have any issue if you have "use client"

**Comment by sushantgwr87** [comment]
@clementroche Thanks for help.

Issue is solved. I just needed to declare lenis in wrapper itself and it worked.
