### ISSUE TITLE
Smooth scroll not working as expected when we use css property `scroll-behaviour:smooth`

### ISSUE THREAD

**Issue by ArshilHapani** [darkroomengineering/lenis#278]
The utilization of `scroll-behavior: smooth;` in conjunction with the `lenis` attribute results in a non-uniform scrolling experience. Specifically, rather than providing a consistently smooth scroll, the page tends to momentarily stick at particular offsets. After a short duration, it then proceeds to scroll the entire page, creating a discontinuity in the expected smooth scrolling behavior.

**Comment by clementroche** [comment]
yes, it's written on the documentation https://github.com/studio-freight/lenis?tab=readme-ov-file#recommended-css

**Comment by ArshilHapani** [comment]
After adding css it still sticks on scroll when 
- We add `scroll-behavior:smooth !important;`  on * selector
- When we change lenis css scroll-behavior from  **auto** to **smooth**

**Comment by clementroche** [comment]
please provide a reproduction link
