### ISSUE TITLE
cdn for Lenis

### ISSUE THREAD

**Issue by liringea** [darkroomengineering/lenis#28]
Good afternoon. Could you please tell me how to add Lenisenis to cdnjs.com ? Just my website is on Tilda builder and I can't install the library via npm

**Comment by clementroche** [comment]
hi, i don't know how cdnjs works but here is what you can use instead
https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.6/bundled/lenis.js

**Comment by liringea** [comment]
> hi, i don't know how cdnjs works but here is what you can use instead https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.6/bundled/lenis.js

Thank you
