### ISSUE TITLE
_lenisRef_current.raf is not a function  | @studio-freight/react-lenis

### ISSUE THREAD

**Issue by brainchildofbalan** [darkroomengineering/lenis#280]
![image](https://github.com/studio-freight/lenis/assets/108955043/fecb3af2-256a-4505-919b-a3c4fab43bc7)

Hi, 

After installing the latest version of the package, an issue has emerged in the code while using https://www.npmjs.com/package/@studio-freight/react-lenis v0.0.40.

I have checked and found this solutuiion 

`lenisRef.current?.lenis?.raf(time  * 1.5)`

Hope you guys should update the doc.
https://www.npmjs.com/package/@studio-freight/react-lenis

Thanks

**Comment by clementroche** [comment]
fixed in v0.0.43 thank you !
