### ISSUE TITLE
Smooth scrolling not working properly

### ISSUE THREAD

**Issue by mxritzdev** [darkroomengineering/lenis#285]
**Describe the bug**
Lenis is behaving really strange: if I scroll, theres a "timeout" and then it scrolls instantly to the position where i scrolled.

**To Reproduce**
I tried to reproduce the steps in codepen, but strangely, it does works there

https://github.com/studio-freight/lenis/assets/101179677/b8ee2290-ef1f-426d-b0a1-4c658c4c8dc4
^Heres A Demo Video^

Thanks for your Help

**Comment by mxritzdev** [comment]
I used the boilerplate code provided in README.md

**Comment by clementroche** [comment]
I'm pretty sure you still have scroll-behavior: smooth ?

https://github.com/studio-freight/lenis?tab=readme-ov-file#recommended-css

**Comment by mxritzdev** [comment]
Thanks, it works now

**Comment by mxritzdev** [comment]
Im sorry to bother again, but now, the smooth scrolling to a #anchor my site is not working anymore. Is there any way to fix this?

**Comment by mxritzdev** [comment]
I also tried this onclick fix, it did not work:
`<a href="#about" onclick="lenis.scrollTo('#about')" class="active"
                >About Me</a
              >`

**Comment by clementroche** [comment]
do a codepen

**Comment by mxritzdev** [comment]
https://codepen.io/mxritzpy/pen/QWopQXq

**Comment by clementroche** [comment]
<img width="433" alt="image" src="https://github.com/studio-freight/lenis/assets/28361254/4a5d41ab-cc4c-4f55-9119-fbc87836311c">

You don't use valid CSS selector as mentioned in the console, if you replace "1" with "anchor1" it works

**Comment by mxritzdev** [comment]
On the codepen, it fixes it, but on my code, it doesnt, is there a problem with my css maybe?
