### ISSUE TITLE
reload from to top?

### ISSUE THREAD

**Issue by heyadeivan** [darkroomengineering/lenis#29]
How do I do it when I reload doesn't save the scroll position, I want to start from the beginning/top

**Comment by clementroche** [comment]
Do you want to reset scroll position on page change ? 
If you want to I advice you to destroy lenis before page destroy and recreate it on page create right after you called window.scrollTo(0,0)

**Comment by sushanyadav** [comment]
in my case setting [scroll-restoration](https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration) to "manual" helped.
