### ISSUE TITLE
Laggy/Jumpy scrolling on Safari (MacOS)

### ISSUE THREAD

**Issue by ulviskaploom** [darkroomengineering/lenis#290]
Hi!
I've been struggling with an odd bug on Safari on Mac. The scrolling is a bit laggy and it seems to "jump" a bit especially when changing the scrolling direction quickly. The bug is most present with images on the page and when using a trackpad. 
The lag can be improved by adding a full-width fixed element at the top of the page, but the "jump" is still present. 

I tried pretty much all the different versions of Lenis and ReactLenis, the same bug persists.

If you have any suggestion on how to fix this, it would be greatly appreciated!

I'm using
MacOS Sonoma 14.3
Safari 17.3

Here's a quick codepen demo:
https://codepen.io/samoned5/pen/ExMLzPb

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis/issues/103

**Comment by alexkuzmin** [comment]
The link https://github.com/studio-freight/lenis/issues/103 is 404. Is here some solution by this bug?

**Comment by clementroche** [comment]
#103  @alexkuzmin
