### ISSUE TITLE
data-lenis-prevent-touch made the toolbar minimised on iOS (used with swiper.js)

### ISSUE THREAD

**Issue by codyng** [darkroomengineering/lenis#293]
**Describe the bug**
data-lenis-prevent-touch made the toolbar minimised on iOS (used with swiper.js)

**To Reproduce**
If inserted a simple horizontal swiper (swiper.js) component normally, the Lenis scroll is fine but then we swiped the swiper horizontally, the page also is scrollable which is a bad UX.

I tried to apply "data-lenis-prevent-touch" data attribute to the swiper container as below:

```
<div class="swiper" data-lenis-prevent-touch>
    <div class="swiper-wrapper">
        <div class="swiper-slide">...</div>
        <div class="swiper-slide">...</div>
        <div class="swiper-slide">...</div>
        <div class="swiper-slide">...</div>
    </div>
</div>

```

It worked perfectly but when the div appeared in the page, the iOS toolbar automatically get minimised. The whole suddenly get "jumped" because of the recalculation of the height of the page and current scrolling position.

**Expected behaviour**
The toolbar won't be minimised even we apply data-lenis-prevent-touch.

**Comment by clementroche** [comment]
can you provide a minimal reproduction link ?

**Comment by clementroche** [comment]
I'm closing this until you provide a reproduction link
