### ISSUE TITLE
Dialog modal content not scrollable, only background scrolls

### ISSUE THREAD

**Issue by ayhan02** [darkroomengineering/lenis#294]
If a dialog modal is open and I want to scroll within the dialog, only the background is scrolled.
When I deactivate lenis it works 

I tried to destroy lenis whenever i open a dialog modal, but when i try to enable it with `lenis.start()`,  the Smooth Scrolling doesn't work anymore.

is there a way to make that work?

**Comment by clementroche** [comment]
you need data-lenis-prevent and to stop lenis on modal open 
https://codepen.io/ClementRoche/pen/PoLdjpw

**Comment by ayhan02** [comment]
So easy ... wow thank you
