### ISSUE TITLE
Infinite Scroll jumps

### ISSUE THREAD

**Issue by joebentaylor1995** [darkroomengineering/lenis#295]
**Describe the bug**
When using the `infinite: true` option, the content loops indefinitely, but there is a notable jump of content vs it looking smooth.

**To Reproduce**
Literally just add `infinite: true` to your lenis config.

Attached is an example of what is happening with my current code. Is there extra steps needed for lenis to calculate infinite scrolling properly?

https://github.com/studio-freight/lenis/assets/54585427/188e6c5f-ec1a-4dcd-8c48-966faee4ea37

**Comment by clementroche** [comment]
To have a seamless infinite list you need to duplicate your content and have it 100vh sized.
Here is an example: https://codepen.io/ClementRoche/pen/OJqBLod

**Comment by joebentaylor1995** [comment]
Hi, I have this and it still doesn't work, do you have any time free to take a look with me so I understand what I may be doing wrong?

I created the clone, but the jump still remains

**Comment by joebentaylor1995** [comment]
I can add you to my repo if need be to look at what I'm doing if need be

**Comment by clementroche** [comment]
What is your email address @joebentaylor1995  ?

**Comment by joebentaylor1995** [comment]
joebentaylor1995@icloud.com

**Comment by joebentaylor1995** [comment]
***@***.*** JoeOn 9 Feb 2024, at 20:57, Clément Roche ***@***.***> wrote:﻿
What is your email @joebentaylor1995  ?

**Comment by clementroche** [comment]
email sent

**Comment by richgcook** [comment]
How did this get resolved? Similar issue. https://alice-waese-dev.netlify.app/jewellery/collections/ss25

**Comment by PaulStaal** [comment]
> How did this get resolved? Similar issue. https://alice-waese-dev.netlify.app/jewellery/collections/ss25

It seems to be working fine (at least right now) on the website you linked, how did you manage to resolve it? :)

**Comment by richgcook** [comment]
I will get back shortly with my code and details 👍🏻

**Comment by PaulStaal** [comment]
Thanks for your quick reply, but in the meantime I finally figured it out.. the jumping I saw was caused by some padding I had set on the <body> element, removing that resolved the issue for me (and hopefully for anyone else reading this in the future)
