### ISSUE TITLE
How it should be?

### ISSUE THREAD

**Issue by thesoldiersway** [darkroomengineering/lenis#299]
I see people have problem with Lenis. You say "as smooth scroll should be". Have you seen GSAP scroll smoother. That is how smooth scroll should be. Lenis have a long way to reach that.

**Comment by clementroche** [comment]
Thank you for your feedback, can you elaborate ? What's better with GSAP ScrollSmoother ?

**Comment by thesoldiersway** [comment]
The idea with a new smooth scroll on the market is amazing. Also the intention. I worked with GSAP smooth and it´s working amazing. I never faced smooth issues and it is really really smooth. The only thing I use from GSAP is the free scroll trigger and the scroll smoother. The problem is for me as for many others that it is not cheap. I mean you are forced to buy the other  GSAP plugins too and can´t buy only the scroll smoother. You give Lenis for free, that is heroic. I think there are a lot of people who will buy only the scroll smoother. In Lenis case, yes I will happily pay for Lenis smooth if it can deliver what GSAP can, that smoothness. GSAP is expensive, forced to buy the whole package. That is negative. Lenis is free and not that smooth as GSAP. That´s not good either. So if you can create a premium version that is GSAP smooth for a normal plugin price. You will save the world. Think about the idea and you also deserve a big thanks for your work.

**Comment by clementroche** [comment]
What do you mean by Lenis not being as "smooth" as ScrollSmoother ? Have you tried to play with `easing`, `duration` and `lerp` ?
