### ISSUE TITLE
Cant start Lenis

### ISSUE THREAD

**Issue by tiagopc** [darkroomengineering/lenis#3]
I installed using NPM and Webpack and when i try to start, i get this error in console:

Unexpected token (53:11) - You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

Is there any dependence i'm missing or am i installing it wrong?

**Comment by clementroche** [comment]
hi, lenis exposes a .esm.js file, maybe your webpack config doesn't support it.

I'm not sure how to do it with webpack but i've found this [issue](https://github.com/facebook/create-react-app/issues/11359).

**Comment by arzafran** [comment]
> Unexpected token (53:11) - You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

would you mind sharing your webpack config?

**Comment by tiagopc** [comment]
@arzafran 
`const mix = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.autoload({
  jquery: [
    "$",
    "window.jQuery",
    "jQuery",
    "window.$",
    "jquery",
    "window.jquery",
  ],
});

mix.setPublicPath("../public_html");
mix
  .copyDirectory("resources/admin/assets", "../public_html/@admin/assets")
  .copyDirectory(
    "node_modules/quill/dist",
    "../public_html/@admin/assets/plugins/quill@1.3.6"
  )

  // Arquivos do site
  .sass(
    "resources/site/assets/sass/vendor.scss",
    "../public_html/assets/css/vendor.css"
  )
  .options({
    processCssUrls: false,
  })
  .sass(
    "resources/site/assets/sass/main.scss",
    "../public_html/assets/css/main.css"
  )
  .options({
    processCssUrls: false,
  })
  .js(
    "resources/site/assets/js/vendor.js",
    "../public_html/assets/js/vendor.js"
  )
  .js("resources/site/assets/js/main.js", "../public_html/assets/js/main.js")
  .js(
    "resources/site/assets/js/pages/home.js",
    "../public_html/assets/js/pages/home.js"
  )
  .sourceMaps();

mix
  .copy("resources/site/assets/fonts", "../public_html/assets/fonts")
  .copy("resources/site/assets/img", "../public_html/assets/img")
  .copy("resources/site/assets/json", "../public_html/assets/json")
  .copy("resources/site/assets/svg", "../public_html/assets/svg")
  .copy(
    "node_modules/@fortawesome/fontawesome-free/webfonts",
    "../public_html/assets/webfonts"
  )

  .browserSync({
    proxy: "localhost:8000",
    files: [
      "resources/**/*.*",
      "app/Http/Controllers/**/*.*",
      "app/Models/*.php",
      "routes/*.php",
    ],
  })
  .version();
`

**Comment by arzafran** [comment]
hmm i'm not sure this is your webpack config file or at least i don't see any references to lenis being imported there 🤔

**Comment by arzafran** [comment]
Will close it since it's impossible to reproduce without having any more information, feel free to open a new one if the error persists!
