### ISSUE TITLE
velocity overshoots zero

### ISSUE THREAD

**Issue by ffdead** [darkroomengineering/lenis#30]
Hey! We noticed the velocity is a bit glitchy when the scroll momentum is about to come to a stop.

The velocity overshoots 0 briefly and switches sign which creates visual glitches when using to animate.

**Comment by arzafran** [comment]
Can you provide a minimal codepen/codesandbox example?

**Comment by clementroche** [comment]
@ffdead it should be fixed in v0.2.8

**Comment by ffdead** [comment]
Didn't have time to provide a sandbox before you fixed it! ✅🚀 

Thanks, nice work!
