### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by thesoldiersway** [darkroomengineering/lenis#303]
I had to come back. I wrote a few days ago about GSAP scrollsmoother and came up with criticism to Lenis. I was stuck with GSAP and Lenis felt confusing until the minute it all worked out. Lenis works great. I got it working more than well, also together with GSAP. Now I am saved and have no reason to use GSAP scrollsmotther anymore. It will be Lenis. However, as the person making the complaint, I have a new complaint. I have a hard time accepting that Lenis is free and calls for a donate button. You work hard and deserve reward. I am convinced that many users want to donate to Lenis that can grow. 1000 thanks!

**Comment by LeoSeyers** [comment]
Would love to donate as well as Lenis is now part of my boilerplate 👍

**Comment by clementroche** [comment]
👀

**Comment by clementroche** [comment]
Good news ! Darkroom can now be supported through Github Sponsors: https://github.com/sponsors/darkroomengineering

cc @thesoldiersway @LeoSeyers
