### ISSUE TITLE
On very first load of the website, not able to scroll till the end

### ISSUE THREAD

**Issue by EmpChirag** [darkroomengineering/lenis#308]
Hello there, I am new to lenis. I have implemented lenis with gsap in my react website but on the very first load of my website, I  am not able to scroll till the bottom some height remains and scroll stops before the bottom. Help will be appreciated. Thanks.

Here is my website url. https://solusent.com/

**Comment by clementroche** [comment]
Remove the height you used on html and body, it's falsing the dimensions

**Comment by EmpChirag** [comment]
hi @clementroche , thanks for the quick response. I have added that height for testing only even without it, still same issue is there. please check I have removed the height now.

**Comment by clementroche** [comment]
your body is still height:100vh, this is wrong

**Comment by EmpChirag** [comment]
@clementroche thanks, It is working proper now.
