### ISSUE TITLE
ReferenceError when trying to use Lenis via script tag

### ISSUE THREAD

**Issue by elsonigo** [darkroomengineering/lenis#31]
I'm trying to use Lenis via the script tag, but can't get it to work.
Initialising it with "Lenis" returns this error: ```Uncaught ReferenceError: Lenis is not defined```.

[codepen](https://codepen.io/sonigo/pen/rNvJVbB)

**Comment by arzafran** [comment]
Hello @jonasmanser, seems like we were bundling Lenis with quotes in our `microbundle` command. it is now fixed in [0.2.7](https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.7/bundled/lenis.js) 

Thanks for the heads up!
