### ISSUE TITLE
Help, regarding custom wrapper and content, unable to scroll

### ISSUE THREAD

**Issue by hengshanMWC** [darkroomengineering/lenis#312]
**Describe the bug**
There is a scroll bar in the modal box, which prevents me from scrolling. I want to modify the wrapper and content

**To Reproduce**
https://codepen.io/abmao/pen/gOyPXwm

**Comment by clementroche** [comment]
Lenis is meant to smooth any element that is already scrollable. In your codepen, `#wrapper` is not srollable, you must do it using CSS first otherwise Lenis does nothing.

```
#wrapper {
  height: 100vh;
  overflow: auto;
}
```

**Comment by hengshanMWC** [comment]
> Lenis is meant to smooth any element that is already scrollable. In your codepen, `#wrapper` is not srollable, you must do it using CSS first otherwise Lenis does nothing.
> 
> ```
> #wrapper {
>   height: 100vh;
>   overflow: auto;
> }
> ```

Thank you.
