### ISSUE TITLE
May I ask if it is possible to add an event for scrollEnd in the future?

### ISSUE THREAD

**Issue by hengshanMWC** [darkroomengineering/lenis#313]
**Describe the bug**
May I ask if it is possible to add an event for scrollEnd in the future? I am currently using setTimeout to make an inaccurate judgment
<img width="460" alt="image" src="https://github.com/darkroomengineering/lenis/assets/45714422/48ef3803-f504-4cfa-9083-75505298d970">

**Comment by clementroche** [comment]
When should it be dispatched ? Can you show an example where it's useful ?

You alread have acess to `onComplete` callback

```
lenis.scrollTo(target, { onComplete: () => {
  console.log('scrollTo completed')
}})
```

**Comment by hengshanMWC** [comment]
> When should it be dispatched ? Can you show an example where it's useful ?
> 
> You alread have acess to `onComplete` callback
> 
> ```
> lenis.scrollTo(target, { onComplete: () => {
>   console.log('scrollTo completed')
> }})
> ```

Background: There is an object that triggers animation when the mouse moves in or scrolls. I hope the scrolling animation has a higher priority than the mouse animation, and to abort the mouse animation during scrolling

**Comment by clementroche** [comment]
i don't understand your issue, can you provide a reproduction link ?

**Comment by hengshanMWC** [comment]
> i don't understand your issue, can you provide a reproduction link ?

Hello, I solved whether it was scrolling by checking the lenis.velocity
