### ISSUE TITLE
[Typescript] useLenis should not require any argument

### ISSUE THREAD

**Issue by cdslxc** [darkroomengineering/lenis#314]
![CleanShot 2024-03-11 at 14 10 29@2x](https://github.com/darkroomengineering/lenis/assets/8092790/5c0108d0-49b7-444f-8f43-fa83835cf2fd)

The first argument is the callback for effect of lenis instance. It shouldn't be required.

**Comment by clementroche** [comment]
nice catch

**Comment by clementroche** [comment]
this should be fixed in v0.0.46
