### ISSUE TITLE
Not able to scroll till the bottom of the webpage in the first load

### ISSUE THREAD

**Issue by dv64bit** [darkroomengineering/lenis#317]
**Describe the bug**
I implemented the Lenis smooth scroll in my webflow website but I am not able to scroll till the bottom of my webpage
website link: https://www.coolant.co/

**Comment by clementroche** [comment]
You have to include CSS 
https://github.com/darkroomengineering/lenis?tab=readme-ov-file#recommended-css

**Comment by dv64bit** [comment]
> You have to include CSS 
> https://github.com/darkroomengineering/lenis?tab=readme-ov-file#recommended-css

Thanks buddy got it.
