### ISSUE TITLE
Demo site is not loading

### ISSUE THREAD

**Issue by gregdeane** [darkroomengineering/lenis#32]
At the time of this issue being opened, the demo site won't load.

- Google Chrome v105.0.5195.125 (also tried incognito)
- MacOS 12.6

![Screenshot 2022-09-28 at 15 36 10](https://user-images.githubusercontent.com/4949000/192793251-e59056f9-1f0f-4238-a4eb-d4b75e6e695a.png)

**Comment by arzafran** [comment]
Thanks for the headsup! seems like something went wrong when linking our Chrome Extension, it should be fixed in a few minutes.
