### ISSUE TITLE
"Module parse failed: Unexpected token" when using Lenis-React

### ISSUE THREAD

**Issue by pascal-adk** [darkroomengineering/lenis#325]
**Describe the bug**
I get this error when using anything from lenis react:
Module parse failed: Unexpected token (3:5)
| import Lenis, { LenisOptions } from '@studio-freight/lenis';
| import React, { ForwardRefExoticComponent, PropsWithoutRef, ReactNode, RefAttributes } from 'react';
> type LenisEventHandler = (lenis: Lenis) => void;
| interface LenisContextValue {
|     lenis: Lenis;

Import trace for requested module:
./node_modules/@studio-freight/react-lenis/dist/types/index.d.ts
./src/components/containers/drawer.tsx
./src/app/(index)/(sections)/(topics)/section.tsx

Although, looking at the file, everything seems correct.
![Bildschirmfoto 2024-04-13 um 19 23 02](https://github.com/darkroomengineering/lenis/assets/80278171/bddb8147-837b-40f7-850f-75920bebdf8c)

**Reproduce Repo**
https://github.com/PixelPage-YT/lenis-error

**Comment by pascal-adk** [comment]
Oops, i figured out my import was messed up. 

The weird thing is now it works in my initial environment but not the one i used to reproduce. There, i get this error now: Error: (0 , react__WEBPACK_IMPORTED_MODULE_1__.createContext) is not a function

**Comment by clementroche** [comment]
it works everywhere else 🤷‍♂️

**Comment by pascal-adk** [comment]
Yes since it even works in my project we can close this ig
thank you

**Comment by clementroche** [comment]
you need 'use client' on top of the file @PixelPage-YT
