### ISSUE TITLE
Scrolling with middle mouse button

### ISSUE THREAD

**Issue by ExileofAranei** [darkroomengineering/lenis#338]
**Describe the bug**
Greetings, awesome plugin!
Found an issue with middle mouse button.
Attempting to scroll by pressing middle mouse button while page is still being scrolled by last mouse wheel causes unexpected behavior. When page is scrolled only by middle mouse from start, it works as expected

Chrome 125.0.6422.76, Edge 125.0.2535.51
Firefox 126.0 (same issue, but don't flicker that much, only waits until animation is complete)

https://github.com/darkroomengineering/lenis/assets/41694699/633a3801-6d35-4463-9ee4-93190796e208

**Comment by clementroche** [comment]
Check [v1.1.4](https://github.com/darkroomengineering/lenis/releases/tag/v1.1.4)

**Comment by ExileofAranei** [comment]
> Check [v1.1.4](https://github.com/darkroomengineering/lenis/releases/tag/v1.1.4)

Works fine! Thanks
