### ISSUE TITLE
Feature request: Custom Scrollbar

### ISSUE THREAD

**Issue by reksaandhika** [darkroomengineering/lenis#34]
Hi Studio Freight team,
Nice library, very useful, and game changer for smooth scrolling, thank you to make this beautiful library.
I wonder if we can have a custom scrollbar (because Windows have suck scroll style and ruined the website UI).

What I mean by custom scrollbar is adding new div instead styling -webkit scroll on CSS (because it has limited styling, and depends on browser).
I understand we can make our own by using `lenis.on('scroll')` function, but it would be great if we have option like example `customScroll: true`, and automatically create custom div for scrollbar.

Like example Studio Freight projects:
- [https://lunchbox.io/](https://lunchbox.io/)
- [https://www.getrepeat.io/](https://www.getrepeat.io/)

Thank you.

**Comment by clementroche** [comment]
Hi @reksaandhika, currenlty you have to do it by yourself as you mentionned. Mostly because we don't want to supercharge the lib with it. The ideal solution would be to create a new package in my opinion, we surely gonna make it one day. By the way the scrollbar we used is [open source](https://github.com/studio-freight/satus/tree/main/components/scrollbar).

**Comment by reksaandhika** [comment]
Hi @clementroche, I see your vision to keep the lib as light as possible, I don't think adding custom scrollbar gonna significantly increase lib size, or even it is, i don't think won't be deal breaker because of it. But I feel happy knowing that you will add it one day. Thank you for the scrollbar source code link, will try to learn from that.

**Comment by Mulegoat** [comment]
Hi @clementroche, do you have any repo of the cusstom scrollbar in vanilla js rather than react? Absolutely loving this library and am porting all sites that use locomotive to Lenis! Thanks again

**Comment by arzafran** [comment]
> Hi @clementroche, I see your vision to keep the lib as light as possible, I don't think adding custom scrollbar gonna significantly increase lib size, or even it is, i don't think won't be deal breaker because of it. But I feel happy knowing that you will add it one day. Thank you for the scrollbar source code link, will try to learn from that.

Thanks for bringing this up @reksaandhika, we're thinking about adding an opt-in alternative to enable it, but we want strongly believe that Lenis should only be focused on scrolling, which is not a simple task by itself already.



> Hi @clementroche, do you have any repo of the cusstom scrollbar in vanilla js rather than react? Absolutely loving this library and am porting all sites that use locomotive to Lenis! Thanks again

hey @Mulegoat, Here's a quick [Codesandbox](https://codesandbox.io/s/vanilla-custom-scrollbar-ecbfey) lacks drag functionality but could easily be added.

**Comment by Mulegoat** [comment]
Thank you, @arzafran! This is great

**Comment by arzafran** [comment]
Closing this for now since there are already solutions provided.

**Comment by about-daniel** [comment]
> Thank you, @arzafran! This is great

@Mulegoat @arzafran anyone has an example with the drag functionality?

**Comment by JetLewis** [comment]
> > Thank you, @arzafran! This is great
> 
> @Mulegoat @arzafran anyone has an example with the drag functionality?

Hey @about-daniel, [here is a small pen](https://codepen.io/JetLewis/pen/mdovMpZ) I made with the drag functionnality.

**Comment by about-daniel** [comment]
> > > Thank you, @arzafran! This is great
> > 
> > 
> > @Mulegoat @arzafran anyone has an example with the drag functionality?
> 
> Hey @about-daniel, [here is a small pen](https://codepen.io/JetLewis/pen/mdovMpZ) I made with the drag functionnality.

Awesome! thanks @JetLewis
