### ISSUE TITLE
Bundle recommended styles

### ISSUE THREAD

**Issue by xavierfoucrier** [darkroomengineering/lenis#344]
Same as many other libraries (*), it would be nice to **bundle the [recommended styles](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#recommended-css) inside the package** `dist` folder.

This way we can safely use them like `@use 'lenis/dist/styles.scss';` for example.
With this kind of import, you can adjust recommended styles  when a new package version is released.

> (*) I know that `lenis` is not like no other libraries 🤘🕶️

**Comment by feledori** [comment]
it so little css, I think its not worth adding it to the bundle. like this everyone can add what they want and wherever they want. just copy and paste.

**Comment by clementroche** [comment]
Let's see what we can do.

**Comment by clementroche** [comment]
yo @xavierfoucrier i've just bundled the css sheet, can you take a look ?

https://unpkg.com/browse/lenis@1.1.9/dist/lenis.css

**Comment by xavierfoucrier** [comment]
Hello @clementroche 👋 

I just tested and it's all fine! 👍 
Thanks a lot ☀️ 🪴 😊
