### ISSUE TITLE
Define wrapper and content，Unable to scroll

### ISSUE THREAD

**Issue by hengshanMWC** [darkroomengineering/lenis#346]
**Describe the bug**
hello, Define wrapper and content，Unable to scroll

**To Reproduce**
[codepen](https://codepen.io/hengshanMWC/pen/oNRBpRo).

**Comment by feledori** [comment]
the wrapper has the same height as the content so their is nothing to scroll for lenis.

**Comment by clementroche** [comment]
https://codepen.io/ClementRoche/pen/xxNgWXe
