### ISSUE TITLE
Vercel preview toolbar unusable in projects using lenis

### ISSUE THREAD

**Issue by iamlinkus** [darkroomengineering/lenis#347]
**Describe the bug**
In projects where Lenis is used for the whole document, using the Vercel toolbar is not possible, since Lenis blocks the scrollable areas of the toolbar (comments list, etc.). 

**To Reproduce**
Try using Vercel toolbar in any Lenis project, where lenis is initialized on the document, rather than a predefined wrapper. Open comments, add enough comments that you'd need to scroll down in the toolbar to see them all - scrolling doesn't work.

**Workaround with flaws**
If you use a wrapper, instead of initializing on the whole document, the toolbar works. But the downside to using wrappers is that when developing your project using HMR, it force-resets the scroll, since the wrapper must be fixed with the height of the browser.

-----

I tried implementing my own hook that observes the dom and if it finds vercel toolbar it forces lenis to ignore it and pass through the events to the toolbar areas that are scrollable, but since the toolbar is injected as shadow dom - you're not actually able to select the elements within it.

If not fixed, I think there should be a disclaimer in the readme, that using Lenis when initializing on the document (and not a wrapper), renders the super useful Vercel preview toolbar useless. And with the upcoming new features for the toolbar, which will make it almost mandatory to use on client projects, I think this might be a big problem when deciding on whether to use Lenis for a project or not.

**Comment by mickaelchanrion** [comment]
Hello @iamlinkus 
This is one of the trade-offs of using Lenis. This is mentioned in the documentation [here](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#nested-scroll): nested scroll elements should have the data-attribute `data-lenis-prevent` to indicate Lenis it should stop interfering. Note that you can add/remove this attribute programatically after Lenis was instanciated without any problem.

That being said, you could also end up in some cases where you don't have the control over a scrollable element. Like an element created some time in the life of the page by a third party script and no events or hooks are available for you to add this attribute. This is exactly what happened to me in the issue #334.

A new option `prevent` was added in v1.1.1 ([see](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings)).

example:
Let's assume the vercel toolbar has the class `.vercel-toolbar`. You can do:
```ts
new Lenis({
  prevent: (element) => {
    return element.nodeName === "VERCEL-LIVE-FEEDBACK"
  }
})
```
The scroll will be back to normal inside this element.

**Comment by clementroche** [comment]
thank you @mickaelchanrion for your answer, `prevent` is the way to go in this situation. I've just edited your reply with the according condition `element.nodeName === "VERCEL-LIVE-FEEDBACK"`. 

Can you try the provided solution @iamlinkus  ?

**Comment by iamlinkus** [comment]
It works! Awesome! Thanks!

**Comment by martinrosbier** [comment]
Thank you very much @mickaelchanrion! Your insight was really helpful.

When using the Lenis JavaScript library for smooth scrolling, you might encounter a scenario where certain elements on your page—like modals, nested scrollable divs, or specific content sections—should not be affected by Lenis's smooth scrolling behavior. Instead, these elements should retain the default browser scrolling to ensure proper functionality.

As its explaind in the link shared by Mickael to exclude these elements from Lenis's smooth scrolling, you can add the data-lenis-prevent attribute to them. However, a common issue arises when this attribute is not added before Lenis initializes. If the attribute is added after Lenis has started, Lenis won't recognize it, and the elements will still be affected by smooth scrolling.

> Hello @iamlinkus This is one of the trade-offs of using Lenis. This is mentioned in the documentation [here](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#nested-scroll): nested scroll elements should have the data-attribute `data-lenis-prevent` to indicate Lenis it should stop interfering. Note that you can add/remove this attribute programatically after Lenis was instanciated without any problem.
> 
> That being said, you could also end up in some cases where you don't have the control over a scrollable element. Like an element created some time in the life of the page by a third party script and no events or hooks are available for you to add this attribute. This is exactly what happened to me in the issue #334.
> 
> A new option `prevent` was added in v1.1.1 ([see](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings)).
> 
> example: Let's assume the vercel toolbar has the class `.vercel-toolbar`. You can do:
> 
> ```ts
> new Lenis({
>   prevent: (element) => {
>     return element.nodeName === "VERCEL-LIVE-FEEDBACK"
>   }
> })
> ```
> 
> The scroll will be back to normal inside this element.

**Comment by zulianAdryan** [comment]
> Thank you very much @mickaelchanrion! Your insight was really helpful.
> 
> When using the Lenis JavaScript library for smooth scrolling, you might encounter a scenario where certain elements on your page—like modals, nested scrollable divs, or specific content sections—should not be affected by Lenis's smooth scrolling behavior. Instead, these elements should retain the default browser scrolling to ensure proper functionality.
> 
> As its explaind in the link shared by Mickael to exclude these elements from Lenis's smooth scrolling, you can add the data-lenis-prevent attribute to them. However, a common issue arises when this attribute is not added before Lenis initializes. If the attribute is added after Lenis has started, Lenis won't recognize it, and the elements will still be affected by smooth scrolling.
> 


So it mean we can't have the smooth scroll behaviour on our modal or the other scrollable element except the root element? because I'm trying to have the smooth scroll on a modal and can't find any documentation to do that

**Comment by mickaelchanrion** [comment]
> If the attribute is added after Lenis has started, Lenis won't recognize it, and the elements will still be affected by smooth scrolling.

@martinrosbier I'm not sure that's correct. As per my understanding, on each scroll event from the virtual scroll, Lenis will traverse the DOM and check the presence of the attribute to prevent itself. See [here](https://github.com/darkroomengineering/lenis/blob/main/packages/core/src/lenis.ts#L313).

@zulianAdryan I'd recommend you to open a new issue or discussion about this different subject because this issue is already closed and not completely related. You'll get more attention that way.

What you are asking for is essentially how to get nested Lenis instances. To do so, you need to instantiate another Lenis on your modal / scrollable element with the correct settings ([see `wrapper` and `content`](https://github.com/darkroomengineering/lenis?tab=readme-ov-file#instance-settings)).

IMO, there's not much benefit on having a smooth scroll inside a modal so the extra work is not worth it. `data-lenis-prevent` on you scrollable element is much simpler and it just works 👌
