### ISSUE TITLE
'userData' Doesn't Get Emitted If 'scrollTo' Is Called With 'immediate'

### ISSUE THREAD

**Issue by PauloMFJ** [darkroomengineering/lenis#349]
**The Bug**
As per title - 'userData' doesn't get emitted if 'scrollTo' is called with 'immediate'. Lenis version: `1.1.2`.

**To Reproduce**
The issue can be replicated here: https://codepen.io/paulomfj/pen/vYwZVeJ

**Comment by clementroche** [comment]
hey @PauloMFJ, it should be fixed in [v1.1.3-dev.0](https://www.npmjs.com/package/lenis/v/1.1.3-dev.0)
