### ISSUE TITLE
Horizontal scrolling in mobile view.

### ISSUE THREAD

**Issue by AasimFarooqi** [darkroomengineering/lenis#355]
So, I have implemented lenis in my web app. The issue is I have a gallery with `display: flex;` which overflows to right, due to this when I change to mobile view first the resize is not correct. And the page is horizontally scrollable, if I add `overflow: hidden;` the issue of resize is corrected but now the touch scroll stops. I would appreciate help on this.

**Comment by clementroche** [comment]
Can you provide a reproduction link ?

**Comment by AasimFarooqi** [comment]
The issue is solved, I had to use wrapper property on the actual scrollable content not the html.
