### ISSUE TITLE
Lenis is not working with handlebars & vite

### ISSUE THREAD

**Issue by alprnrtrk** [darkroomengineering/lenis#359]
I don't have a clear understanding of this bug, but I'm trying to use Lenis in the Vite project, which is also using handlebars.
I don't have any errors or warnings, but Lenis is properly set up, and class management is also working properly. 

but somehow the scroll is not working at all. 
I used the basic Lenis layout, as shown in the usage section.
I am not using GSP or any other scroll-related libraries. 

I don't even know how to properly approach this bug.

Thank you for your time  🙏🏻.

**Comment by arzafran** [comment]
can you please share a codesandbox with a minimal environment to replicate the issue?

**Comment by clementroche** [comment]
Closing this until we get a minimal reproduction link.
