### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by rollakal** [darkroomengineering/lenis#36]
Hi Lenis team, 
I'm not able to make horizontal scroll work. Is there something to keep in mind when implementing horizontal scroll?
I have a basic setup with a flex horizontal layout. If it's needed I can provide a codepen.

**Comment by clementroche** [comment]
Can you provide a codepen please ?

**Comment by rollakal** [comment]
sure, here you go.

https://codepen.io/rolla/pen/bGMKPEq

**Comment by clementroche** [comment]
Your content node (body by default) should always match the size of its content.

I'm not sure it's the perfect solution but adding this works:
```css
body {
  width: fit-content;
}
```

**Comment by rollakal** [comment]
Thanks for helping me.

**Comment by SylvainFaure** [comment]
> Your content node (body by default) should always match the size of its content.
> 
> I'm not sure it's the perfect solution but adding this works:
> 
> ```css
> body {
>   width: fit-content;
> }
> ```

Hi @clementroche !
I had the same problem and your solution works. Maybe this should be added to the doc as for the moment it is specified to make the body with width at 100%?
Thank you!
