### ISSUE TITLE
Scroll position jumps when dragging scrollbar after wheel

### ISSUE THREAD

**Issue by Hiei16** [darkroomengineering/lenis#365]
The bug is totally described [here (previous issue topic)](https://github.com/darkroomengineering/lenis/issues/168), it has been resolved 1 year ago but seems to be back with version 1.0.42. The [demo website](https://lenis.darkroom.engineering/) has the bug too.

**Comment by clementroche** [comment]
Last version of lenis is v1.1.6, i can't reproduce on the demo website
https://www.npmjs.com/package/lenis

**Comment by Hiei16** [comment]
Ok, I updated my version and i still got the bug, for the demo website i go unitl this section, scroll and immediatly grab the bar and scroll: 
![image](https://github.com/darkroomengineering/lenis/assets/12182888/5d29d2df-e1c5-4188-8682-3e4e8cf588b1)

EDIT: this is too fast for my recorder so i can"t show on video
It may be more visible when you do it in transition from the previous screen to this one:
![image](https://github.com/darkroomengineering/lenis/assets/12182888/e4273322-4246-492c-89ce-eef28c6f65c9)

**Comment by Hiei16** [comment]
I succeeded to catch it on video:
https://github.com/darkroomengineering/lenis/assets/12182888/c98ee8eb-2ddc-44b1-9c07-d63a42517240

**Comment by clementroche** [comment]
That is not the same issue actually. The one you caught is related to this and it's not fixable. https://github.com/darkroomengineering/lenis/issues/107

**Comment by Hiei16** [comment]
The native bar is not blocked/prevented in my case, it would solve my problem if it was the case :(
But the ticket can be closed if this is not fixable.

**Comment by clementroche** [comment]
I leave the original one open
