### ISSUE TITLE
isScrolling

### ISSUE THREAD

**Issue by csskiller** [darkroomengineering/lenis#368]
When lenis is running without smooth scroll, the isScrolling variable doesnt work :(

**Comment by clementroche** [comment]
Do you mean that `isScrolling` class is not assigned or that `lenis.isScrolling` remains `false` ?

**Comment by csskiller** [comment]
Yeah :) with smooth scroll, you get when is scrolling and when is paused, but without smooth scroll it doesnt work

**Comment by clementroche** [comment]
Which version of lenis are you using ?

**Comment by csskiller** [comment]
Really old version, i updated it and now working! Thanks and sorry!
