### ISSUE TITLE
Infinite scroll jumps on last item

### ISSUE THREAD

**Issue by eqtrd** [darkroomengineering/lenis#370]
**Describe the bug**
Infinite scroll option makes scroll jumps when reaching end of original content.

https://github.com/user-attachments/assets/38c93d15-52c9-46c0-83b5-d55c268e2e77

I've checked this #295 butI can't get it to work either

**To Reproduce**
Try to set .grid {display: block;} to get fullwidth items
https://codepen.io/uzitrake/pen/mdoaaRZ

Thank you for your help

**Comment by clementroche** [comment]
First of all, please use the latest lenis version ([v1.1.8](https://www.npmjs.com/package/lenis))

**Comment by clementroche** [comment]
How confortable are you with CSS ? Did you make this example by yourself ?

This is not a Lenis issue but a wrong implementation on your side, follow this [example](https://codepen.io/ClementRoche/pen/OJqBLod) to have it working.
