### ISSUE TITLE
Mouse wheel quick scroll during webpage refresh causes delayed auto-scroll to top

### ISSUE THREAD

**Issue by re-xmyl** [darkroomengineering/lenis#372]
Typically, when the vertical scroll wheel of a webpage is positioned in the middle, the scroll wheel retains this position upon refreshing the webpage. Post the implementation of Lenis, allowing for a brief pause before attempting to scroll the wheel after a webpage refresh yields a seamless experience. However, when refreshing the webpage at a rapid pace, the scroll wheel exhibits an erratic, jerky movement, automatically scrolling to the top.

**Comment by feledori** [comment]
Can you provide a minimal reproduction.

**Comment by re-xmyl** [comment]
I have encountered an issue while utilizing Lenis within a Vue project.  In [CodePen Link](https://codepen.io/ClementRoche/pen/VwxgZEP) , everything seemed to be functioning as expected.
Here is  a minimal reproduction:
<pre>
<script setup>
import Lenis from 'lenis';
const lenis = new Lenis()
function raf(time) {
    lenis.raf(time)
    requestAnimationFrame(raf)
}
requestAnimationFrame(raf)
</script>
</pre>

a template with long text.

<pre>
<style scoped>

</style>
</pre>

**Comment by clementroche** [comment]
If you can't reproduce on codepen it means your implementation is wrong. Anyway Lenis doesn't have any effect over the initial page position.

**Comment by airfortech** [comment]
> If you can't reproduce on codepen it means your implementation is wrong. Anyway Lenis doesn't have any effect over the initial page position.

Issue exists. Problem is codepen or codesandbox doesnt keep scroll last position after refresh page.
In next.js project when scroll is f.e. in the middle after refresh page, scroll still is in the middle and then issue occurs. 
But it seems like adding "use client" to page.tsx in next.js resolves issue.
