### ISSUE TITLE
Next.js and Lenis are not scrolling to the top of the page when I navigate to a new one

### ISSUE THREAD

**Issue by Liam-hi** [darkroomengineering/lenis#375]
**Describe the bug**

When the lenis-scrolling lenis-smooth classes are active and I click on a link, the new page does not start at the top, creating a bad user experience. When these classes are removed from the HTML element, the navigation works as expected

Secondly, googling this, this seems a very common problem. 

**To Reproduce**

I used Stackblitz to create a minimal demo. I haven't added unnecessary CSS or other elements that might interfere.

To recreate the problem, click on a link quickly while the lenis-scrolling lenis-smooth class is active.

But will a user click on a link this fast in a real project? From a user experience perspective, yes. Imagine a user clicking on an image while scrolling. This creates a bad experience for the user.

[Minimal demo](https://stackblitz.com/edit/stackblitz-starters-qbbkmh?file=app%2Fpage.tsx)

**Comment by clementroche** [comment]
That's because your lenis instance is shared between pages since it's created between in `layout.js`, two solutions:
- use your `<SmoothScroll>` component into template.js or page.js so it's recreated on every page change, the [Satūs](https://github.com/darkroomengineering/satus/blob/main/app/(pages)/(components)/wrapper/index.js) way. Don't forget to destroy it.
- reset lenis `lenis.scrollTo(0, {immediate: true, force: true})` on every [pathname](https://nextjs.org/docs/app/api-reference/functions/use-pathname) change. Example: https://stackblitz.com/edit/stackblitz-starters-v1hzro?file=components%2FSmoothScroll.js

**Comment by QingjiaTsang** [comment]
> That's because your lenis instance is shared between pages since it's created between in `layout.js`, two solutions:这是因为您的lenis实例在页面之间共享，因为它是在`layout.js中`创建的，两个解决方案：
> 
> * use your `<SmoothScroll>` component into template.js or page.js so it's recreated on every page change, the [Satūs](https://github.com/darkroomengineering/satus/blob/main/app/(pages)/(components)/wrapper/index.js) way. Don't forget to destroy it.在template.js或page.js中使用`<SmoothScroll>`组件，以便在每次页面更改时重新创建它，这是[Satellite的](https://github.com/darkroomengineering/satus/blob/main/app/(pages)/(components)/wrapper/index.js)方式。别忘了销毁它。
> * reset lenis `lenis.scrollTo(0, {immediate: true, force: true})` on every [pathname](https://nextjs.org/docs/app/api-reference/functions/use-pathname) change. Example: https://stackblitz.com/edit/stackblitz-starters-v1hzro?file=components%2FSmoothScroll.js在每次[路径名](https://nextjs.org/docs/app/api-reference/functions/use-pathname)更改时重置lenis `lenis.scrollTo(0, {immediate: true, force: true})` 。示例：[https://stackblitz.com/edit/stackblitz-starters-v1hzro? file=components%2FSmoothScroll.js](https://stackblitz.com/edit/stackblitz-starters-v1hzro?file=components%2FSmoothScroll.js)

It still has this problem when you use vite, react18 and tanstack router.

**Comment by QingjiaTsang** [comment]
> That's because your lenis instance is shared between pages since it's created between in `layout.js`, two solutions:
> 
> * use your `<SmoothScroll>` component into template.js or page.js so it's recreated on every page change, the [Satūs](https://github.com/darkroomengineering/satus/blob/main/app/(pages)/(components)/wrapper/index.js) way. Don't forget to destroy it.
> * reset lenis `lenis.scrollTo(0, {immediate: true, force: true})` on every [pathname](https://nextjs.org/docs/app/api-reference/functions/use-pathname) change. Example: https://stackblitz.com/edit/stackblitz-starters-v1hzro?file=components%2FSmoothScroll.js

It still has this problem when you use vite, react18 and tanstack router.

**Comment by sameerxanand** [comment]
I don't think this is a good solution. When you navigate back, it'll scroll you to the top rather than your original position.
