### ISSUE TITLE
ScrollTo not triggering when screen height is below 100vh

### ISSUE THREAD

**Issue by GustavoGomez092** [darkroomengineering/lenis#378]
**Describe the bug**
Whenever using the lenis.scrollTo() method, if the screen height is less than 100vh, the event seems to not get triggered, so callbacks like: onStart or onComplete never get triggered. I would expect the method to execute the callbacks accordingly.

**To Reproduce**
https://codepen.io/gustavogomez092/pen/oNrpMLo?editors=1111

**Comment by feledori** [comment]
Why should it trigger the callbacks lenis never scrolled anywhere? "scrollTo" never "scrolled to" anything because there is nothing to scroll so I wouldn't expect it to call anything.

**Comment by clementroche** [comment]
Not sure about what I expect here but I pushed the fix anyway lol. [v1.1.11](https://github.com/darkroomengineering/lenis/releases/tag/v1.1.11)

**Comment by GustavoGomez092** [comment]
That is amazing! I specifically stumbled upon the scenario where I needed these events while the router changed views to finish a page transition animation, but since this event got triggered right at the moment the page does not have any content on it, then it wasn't triggered, I understand @feledori point of view and it is certainly valid, but I'm glad you took this into consideration @clementroche
