### ISSUE TITLE
Scroll is not smooth while using a large iframe

### ISSUE THREAD

**Issue by elisabetperez** [darkroomengineering/lenis#38]
Hello,
I'm having trouble with one of my pages consisting of a 400px hero section, an iframe of this magnitude: height: 1547px; width: 1432px; and then my footer, while using Lenis. The height and width of the iframe are loaded right before Lenis is initialized. What is it I might be doing wrong?
Thanks in advance.

**Comment by clementroche** [comment]
Hi, can you provide a codepen ?

**Comment by elisabetperez** [comment]
yes, here it is [https://codepen.io/elisabetperez/pen/QWrJeLK](https://codepen.io/elisabetperez/pen/QWrJeLK)
as you can see, the first scroll gets stuck in the middle of the iframe and it's not smooth - this only happens sometimes but I wonder why

**Comment by clementroche** [comment]
Unfortunatelly there is no easy fix since iframe elements don't forward wheel events. You can look for potential solution in [this thread](https://github.com/locomotivemtl/locomotive-scroll/issues/205) from Locomotive-scroll.

**Comment by arzafran** [comment]
> 

the reason why it happens 'sometimes' is because the original scroll has a bit of momentum, so when you scroll outside of the iframe it's smooth, inside it's not. there's no real way to fix this without breaking interactivity within the iframe. i'll close it for now.
