### ISSUE TITLE
`lerp` seems to have no effect

### ISSUE THREAD

**Issue by CNSeniorious000** [darkroomengineering/lenis#380]
**Describe the bug**
```js
const lenis = new Lenis({ lerp: 0.9 })
```

But the animation is still slow as before.

**To Reproduce**
~~[codepen](https://codepen.io/CNSeniorious000/pen/RwzJVOW)~~

**Comment by clementroche** [comment]
The closer you get to `1` the choppier the animation will be. It's working properly on my side.

**Comment by CNSeniorious000** [comment]
Sorry! It seems I made some mistake. If I still find this a bug, I will reopen this.

**Comment by CNSeniorious000** [comment]
Really weird. I can't reproduce this in your codepen template, but I can reproduce it in my astro site. Even if the code is the same:

```ts
import Lenis from 'lenis'

const lenis = new Lenis({ lerp: 0.9 })

function raf(time: number) {
  lenis.raf(time)
  requestAnimationFrame(raf)
}

requestAnimationFrame(raf)
```

May I create a heavier reproduction with stackblitz and reopen this?

---

Plus, I found that it works well in `<=1.1.9` but fail since `1.1.10`. Are there some implementation details changed between that?

**Comment by feledori** [comment]
@CNSeniorious000 are you making sure astro is loading your js and not just rendering stuff static? Haven't used astro in a while but I think there are these client:load attributes which need to be set.

**Comment by CNSeniorious000** [comment]
Only foreign components like React/Vue/Svelte... needs `client:load` stuff. In `.astro` components, `<script>` are just static HTML tags that will be bundled as-is.

**Comment by CNSeniorious000** [comment]
[![](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/withastro-astro-jh7fdu?file=src%2Fpages%2Findex.astro)

Some hints:

- This bug can reproduce since `1.1.10`
- Only `lerp` has problem, I've changed to use `duration` in my own projects

**Comment by clementroche** [comment]
Yo @CNSeniorious000, you're right. The codepen template you used was using an older version of lenis (v1.0.29). Now it can be reproduced, we gonna fix it.

**Comment by clementroche** [comment]
fixed in v1.1.12 @CNSeniorious000

**Comment by CNSeniorious000** [comment]
Thanks!

By the way, the dependency management in the CodePen template can be a bit misleading. I wonder if it would be better to change it to the latest version or remind people to update it in the issue template.

**Comment by clementroche** [comment]
@CNSeniorious000 it's updated in order to always use the latest version of v1
