### ISSUE TITLE
Toggle / Dynamic Infinite Scrolling

### ISSUE THREAD

**Issue by joshua-isaac** [darkroomengineering/lenis#384]
Not necessarily a bug, just curious to know if its possible to enable infinite scrolling based on a toggle of some sort.

I have the following: 

 ```
  const lenis = useLenis(
    ({ options }) => {
      options.infinite = hasReachedBottom ? true : false;
    },
    [hasReachedBottom],
  );
```

However when `hasReachedBottom` gets toggled to true - lenis stops scrolling entirely.

Thanks in advance!

**Comment by clementroche** [comment]
infinite requires some extra computations, you can try to call `lenis.resize()`

**Comment by joshua-isaac** [comment]
Thanks for the response @clementroche! Just tried this with no luck :(

When `hasReachedBottom` gets toggled to true lenis stops. When I add something like the following:

```
  useEffect(() => {
    window.addEventListener("resize", () => {
      lenis?.start();
    });
  }, []);
  ```
  
  I'm able to get lenis to start back up again once i reach the bottom and resize my screen - but this isn't ideal

**Comment by joshua-isaac** [comment]
I was able to get it working using the following:

```

// _app.tsx

  const lenis = useLenis(
    ({ options }) => {
      options.infinite =
        router.asPath === "/" && hasReachedBottom ? true : false;
    },
    [hasReachedBottom],
  );

  useGSAP(() => {
    ScrollTrigger.create({
      trigger: "footer",
      start: "top center",
      end: "bottom center",
      markers: false,
      onEnter: () => setHasReachedBottom(true),
    });
  }, [hasReachedBottom]);

  useEffect(() => {
    if (hasReachedBottom) {
      setTimeout(() => {
        lenis?.resize();
        lenis?.start();
      }, 10);
    }
  }, [hasReachedBottom]);
  ```
  
The setTimeout helped in this case.

  Thanks @clementroche!
