### ISSUE TITLE
Lenis and GSAP

### ISSUE THREAD

**Issue by thesoldiersway** [darkroomengineering/lenis#388]
Hi, I need advide. Lenis working excellent both on my dekstop and mobile. I use it with GSAP. On mobile it is very smooth. The only thing on mobile is that it is to sensitive, one touch scroll and its scrolling too fast and long. I tried to adjust the lerp between 1-2 but that is not helped. Is it any way to control the sensitivity?

**Comment by clementroche** [comment]
Please provide a minimal reproduction link.
