### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by azkalex** [darkroomengineering/lenis#39]
Hello, can't find anywhere more details on these 3 options:

- smoothTouch: false
- touchMultiplier: 2
- inifinite: false

Can you explain them properly with examples? Thank you.

**Comment by arzafran** [comment]
Hi @azkalex!

yes, we need to update the docs, those are fairly recent features we've added.

`smoothTouch`'s intention is to allow devs to enable/disable lerping (or smoothing) the values on touch devices, given that mobile is not the only kind of devices that can have touchscreens we opted for adding this flag, and set it as default, which makes notebooks with touchscreens not smooth, but native scrolling is usually better on those devices.

`touchMultiplier` is a feature that comes directly from [Virtual Scroll](https://github.com/ayamflow/virtual-scroll):

> touchMultiplier: Mutiply the touch action by this modifier to make scroll faster than finger movement. Defaults to 2.

`infinite` allows you to create infinite scrolling pages, you can check how it's implemented [here](https://github.com/studio-freight/lenis/blob/main/src/lenis.js#L82).

I'll add it to the readme

Let me know if you have any other questions.

**Comment by azkalex** [comment]
I'll try to explain this. The scrolling setting on my mouse wheel is 3 lines. Without Lenis, this is the amount it scrolls after the first scroll:

![image](https://user-images.githubusercontent.com/60075863/195736278-4d16fda5-d6d0-44fb-8f19-bc98c79b9069.png)

And this is the distance on the first scroll with Lenis enabled:

![image](https://user-images.githubusercontent.com/60075863/195736357-29eca11f-26f5-470b-a863-572d26cd5fd0.png)

@arzafran Is there any way I can make changes to this? I'd like to keep the smoothness while keeping the distance the same as when it's disabled. It's like without Lenis I scroll 3 lines, and with Lenis, I scroll 6 or something. I hope you get what I mean. Thank you.

**Comment by azkalex** [comment]
@arzafran can you have a look at this? Thank you.

**Comment by clementroche** [comment]
We can add a mouseMultiplier option
