### ISSUE TITLE
Tweaking the behavior of nested scroll

### ISSUE THREAD

**Issue by samyung0** [darkroomengineering/lenis#391]
**Describe the bug**
Currently when we have nested scrolling containers we would smooth scroll them by initializing multiple lenis instances, and it works fine. But let's say when we are scrolling, we finish scrolling one of the nested container, we then need to move the mouse cursor out of the container before we can continue scrolling the rest of the page and this differs from the native scroll. Is there a way we can change this behavior?

**To Reproduce**
[https://codepen.io/not-sam/pen/poMbYwL](https://codepen.io/not-sam/pen/poMbYwL)

**Comment by clementroche** [comment]
yo @samyung0, just shipped "overscroll" option on Lenis on [v1.1.14-dev.1](https://www.npmjs.com/package/lenis/v/1.1.14-dev.1). Can you try it?

```js
  /**
   * Wether or not to enable overscroll on a nested lenis instance, similar to CSS overscroll-behavior (https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior)
   * @default false
   */
  overscroll?: boolean
```

```js
const lenisContainer = new Lenis({
  overscroll: true
})
```

**Comment by samyung0** [comment]
Appreciate the prompt response. I tried it and it works but the overscroll has a delay to it? I am not sure if I messed something up with the css/js config (I am using lenis with gsap according to the instruction in docs)

https://github.com/user-attachments/assets/03cd35ed-f474-4009-91ba-23a4b64c8014

**Comment by clementroche** [comment]
That's the correct behavior., it just waits for the animated scroll to reach the end of the scroll before to allow page scroll

**Comment by samyung0** [comment]
Yep that makes sense. I guess the delay is more noticeable on smooth scroll rather than the normal one. Don't think I can do anything about that tho.

**Comment by clementroche** [comment]
exact @samyung0
