### ISSUE TITLE
Missing whitespace on <html> class

### ISSUE THREAD

**Issue by bomastudioweb** [darkroomengineering/lenis#393]
**Description**

I have a show/hide mechanism based on a class on `<html>` tag.
When I add Lenis to my website, it attachs the classname 'lenis' without leaving a whitespace to the existing class.

EXPECTED BEHAVIOUR `<html class="show--consent lenis">
`

BUGGY BEHAVIOUR `<html class="show--consentlenis">
`

On another website, the issue happens just after the first scroll on the page, i.e.

on document load: `<html class="lenis show--consent">
`

after scroll (BUGGY): `<html class="show--consentlenis">
`

I think the mechanism to add/remove class to the <html> element should be more robust/reliable...

**Example**
See BUG at https://www.bomastudio.it/it/landing/logo.html

**Comment by clementroche** [comment]
Can you please share a codepen with a minimal reproduction of the bug instead of a website, it's almost impossible to debug. How do you add `show--consent` class to html element?

**Comment by bomastudioweb** [comment]
Reproduce here:
https://codepen.io/ficod/pen/Jjgbjda

**Comment by bomastudioweb** [comment]
I will try to make a codepen to reproduce it...

`show-consent` class is added by another plugin:
https://cookieconsent.orestbida.com/

**Comment by bomastudioweb** [comment]
https://codepen.io/ficod/pen/Jjgbjda

Unfortunately I wasn't able to reproduce the bug.
It seems to me that there is something in my peculiar configuration on the site.

It works if I load cookieconsent and lenis separately, seems a minification issue...

**Comment by clementroche** [comment]
Thank you, i'm closing this issue until you can provide a minimal reproduction
