### ISSUE TITLE
Import via CDN

### ISSUE THREAD

**Issue by thagxt** [darkroomengineering/lenis#4]
Can you provide a CDN URL so we can import without having to use npm etc. 

Thank you for your work.

**Comment by MAGGIx1404** [comment]
https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.modern.js

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.umd.js

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.esm.js

**Comment by MAGGIx1404** [comment]
> Can you provide a CDN URL so we can import without having to use npm etc.
> 
> Thank you for your work.

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.esm.js

**Comment by MAGGIx1404** [comment]
> Can you provide a CDN URL so we can import without having to use npm etc.
> 
> Thank you for your work.

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.esm.js

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.modern.js

https://cdn.jsdelivr.net/npm/@studio-freight/lenis@0.1.12/dist/lenis.umd.js

**Comment by arzafran** [comment]
> Can you provide a CDN URL so we can import without having to use npm etc.
> 
> Thank you for your work.

closing this.

thanks @MAGGIx1404!

**Comment by haroldao** [comment]
Nice🍾🍾🤩

**Comment by haroldao** [comment]
![image](https://user-images.githubusercontent.com/36776278/179548985-646e6088-9fc2-4b6c-a968-32fe261e8e48.png)
 I have this error 😭😶...

**Comment by haroldao** [comment]
On my side, these links are not working ...
but I found an alternative solution that is working for me...

```
<script type="module">
      import Lenis from "https://cdn.skypack.dev/@studio-freight/lenis@0.1.12";

      const lenis = new Lenis({
        lerp: 0.1,
        smooth: true,
        direction: 'vertical',
      })

      //get scroll value
      lenis.on('scroll', ({ scroll, limit }) => {
        console.log({ scroll, limit })
      })

      function raf() {
        lenis.raf()
        requestAnimationFrame(raf)
      }

      requestAnimationFrame(raf)
    </script>
```
