### ISSUE TITLE
Lazy loaded images cause scrollTo position not incorrect

### ISSUE THREAD

**Issue by JarvisChao** [darkroomengineering/lenis#402]
**Describe the bug**
When using [vanilla-lazyload](https://github.com/verlok/vanilla-lazyload) and click hash links with scrollTo, during the scrolling process, when the height of the loaded images are different from skeleton, scrollTo does not update the position of the id element, causing the scroll position to be incorrect.

**To Reproduce**

https://github.com/user-attachments/assets/38477545-15ad-492c-8e2e-394276b3e74e

**Comment by clementroche** [comment]
There is not much we can do about it unfortunatelly, your page size is wrong from the beginning. This is why you should assign width and height or aspect-ratio to your images. 

Check this article: https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/
