### ISSUE TITLE
Problem with latest version with Elementor wordpress

### ISSUE THREAD

**Issue by allen1997831** [darkroomengineering/lenis#405]
Hello we been using this amazing smooth scroll for most of our wordpress elementor build website, it's been working great but the latest version of elementor now makes the web is not scrollable, just stuck with it.

you can visualize on [this page]([Here](https://24web38.esedigital-dev.com/yes/)) that has but the following code that always work for us until the latest update of elementor

[Ver](https://24web38.esedigital-dev.com/yes/)

`<style>
html.lenis {
  height: auto;
}

.lenis.lenis-smooth {
  scroll-behavior: auto;
}

.lenis.lenis-smooth [data-lenis-prevent] {
  overscroll-behavior: contain;
}

.lenis.lenis-stopped {
  overflow: hidden;
}

.lenis.lenis-scrolling iframe {
  pointer-events: none;
}
</style>

<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@v0.2.26/bundled/lenis.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    if (!document.querySelector("html").classList.contains('elementor-editor-active')) {
        const lenis = new Lenis({
            duration: 1.5,
            easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
            direction: 'vertical',
            gestureDirection: 'vertical',
            smooth: true,
            smoothTouch: false,
            touchMultiplier: 2,
            infinite: false,        
				});

        function raf(time) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);

        // Target all anchor links on the page
    const anchorLinks = document.querySelectorAll('a[href^="#"]');

        anchorLinks.forEach(link => {
            if (!link.href.includes('#elementor-action')) {
                link.addEventListener('click', function (e) {
                    e.preventDefault();
                    e.stopPropagation();

                    var target = this.getAttribute('href');
                    var targetElement = document.querySelector(target);

                    if (targetElement) {
                        lenis.scrollTo(targetElement, {
                            offset: 0,
                            immediate: false,
                            duration: 1.5, // Increased duration for slower scroll
                            easing: (x) => x < 0.5 ? 2 * x * x : -1 + (4 - 2 * x) * x, // You can adjust this for a different effect
                        });
                    }
                });
            }
        });
    }
});
</script>
`

**Comment by clementroche** [comment]
Please read the documentation, update lenis version and share a minimal reproduction link.

**Comment by allen1997831** [comment]
yes I did update the latest version and how canI share a minimal reproduction link?
you could see it here 
https://24web38.esedigital-dev.com/yes/

**Comment by clementroche** [comment]
Just sharing a website link is not enough it can be literally anything related to your implementation, i need a minimal reproduction link such as codepen or codesandbox.  In addition your website is working correctly

**Comment by allen1997831** [comment]
It's something with wordpress elementor editor problem, it can't just shared on codepen. Correct me if im wrong

**Comment by clementroche** [comment]
Your website is scrolling correctly

**Comment by allen1997831** [comment]
Not on Chrome (annoying browser) but yes it works on Firefox and safari for me

**Comment by clementroche** [comment]
It works on Chrome on my side.

**Comment by clementroche** [comment]
try to remove "scroll-behavior: smooth;" from html element
