### ISSUE TITLE
Incompatible with Next 15 /  React 19

### ISSUE THREAD

**Issue by abel-sch** [darkroomengineering/lenis#407]
I get a dependency conflict whilst adding Lenis to Nextjs 15 but I don't see why Lenis shouldn't be able to work with React 19:

```
npm WARN Found: react@19.0.0-rc-02c0e824-20241028
npm WARN node_modules/react
npm WARN   react@"19.0.0-rc-02c0e824-20241028" from the root project
npm WARN   3 more (next, react-dom, styled-jsx)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional react@">=17.0.0" from lenis@1.1.14
```

**Comment by arzafran** [comment]
it's just a warning, lenis works with react19 but we can't update the dependencies until react v19 is officially released.

**Comment by Marlstergo** [comment]
> it's just a warning, lenis works with react19 but we can't update the dependencies until react v19 is officially released.

Alright great so you recommend installing with the --force flag
