### ISSUE TITLE
Version bump crashed scroll (1.1.15)

### ISSUE THREAD

**Issue by jmisilo** [darkroomengineering/lenis#408]
**Describe the bug**
Version 1.1.15 update crashed scroll on my website.

**To Reproduce**
I am not sure what to do to reproduce that. On my website, I deployed new version, after you released new version. Then issue occured - I was not able to scroll using mouse wheel. I noticed that class lenis-scrolling has been added to html tag, but not removed. I checked my changes, but  after revert the same issue was there. Then I noticed your update, brought it locally and issue was there.

Next.js

**Comment by clementroche** [comment]
Please, can you share a minimal reproduction link?

It's working fine on [this codepen](https://codepen.io/ClementRoche/pen/VwxgZEP)

**Comment by jmisilo** [comment]
@clementroche please check it here https://knmstudio.com/. Then I will bring back 1.1.14

**Comment by clementroche** [comment]
@jmisilo this is not a minimal reproduction link. Can you share a codesandbox? I need to see how you initialize Lenis, are you using `lenis/react` ?



I think i know why, i removed `autoRaf` prop in favor of `options.autoRaf`. That must be a breaking change, let me fix that in v1.1.16

**Comment by jmisilo** [comment]
not really able to do it right now.

yes, I use `lenis/react`

**Comment by clementroche** [comment]
@jmisilo can you try [v1.1.16](https://www.npmjs.com/package/lenis/v/1.1.16)? It should be fixed

**Comment by jmisilo** [comment]
@clementroche yes, it works. thank you very much!
