### ISSUE TITLE
Amount of lines to scroll

### ISSUE THREAD

**Issue by azkalex** [darkroomengineering/lenis#41]
Hello, can you have a look at this?

https://github.com/studio-freight/lenis/issues/39#issuecomment-1278327839

Thank you.

**Comment by clementroche** [comment]
We can add a mouseMultiplier option

**Comment by azkalex** [comment]
That would be great, I saw it on Virtual Scroll and I checked the code to see if it's available on Lenis too.

![image](https://user-images.githubusercontent.com/60075863/196969024-df649730-37de-487b-be64-073b9b0c3319.png)

Any idea when the mouseMultiplier option will be available? Thanks a lot.

**Comment by clementroche** [comment]
published in v0.2.14
