### ISSUE TITLE
can't get lenis to work linearily

### ISSUE THREAD

**Issue by a-dominiak** [darkroomengineering/lenis#411]
Hey, I don't know if it is a bug actually. I just can't get it to work.
I have this folder animation. However as you can see on the bottom when I scroll back and forth lenis creates this "jelly scrolling" effect on folders. When not using lenis the folders stay perfectly still. I tried changing `lerp` value to `0`, `0.5` and `1`, as well as easing function to `t`, `1`, `0.5`, `0` to make it linear, however this jelly scrolling effect persisted. 

https://github.com/user-attachments/assets/390b5d90-96ae-4be7-9ce7-148aa4803ee8

**Comment by clementroche** [comment]
Please share a minimal reproduction link, not the full website.
