### ISSUE TITLE
Improve IDE Autocompletion for Subpath Exports

### ISSUE THREAD

**Issue by no3232** [darkroomengineering/lenis#414]
**Describe the bug**
When using VSCode or other IDEs, autocompletion for subpath imports like `lenis/react` or `lenis/snap` incorrectly suggests paths from the `dist` directory. While the main library's autocompletion works correctly, the subpath exports are not being properly recognized by IDEs.

**Current Behavior**
- Importing from `lenis/react` suggests: `lenis/dist/lenis-react.js`
- Importing from `lenis/snap` suggests: `lenis/dist/lenis-snap.js`

<img width="506" alt="스크린샷 2024-11-25 오후 3 28 58" src="https://github.com/user-attachments/assets/2dc17b5c-1d9e-4f37-8e6a-f1e72f7792e4">
<img width="619" alt="스크린샷 2024-11-25 오후 3 35 46" src="https://github.com/user-attachments/assets/15ba8fee-a763-49e2-9513-1d3b79dc59b8">

The issue stems from the order of exports in package.json. The wildcard pattern `"./dist/*"` is placed before specific subpath exports, causing IDE's module resolution to prioritize dist paths.

**To Reproduce**
Reorder the exports field in package.json to place the wildcard pattern after specific subpath exports:

```json
"exports": {
    ".": {
      "types": "./dist/lenis.d.ts",
      "default": "./dist/lenis.mjs"
    },
    "./react": {
      "types": "./dist/lenis-react.d.ts",
      "default": "./dist/lenis-react.mjs"
    },
    "./snap": {
      "types": "./dist/lenis-snap.d.ts",
      "default": "./dist/lenis-snap.mjs"
    },
    "./vue": {
      "types": "./dist/lenis-vue.d.ts",
      "default": "./dist/lenis-vue.mjs"
    },
    "./dist/*": "./dist/*"
  }
```

<img width="510" alt="스크린샷 2024-11-25 오후 3 28 44" src="https://github.com/user-attachments/assets/8f4e075c-20c7-4a33-a8d0-2a99140053dc">
<img width="619" alt="스크린샷 2024-11-25 오후 3 35 46" src="https://github.com/user-attachments/assets/c5e483b2-fa7e-4b27-aceb-166c32e091ad">

**Addtional Context**

If you don't mind, can I take over this Issue?

**Comment by clementroche** [comment]
Nice catch @no3232, can you do a PR?

**Comment by feledori** [comment]
Thanks for pointing this out. I was wondering why it did this. Didn't know the order in the package.json made a difference. Just pushed the fix to main.
