### ISSUE TITLE
Support for React 19

### ISSUE THREAD

**Issue by moazzam-ali** [darkroomengineering/lenis#416]
Hi,

I am using the latest React 19 release (19.0.0-rc-02c0e824-20241028) along with react-dom in my project. While integrating @studio-freight/react-lenis, I encountered a peer dependency conflict because the package currently specifies:

`ERESOLVE unable to resolve dependency tree
peer react-dom@"^17 || ^18" from @studio-freight/react-lenis
`

Would it be possible to add support for React 19 in the peer dependencies?
Thanks for the amazing library, and I’d be happy to provide more details if needed!

**Comment by clementroche** [comment]
`@studio-freight/react-lenis` has been deprecated, please use [`lenis/react`](https://github.com/darkroomengineering/lenis/blob/main/packages/react/README.md) instead
