### ISSUE TITLE
Ref as content

### ISSUE THREAD

**Issue by opr-inzn** [darkroomengineering/lenis#417]
I'm trying to pass a ref as content in my Lenis options:
```
const ref = useRef<HTMLDivElement>(null)
<Lenis root options={{
            orientation: 'horizontal',
            gestureOrientation: 'both',
            content: ref.current,
        }}
>
   <div ref={ref} className='flex w-max h-full'>
```
which obviously doesnt work since ref.current might be null until it’s loaded. How can I set a specific content container in React/NextJS?

**Comment by clementroche** [comment]
`<Lenis>` component is already creating a content element for you, you can access it from `ref`. I don't see any reason why you would need to define a custom content element.

```js
const contentRef = useRef()

return ( <Lenis ref={(ref)=>{
  contentRef.current = ref?.content
}}>
  // content
</Lenis> )
```

**Comment by opr-inzn** [comment]
Hey @clementroche, thanks for the quick response! I understand. My problem is actually a slightly different one, I just thought it’d be fixed by defining the content.

In my NextJS I have a root layout that uses `<Lenis root>` for smooth vertical scrolling. I then have a subpage, that is meant to be only scrolled horizontally, so I defined another instance of Lenis in said component, again as root, with the options
```
orientation: 'horizontal',
gestureOrientation: 'both',
```
It seems, that the two instances of Lenis interfere with each other and I don’t know how to fix this?

**Comment by clementroche** [comment]
Defining a content element for a root Lenis is useless and will do nothing. Why can't you define a layout that will take care of switching from vertical to horizontal? And then call it within your page? Your Lenis doesn't need to be defined in the root layout.

**Comment by opr-inzn** [comment]
I fixed it by using Lenis on a per-page basis! I supposed lenis/snap doesn’t work with NextJS yet?

**Comment by clementroche** [comment]
It works, you just need to add elements manually by creating a component perhaps
