### ISSUE TITLE
Browser previous and next trackpad gestures don't work in pages using Lenis

### ISSUE THREAD

**Issue by azkalex** [darkroomengineering/lenis#42]
Should it work out of the box or am I using wrong settings? Thank you.

**Comment by azkalex** [comment]
Anyone? Posted this 20 days ago.

**Comment by clementroche** [comment]
Yes that's a drawback of Lenis, we still don't have any solution for that. PR are welcome if you find the way.

**Comment by clementroche** [comment]
Great news ! This sould be fixed in [v0.2.27](https://github.com/studio-freight/lenis/releases/tag/0.2.27). Can you confirm @azkalex ?

**Comment by azkalex** [comment]
Yes, works, this is amazing. Thank you!
