### ISSUE TITLE
Native scrollend event triggered all the time

### ISSUE THREAD

**Issue by titouan-pellerin** [darkroomengineering/lenis#422]
**Describe the bug** 

When setting up Lenis, the native `scrollend` event is triggered consistently right after the `scroll` event. This causes issues for any library relying on this recently introduced event. For instance, [Astro](https://astro.build) `<ClientRouter/>` uses this event to store the scroll position for restoration purposes. For performance reasons, Astro chose this event over a debounced `scroll` event. 
[See the corresponding issue on the Astro repository](https://github.com/withastro/astro/issues/12725). 

**To Reproduce** 

Fork this [example](https://stackblitz.com/edit/vitejs-vite-kuq3zlvy?file=src%2Fmain.js) and look at the console output.

**Comment by titouan-pellerin** [comment]
I believe this is native browser behavior and might not be directly controllable. However, one (slightly hacky) solution could be the following. I haven't tried it, but it might be worth exploring:

### Step 1: Remove the native `scrollend` event

```js
delete window.onscrollend
```

### Step 2: Re-implement it using a `CustomEvent`
```js
const event = new CustomEvent('scrollend', { bubbles: true, cancelable: true });

// Dispatch the event when Lenis detects a `scrollend`
wrapper.dispatchEvent(event);
```

**Comment by clementroche** [comment]
Hello @titouan-pellerin this has been fixed in [v1.1.19-dev.0](https://www.npmjs.com/package/lenis/v/1.1.19-dev.0), can you confirm?

**Comment by titouan-pellerin** [comment]
Hello @clementroche, I just tried it, but it doesn’t seem to have changed anything. Am I missing something?
[Demo here ](https://stackblitz.com/edit/vitejs-vite-kuq3zlvy?file=package.json) (_You can check the logs while scrolling_)

**Comment by clementroche** [comment]
My bad @titouan-pellerin, I added the event on the wrong element, Can you try [v1.1.19-dev.0](https://www.npmjs.com/package/lenis/v/1.1.19-dev.1).

**Comment by titouan-pellerin** [comment]
Hello @clementroche, 

I think you meant 1.1.19-dev.1 (the link is correct, but the label isn’t). The `scrollend` event no longer fires at tick rate, but it’s not firing at all now. This might be a limitation in how Lenis handles it. Since some libraries could rely on this event for performance reasons, it might be worth considering a workaround to ensure it triggers.

For example:
Could you track the last time the `setScroll` method was used? This could make the `e.stopPropagation()` you added conditional, allowing the final scrollend event to be emitted properly.

**Comment by clementroche** [comment]
Totally, I will exclude the very last scroll.

**Comment by clementroche** [comment]
Hey @titouan-pellerin, can you try [v1.1.19-dev.2](https://www.npmjs.com/package/lenis/v/1.1.19-dev.2). I had to use `CustomEvent` since the native event is dispatched before the smooth scroll ends. Also the target is `window` instead of `document`, let me know if that's an issue.

So by default Lenis stops propagation of any `scrollend` event on is wrapper while smooth scrolling. Then it dispatches a `CustomEvent` `scrollend` event once it reaches its target scroll.

**Comment by titouan-pellerin** [comment]
Thanks for your time @clementroche - it looks like you've solved the problem. I could argue about the final `scroll` event being triggered one last time after `scrollend`, but it's not a big issue in my case.

**Comment by clementroche** [comment]
You mean you have both CustomEvent and native event `scrollend` at the end?

**Comment by titouan-pellerin** [comment]
This is what I get when I stop scrolling. First the custom `scrollend` event, then a native `scroll` event

<img width="227" alt="image" src="https://github.com/user-attachments/assets/fb2116ea-a53a-42df-8787-ddd9d7de5695" />

**Comment by clementroche** [comment]
interesting, I faced the same issue but managed to fix it, i wonder why it's still happening

**Comment by clementroche** [comment]
Oh i get it, let me see what i can do about that!

**Comment by clementroche** [comment]
[v1.1.19-dev.3](https://www.npmjs.com/package/lenis/v/1.1.19-dev.3) fixes it

**Comment by titouan-pellerin** [comment]
Sounds like a fix to me. Nice!

**Comment by clementroche** [comment]
Thank you for your feedbacks

**Comment by gauel** [comment]
Hello, I just run into the same issue but solved it by bumping up my `setTimeout` delay for scroll detection from `100ms` to `150ms`

v: [1.1.19-dev.3](https://www.npmjs.com/package/lenis/v/1.1.19-dev.3)

https://github.com/user-attachments/assets/01a15a80-9a1a-47f0-b22a-aa6fe15fd7ad

1. I start scrolling (trackpad) = _scrollstart_ = my highlight hides.
2. I move the mouse = _mousemove_ = my higlight shows.
3. Lenis finishes the scroll = _scrollend_ = nothing changes
4. Scrollstart is called one last time = _scrollstart_ = my higlight hides <- This causes the issue

Setting timeout to `150ms` solved it
<img width="474" alt="Image" src="https://github.com/user-attachments/assets/c0b29090-0df1-43a2-b680-56b2052bc041" />
