### ISSUE TITLE
Implementing lenis with React and GSAP

### ISSUE THREAD

**Issue by xllcs** [darkroomengineering/lenis#424]
Hello,
I'm trying to setup lenis with React through GSAP. I've created a small component in my project that has scrolling in it and I would like to apply lenis onto it using the example in [the docs](https://github.com/darkroomengineering/lenis/blob/main/packages/react/README.md#gsap-integration), but it doesn't seem to do the job, meaning that there is no smooth scrolling. Also tried looking on the internet for a solution but wasn't able to find much. Could anybody please help with this? Thank you!

**Comment by clementroche** [comment]
Can you provide a reproduction link please?

**Comment by xllcs** [comment]
Hello @clementroche,
There you go: https://codesandbox.io/p/sandbox/trusting-elion-hhxycc?file=%2Fsrc%2FApp.js%3A20%2C11

**Comment by clementroche** [comment]
You need to add `game-view-content` class and `orientation: "horizontal"` to `<ReactLenis>` so it allows the horizontal scroll.

Here is the fixed version: https://codesandbox.io/p/sandbox/mystifying-montalcini-qzmfv2?file=%2Fsrc%2FApp.js%3A34%2C16
