### ISSUE TITLE
New site submission

### ISSUE THREAD

**Issue by kekkorider** [darkroomengineering/lenis#43]
I don't know how you keep track of sites that use Lenis, so I'm opening an issue 😄

Here's a brand-new one that I've developed, this time replacing GSAP's ScrollSmoother with Lenis: https://www.heights.agency/
I've added Lenis at an advanced state of the project, and everything went extremely smoothly.

Nice job everyone! 👏

**Comment by clementroche** [comment]
Hey, nice done it's clean ! Glad you like it.
I see you're using v0.2.9, I advice you to update to a more recent version to benefits some bug fixes.

I'm adding it to the showcase.
