### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by gyurmey2** [darkroomengineering/lenis#44]
I noticed an error in the console that does not appear in Chrome v106, but it does appear in Chrome v109, but mostly in Firefox (v 106), Firefox Developer (v107), Firefox Nighly (v 108).

Pen: https://codepen.io/gyurmey2/pen/NWMErqQ

**Comment by clementroche** [comment]
related to #45
