### ISSUE TITLE
Lenis uses `Event.path` which is deprecated

### ISSUE THREAD

**Issue by flayks** [darkroomengineering/lenis#45]
**Describe the bug**
Not necessarily a bug and this is minor but I believe it would be good to use `Event.composedPath()` as `Event.path` is deprecated, as the Issues tab on the Chrome Tools notices so.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/273716/197717349-153eeab3-73a3-4fef-b2ce-5c3270601380.png">

**To Reproduce**
Just use Lenis, Chrome returns this error:
```
Event.path is deprecated and will be removed. Please use Event.composedPath() instead.
1 source: @studio-freight_lenis.js:249
```

**Comment by clementroche** [comment]
Nice catch ! Thank you.
Fixed in [v0.2.18](https://github.com/studio-freight/lenis/releases/tag/0.2.18)
