### ISSUE TITLE
Issue with scrollTo + immediate

### ISSUE THREAD

**Issue by matiasperz** [darkroomengineering/lenis#46]
I'm having an issue doing the following for a page transition:

```
// Transition animation starts
lenis.stop()

// Transition covers up the page
lenis.scrollTo(0, { immediate: true })

// When the page transition ends after a short time, free the scroll again
lenis.start()
```
### The problem
The problem is that if the user changes the page before the **scroll** animation reaches its target, the scroll remembers the last point before the `scrollTo` executes. So when I start it back again it animates from there to the top trying to reach the new target.

You can reproduce it in the following link by pressing the space right before the scroll animation ends.
https://codepen.io/matias4205/pen/MWXWQMa

**Comment by clementroche** [comment]
Thank you for your contribution.
