### ISSUE TITLE
Lag in Chrome

### ISSUE THREAD

**Issue by thagxt** [darkroomengineering/lenis#5]
I've tried Lenis on multiple sites and on all of them I experience a really bad lag. When I scroll it takes 2-3 secs before the script actually scrolls the page.

In the video below you can see when the numbers in the console update that's when I scroll with the mouse wheel, and pay attention after how many secs the page actually scrolls... [here's a codepen](https://codepen.io/gxt/pen/PoRpzdN) with the code.

https://user-images.githubusercontent.com/7128602/179609793-d8e744b8-a519-403a-b097-ac86060f6435.mp4

- Chrome: Version 103.0.5060.114 (Official Build) (arm64)
- Brave: Version 1.41.96 Chromium: 103.0.5060.114 (Official Build)

**Comment by thagxt** [comment]
Figured it out `html { scroll-behavior: smooth }` is causing the lag. 
This must be documented somewhere or the script should fix it automatically.

having `html { scroll-behavior: initial }` fixes it.

**Comment by arzafran** [comment]
> Figured it out `html { scroll-behavior: smooth }` is causing the lag. This must be documented somewhere or the script should fix it automatically.
> 
> having `html { scroll-behavior: initial }` fixes it.

Woah, nice catch!
We'll push an update soon, thanks ❤️
