### ISSUE TITLE
Should we have some debouncing?

### ISSUE THREAD

**Issue by clearly-outsane** [darkroomengineering/lenis#51]
I'm using this with r3f and I noticed 200+ console logs a second when I do something like `lenis.on('scroll', (scroll)=>{console.log))`. Should we limit it to like 30 a second?

**Comment by clementroche** [comment]
While scrolling the event is triggered the same refresh rate than your display in order to get the exact scroll value every frame. Why should we limit this to 30 per second ?

**Comment by clementroche** [comment]
Without any answer i will close this issue during the week.
