### ISSUE TITLE
Spacebar is scrolling the page

### ISSUE THREAD

**Issue by nortenhodesign** [darkroomengineering/lenis#52]
I have Lenis throughout my website and when a user is typing info in the form, if they hit spacebar, the page scrolls down.

I tested it by removing the smooth scroll and it works. Is there a fix for this? Maybe how to block a section from having smooth scroll?

To see what is happening you can check here:
https://darren-voros.webflow.io/contact

Thank you!

**Comment by clementroche** [comment]
Thank you it seems like useKeyboard: false as been removed by accident. It's fixed with [v0.2.21](https://github.com/studio-freight/lenis/releases/tag/0.2.21)
