### ISSUE TITLE
setScroll or scrollTo not changing scroll position if scrolling / having inertia

### ISSUE THREAD

**Issue by benjaminrobinet** [darkroomengineering/lenis#59]
**Describe the bug**
Methods `setScroll()` or `scrollTo()` won't work due to inertia. If there is a call to one of these methods while scrolling (or having some inertia), it won't work. Or at least it will not reset the right scroll position.

**To Reproduce**
https://codepen.io/benjaminrobinet/pen/KKeymNV  
I added a button on the bottom right of the screen that calls a `lenis.setScroll(0)`. Just try to click it while having inertia: it won't change the scroll position.

**Comment by benjaminrobinet** [comment]
Looks similar to this issue: https://github.com/studio-freight/lenis/issues/46. Calling `stop()`, `scrollTo()` and then `start()` seems to fix it.

**Comment by clementroche** [comment]
fixed in [v.0.2.23](https://github.com/studio-freight/lenis/releases/tag/0.2.23)
