### ISSUE TITLE
Scroll distance per wheel event is noticeably less in Firefox

### ISSUE THREAD

**Issue by thasmo** [darkroomengineering/lenis#61]
**Describe the bug**
The scroll distance per wheel event is noticeably less in Firefox (on Ubuntu/Linux) than in Chrome. In Chrome the scroll distance per wheel event feels nice and looks reasenable, but in Firefox the scrolled distance per wheel event is quite a lot less and scrolling feels very slow and cumbersome.

**To Reproduce**
https://codepen.io/ClementRoche/pen/VwxgZEP

**Comment by clementroche** [comment]
What platform and scrolling device are you using ? MacOS with trackpad ?
I've just tested on Windows with a mouse wheel and both Firefox and Chrome are the same.

**Comment by thasmo** [comment]
`Firefox 107.0` on `Ubuntu 20.04.5`.

**Comment by clementroche** [comment]
But using a mouse wheel ?

**Comment by thasmo** [comment]
> But using a mouse wheel ?

Pardon, yes. Using a mouse wheel.

**Comment by thasmo** [comment]
A single wheel event scrolls 48px in Firefox but 96px in Chrome.

**Comment by thasmo** [comment]
Anything else I can provide to this? Thanks! :)

**Comment by clementroche** [comment]
@thasmo I've just tested lenis on Firefox Ubuntu and it looks the same as Ubuntu Chrome. Are you sure you havn't changed the wheel speed or any scroll related option on your side ?

**Comment by thasmo** [comment]
@clementroche I've updated to version `0.2.28` and the issue persists, although the scroll distance has changed.

One mousewheel event scrolls `100px` in Firefox and `201.5px` in Chrome and Edge.

**Comment by clementroche** [comment]
Can you try using this [codesandbox](https://ju3jjt.csb.app/) ?

**Comment by thasmo** [comment]
On https://ju3jjt.csb.app/ the scroll distance difference is smaller, in fact, scroll distance is rather equal:
Firefox: `114px`
Chrome: `106px`

That's odd. I'l dig deeper into my code/integration.

Thanks for the help!

**Comment by clementroche** [comment]
The last codesandbox I sent is the incoming Lenis v1.0.0. Bunch of things has been simplified/fixed. This version should be released within the next weeks.

**Comment by clementroche** [comment]
So basically you can consider this issue fixed with this version.

**Comment by thasmo** [comment]
I see. Wonderful! Thanks for the update. Going to test v1 next year then probably. :)

**Comment by clementroche** [comment]
[v1.0.0-dev](https://github.com/studio-freight/lenis/releases/tag/1.0.0-dev.1) is out ! It's currently a beta version waiting for potential bugs

**Comment by thasmo** [comment]
@clementroche Thanks! :) I noticed [`latest`](https://www.npmjs.com/package/@studio-freight/lenis/v/latest) on npmjs.com refers to `1.0.0-dev.1`. Not sure this is intentional; just wanted to let you know.

**Comment by clementroche** [comment]
i think that's fine since `npm i @studio-freight/lenis` should install 0.2.28 a.k.a last stable version

**Comment by thasmo** [comment]
@clementroche, that's what I meant. `latest` points to `1.0.0-dev.1` and not `0.2.28`.

![image](https://user-images.githubusercontent.com/184284/212878942-ebec2103-02aa-4337-bf47-cfa0203bf6f2.png)

`npm i @studio-freight/lenis` will install `1.0.0-dev.1`.

**Comment by thasmo** [comment]
Also, it seems that the original issue `Scroll distance per wheel event is noticeably less in Firefox` still occurs with `1.0.0-dev.1`. I noticed there's also `1.0.0-dev.2`, which is not available on npmjs.com; would I need to test `1.0.0-dev.2`?

**Comment by clementroche** [comment]
The latest tag is fixed thank you !

**Comment by thasmo** [comment]
@clementroche :+1:

So, I've noticed that the fix you made, which I tested earlier, does not seem to work in `1.0.0-dev.1`.

> The last codesandbox I sent is the incoming Lenis v1.0.0. Bunch of things has been simplified/fixed. This version should be released within the next weeks.

Any idea why that is? Is there a dedicated test environment where I can re-test the fix?

**Comment by clementroche** [comment]
That's weird, i'm gonna test again

**Comment by clementroche** [comment]
i get 114px per wheel on Firefox and 120px on Chrome both Ubuntu @thasmo is that right ?

**Comment by thasmo** [comment]
@clementroche, yes - 114px on Firefox, but 240px on Chrome.

**Comment by clementroche** [comment]
i get 120px on chrome, i'm testing here https://codepen.io/ClementRoche/pen/VwxgZEP

**Comment by thasmo** [comment]
@clementroche I still get 240px (double) on the codepen in Chrome. So odd. I'm on Chrome `109.0.5414.74`.

**Comment by thasmo** [comment]
Last month I had different results, on a different demo:
> On https://ju3jjt.csb.app/ the scroll distance difference is smaller, in fact, scroll distance is rather equal:
> Firefox: 114px
> Chrome: 106px

I double checked to not have any Chrome extensions enabled etc. :thinking: Weird, but the Codepen demo gives me 240px in Chrome.

**Comment by clementroche** [comment]
I wonder if clamp the wheel delta between -100 and 100 is a good idea, in theory it should fix that

**Comment by thasmo** [comment]
@clementroche I' not sure how wheel delta is used on lenis or virtual-scroll, but afaik [delta should be converted](https://stackoverflow.com/questions/14926366/mousewheel-event-in-modern-browsers) to `1` or `-1` for consistancy; probably depends on how the value is used, I guess.

**Comment by clementroche** [comment]
https://github.com/studio-freight/lenis/blob/main/src/virtual-scroll.js

**Comment by thasmo** [comment]
@clementroche does Lenis use the actual value of wheel-delta directly? Another way would be to clamp it between `1` (scroll down) and `-1` (scroll up) and multiply it by a constant value (e.g.120), I guess. But I don't know if that's the best option or makes sense at all in the context of Lenis.

**Comment by clementroche** [comment]
Windows Firefox: 102
Windows Chromium: 100
Ubuntu Firefox: 114
Ubuntu Chromium: 120

**Comment by clementroche** [comment]
The issue is with trackpad mostly on laptop, they return smaller values so you can't just multiply by a constant. There is no way to know if the user is scrolling using wheel or trackpad, both are treaten the same through wheel event

**Comment by clementroche** [comment]
i think clamping the value should fix it

**Comment by thasmo** [comment]
I would try and change it to:
```js
  #onWheel = (event) => {
    let { deltaX, deltaY } = event
    deltaX = Math.max(Math.min(deltaX, 1), -1) * 100 * this.#wheelMultiplier
    deltaY = Math.max(Math.min(deltaY, 1), -1) * 100 * this.#wheelMultiplier

    this.#emitter.emit('scroll', { type: 'wheel', deltaX, deltaY, event })
  }
```

**Comment by clementroche** [comment]
this breaks scrolling with trackpad

**Comment by thasmo** [comment]
Oh, didn't know the trackpad emits wheel events. My bad.

**Comment by thasmo** [comment]
Still, I don't really understand why Chrome would scroll 240px instead of 120px, in my case. :thinking: Without Lenis the scroll distance in Chrome is 120px.

**Comment by clementroche** [comment]
me neither and in addition i can't reproduce it

**Comment by thasmo** [comment]
I'll have to debug/tinker with it a bit, as soon as I have time. Not sure when this will be tho. :crossed_fingers:

**Comment by thasmo** [comment]
> Windows Firefox: 102
> Windows Chromium: 100
> Ubuntu Firefox: 114
> Ubuntu Chromium: 120

Windows Firefox: 102
Windows Chrome: 150

😆

**Comment by clementroche** [comment]
What mouse are you using ?

**Comment by thasmo** [comment]
@clementroche, actually a different one for each system (Windows, Linux). 😅

**Comment by clementroche** [comment]
can you try to switch and see if values are the same ?

**Comment by thasmo** [comment]
@clementroche, not right now, but I'm testing Firefox and Chrome on Windows at the moment:

**Windows Firefox**
native: 104px
lenis: 102px

**Windows Chrome**
native: 100px
lenis: 150px

Are those expected numbers? 🤔

**Comment by clementroche** [comment]
I have Windows Chrome Lenis: 100px

**Comment by thasmo** [comment]
Just realized that browser scroll distance also depends on the Windows mouse setting "lines to scroll at a time".

![image](https://user-images.githubusercontent.com/184284/212993730-9b601062-1f45-466f-ac91-288d797fe588.png)

Depending on that setting, scroll distance changes in browsers, but it's ofc not consistent accross browsers.

**Comment by clementroche** [comment]
So i'm shared between let the user choose to keep user wheel values or normalize everything to -100/100 or even create a `normalizeWheel` option

**Comment by thasmo** [comment]
> So i'm shared between let the user choose its lines to scroll or normalize everything to -100/100 or even create a normalizeWheel option

It would be nice if scroll distance via Lenis is the same as native; browser differences would then be fine I guess.

I just noticed something of which I'm not sure it should be that way or what it even means: When scrolling with the mousewheel for a single tick, this are the reported values:

**Firefox**
wheel.deltaY: 102
window.scrollY: 104

**Chrome**
wheel.deltaY: 150
window.scrollY: 100

Does that make sense? 🤔I probably did not realize that the wheel delta is **not** the scroll distance but rather a value for how much the wheel was turned?! I guess I haven't dealt too much with the wheel event by now. xD

**Comment by clementroche** [comment]
Yes wheelEvent is different than scrollEvent. That's the trick, Lenis scroll distance cannot be the same as native since wheelEvent.deltaY is not reliable, we have to normalize it someways, clamp(-100, wheel.deltaY, 100) will make it 100 for every browsers/OS

**Comment by clementroche** [comment]
`normalizeWheel` options was introduced in [v1.0.0-dev.4](https://github.com/studio-freight/lenis/releases/tag/v1.0.0-dev.4), can you check @thasmo ?

**Comment by thasmo** [comment]
@clementroche So far, `normalizeWheel` seems to do the job. Thanks!

Btw. I noticed that you maybe forgot a [console.log](https://github.com/studio-freight/lenis/blob/2aa7bc3af476df8484db53f3570b83089aa3aa8b/src/index.js#L214) in the `1.0.0-dev.5` release.

**Comment by clementroche** [comment]
thank you i can finally close this issue.
