### ISSUE TITLE
scrollTo immediate how to?

### ISSUE THREAD

**Issue by romain-granai** [darkroomengineering/lenis#62]
I'm strictly unable to scroll to an element without easing and duration, could you please provide an example?

Here is what I tried, without success : 

`lenis.scrollTo('.section--about--first', {immediate: true})`
`lenis.scrollTo('.section--about--first', {offset: 0, duration: 0, easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)), immediate: true})`

How does it need to be witten?

Thank you

**Comment by clementroche** [comment]
Can you please provide a codepen reproduction using [this template](https://codepen.io/pen?template=VwxgZEP) ?

**Comment by romain-granai** [comment]
Sure,

Here it is : 

https://codepen.io/romaingranai/pen/dyKdeyb?editors=0010

on line 154 

`lenis.scrollTo('.section--about--first', {offset: 0, immediate: true, duration: 0, easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t))})`

Thanks

**Comment by arzafran** [comment]
I'm reviewing your codepen but i'm not completely sure what you're trying to do, are you trying to implement an infinite scroll?

if so you can enable `infinite` when instancing Lenis to avoid fake sections.

btw, this code is ok:
`lenis.scrollTo('.section--about--first', {immediate: true})`
