### ISSUE TITLE
Scrollbar drag teleport issue

### ISSUE THREAD

**Issue by QuentiumYT** [darkroomengineering/lenis#65]
**Describe the bug**
When enabling lenis on 2 of my websites, I get an issue when trying to click the scroll bar and drag it up and down.

[Screencast from 24-11-2022 13:54:50.webm](https://user-images.githubusercontent.com/35229942/203789932-c34285f5-8145-4cf3-b6e2-30329ae1da26.webm)

**To Reproduce**
This code is used in my website, also CSS properties for the full height are set.

```js
const lenis = new Lenis({
  duration: 1.2,
  easing: (t) => Math.min(1, 1 - Math.pow(2, -10 * t)),
  direction: 'vertical',
  gestureDirection: 'vertical',
  smooth: true,
  mouseMultiplier: 2,
  smoothTouch: false,
})

function raf(time) {
  lenis.raf(time)
  requestAnimationFrame(raf)
}

requestAnimationFrame(raf)
```

This does not happen with Locomotive scroll for example.
EDIT: Tested with opera 93 (page teleport) and chrome 107 (scroll completely locked)
Also same behaviour on Safari Mac

**Comment by arzafran** [comment]
do you have the same issue when trying to drag the scrollbar on https://lenis.studiofreight.com?

I've tested your instance configuration in a codepen but seems to work fine. 

Tested on chrome in macOS and Edge on a fresh install of Windows 11.

if possible, can you replicate the issue in a codepen using [this template](https://codepen.io/pen?template=VwxgZEP)?

**Comment by BleXor** [comment]
@arzafran 
Hi, seems like this glitch happens to me when you scroll via scrollwheel and before it finishes you start dragging the scrollbar. That is when this "jumpy/glitchy" behavior happens...

Edit 2022/11/29:
I'd like to add that this scroll glitch happens the same way if you scroll and before the scroll animation finishes, you press scrollwheel and move/drag verticaly.

**Comment by QuentiumYT** [comment]
Yes, it does happen on lenis website as well, but seems like a fix is preventing from glitching more than 2sec. Sadly not on my website.
Since opera latest version (from this morning) it sometimes breaks as chrome did, but no way to have a classic scroll.

As @BleXor added, it is true on a mac book pro, but it still persist even after the smooth scroll is still on my Linux.

So to sum up, Windows looks correct, Mac glitch during smooth scroll, Linux all the time.

You can try this behaviour on http://bluepaper.demo.izhak.fr/

**Comment by clementroche** [comment]
Please replicate this issue using [this template](https://codepen.io/ClementRoche/pen/VwxgZEP) otherwise there is nothing we can do. If you can't reproduce it means your implementation is wrong.

**Comment by QuentiumYT** [comment]
Same behaviour on the codepen, using the config of my website https://codepen.io/quentin-pro/pen/xxzyBqo
Tested on chrome & opera on Ubuntu 22.04 
[Screencast from 02-12-2022 14:32:25.webm](https://user-images.githubusercontent.com/35229942/205304530-91f7c1f1-cf73-4764-b155-35e70548250a.webm)

**Comment by clementroche** [comment]
It seems like the easing is causing issues. Can you try with this one instead (default): `easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t))`. It must exist issues with easing somewhere in the code, this issue will remain opened while investigation.

**Comment by BleXor** [comment]
@clementroche Hi - I used your easing in codepen from @QuentiumYT and it kinda fixed problem with pressing the scrollwheel to scroll - firstly animation finishes and after that the scrolling starts again, without that jumpy glitch from before. Although the issue with dragging the scrollbar before animation finishes still sometines causes that jumpy glitch.

**Comment by QuentiumYT** [comment]
Yup, I just tested, I agree with BleXor. It does improve the effect but when the scroll inertia is still playing, it does the jumpy glitch. If you set duration to 5, you will likely see it better.

**Comment by clementroche** [comment]
So the issue is when grabbing the scrollbar while scrolling with wheel ?

**Comment by QuentiumYT** [comment]
Yup exactly, the math easing may have done something that can smooth a bit but it's not solving the problem. It happens when you have that duration still scrolling the page and trying to drag the scrollbar. It does happen on any OS / any browser tho

**Comment by clementroche** [comment]
Well, I don't think we can do something for this since there is no way to prevent scrollbar grabbing. It's very unlucky if the user has to do both at the same time

**Comment by QuentiumYT** [comment]
Uh :/ I think the only option it to not have a long duration... which is very unfortunate :/
Looking at gsap scrollsmoother, it looks like they are reseting the scroll very quickly but still keep an inertia on the page (https://greensock.com/scrollsmoother/) what about someting similar?
