### ISSUE TITLE
Question: any advice on how to use as plugin with Nuxt3

### ISSUE THREAD

**Issue by codecansdev** [darkroomengineering/lenis#66]
Hi,

Thank you for such a great library. 

I was wondering if you could provide any advice on how to get it working as a plugin within a **Nuxt3** project. The following is what I have so far for my plugin file **lenis.client.js** withing the **plugins** folder of the project 

```
import Lenis from "@studio-freight/lenis";

const lenis = new Lenis({
  lerp: 0.1,
  smooth: true,
  direction: "vertical",
});

lenis.on("scroll", ({ scroll, limit }) => {
  console.log({ scroll, limit });
});

function raf() {
  lenis.raf();
  requestAnimationFrame(raf);
}

requestAnimationFrame(raf);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.provide("lenis", lenis);
});
```

Unfortunately the page stops scrolling and this is what I get on the console on scroll:

<img width="318" alt="imagen" src="https://user-images.githubusercontent.com/109253600/204878646-f4c2a9ae-7b8b-4570-b6b7-5d40290e6dee.png">

Thank you in advance for your help

**Comment by clementroche** [comment]
Can you provide a Codesandbox example ?

**Comment by codecansdev** [comment]
here you go [https://stackblitz.com/edit/nuxt-starter-y9tvbz?file=plugins/lenis.client.js](https://stackblitz.com/edit/nuxt-starter-y9tvbz?file=plugins/lenis.client.js)

thank you, Clément

**Comment by codecansdev** [comment]
nevermind, Clément.. 
the answer by @arzafran in this issue got it working https://github.com/studio-freight/lenis/issues/67
thank you!
