### ISSUE TITLE
Can't debug Lenis when returning NaN

### ISSUE THREAD

**Issue by dirtymartiniexe** [darkroomengineering/lenis#67]
Scroll is returning: {scroll: NaN, limit: 0, velocity: NaN, direction: -1, progress: NaN}

I have no idea, why this isn't working and with no way to debug install works perfectly with scrollSmoother and Locomotive scroll.

Javascript looks like this, set up is really simple. While it is a WP install I have a wrapper and content div that goes around the main html tag, super simple stuff.

Really confused why limit is not assigned, looking at other issues I can see the wheel event called before this can affect the scroll, however I have deleted all other references.

FYI the page does not move at all, any help on debugging this would be great.

`  createScroll() {
    this.scrollWrapper = document.querySelector('#smooth-wrapper')
    this.scrollContent = document.querySelector('#smooth-content')

    this.Scroll = new Lenis({
      duration: 1.2,
      wrapper: this.scrollWrapper,
      content: this.scrollContent,
      direction: 'vertical',
      smooth: true,
    })

    this.Scroll.on('scroll', ({ scroll, limit, velocity, direction, progress }) => {
      console.log({ scroll, limit, velocity, direction, progress })
    })

    const raf = () => {
      this.Scroll.raf()
      requestAnimationFrame(raf)
    }
    
    requestAnimationFrame(raf)
  }`

<img width="2823" alt="Screenshot 2022-12-01 at 12 10 33" src="https://user-images.githubusercontent.com/88897007/205049705-73c9635e-abc7-454d-8afc-fe800b0e4440.png">

**Comment by arzafran** [comment]
`time` is missing  when setting up the rAF function, it should look like this:

```js
const raf = (time) => {
  this.Scroll.raf(time)
  requestAnimationFrame(raf)
}
```

if that doesn't fix it, can you please provide a codepen based on [this template](https://codepen.io/pen?template=VwxgZEP) with your issue?

**Comment by dirtymartiniexe** [comment]
Thats great thanks @arzafran, that's cleared up the errors in the console

However I'm now getting no console.log and the mouse wheel event isn't triggering anything at all.

if i move the mouse to the top and bottom of the screen I'm getting a tiny bit of movement but not a lot, do you know how I can check the wheel events?

**Comment by dirtymartiniexe** [comment]
I had an element covering the main container that had 'pointer-events: none' that seem to be affecting it. I have removed this element but it's still not triggering  lenis scroll it just seems to be the default smooth scroll Chrome behaviour.

**Comment by clementroche** [comment]
Please reproduce it on [codepen](https://codepen.io/pen?template=VwxgZEP).
