### ISSUE TITLE
scrollTo with disabled events

### ISSUE THREAD

**Issue by vitass** [darkroomengineering/lenis#68]
Utilizing **scrollTo** method causes a conflicting behavior with any subsequently fired wheel events. 
Is there a way to disable scrollbar wheel events until the **scrollTo** target is reached?

**Comment by clementroche** [comment]
You mean other wheel events will not be fired if lenis is initialised ? If so can you reproduce it on [codepen](
https://codepen.io/pen?template=VwxgZEP) ?

**Comment by vitass** [comment]
Hey! 

No, it's about using the **scrollTo** method on lenis with its events still enabled. While the method is executing (scrolling to a destination), events on lenis are still active. So if you do a wheel interaction during that time it messes up the end calculation as lenis gets retriggered by the wheel event. 

So I'm wondering is there a way to disable event listeners on lenis while **scrollTo** executes?

**Comment by clementroche** [comment]
Look at this [example](https://codepen.io/ClementRoche/pen/PoaVYwB), ideally lenis should do the same, to interrupt the `scrollTo` if wheel event is triggered. You could possibilty stop wheel event propagation until `scrollTo` finishes.

```js
function stopPropagation(e) {
  e.stopPropagation()
}

// call on lenis.scrollTo()
lenis.contentNode.addEventListener('wheel', stopPropagation)

// call on lenis.scrollTo() finishes
lenis.contentNode.removeEventListener('wheel', stopPropagation)
```
