### ISSUE TITLE
Scrollbar still visible when deactivating the scroll

### ISSUE THREAD

**Issue by kkopp001** [darkroomengineering/lenis#69]
**Describe the bug**
It's still possible to scroll with the cursor using the scrollbar on the right side of the browser.
A solution would be to deactivate the scrollbar with css, but shouldn't this be automatically done by Lenis?

**To Reproduce**
just `lenis.stop()`

**Comment by clementroche** [comment]
I'm not convinced Lenis should be in charge of hidding overflow by itself. So you need to hide the scrollbar/hide overflow using CSS if you want to prevent this.

**Comment by kkopp001** [comment]
But whats the purpose of `lenis.stop()` if the user is still able to scroll with the scrollbar?

**Comment by clementroche** [comment]
To stop the wheel/touch scroll

**Comment by clementroche** [comment]
Eventually we could add a CSS class like `lenis-stopped` or we could stop totally the scroll with javascript, I'm gonna study pros and cons

**Comment by kkopp001** [comment]
Yeah could be a nice addon, but if it's intended I can close the issue and will add the css myself. Thanks ! 👍

**Comment by clementroche** [comment]
Now [v0.2.25](https://github.com/studio-freight/lenis/releases/tag/0.2.25) adds a `lenis-stopped` class to wrapper element on stop
