### ISSUE TITLE
Intersection Observer

### ISSUE THREAD

**Issue by vickykeen** [darkroomengineering/lenis#70]
Sorry just a rookie question how to state intersection observer is there any specific class for that?

**Comment by clementroche** [comment]
You must use [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) by yourself

**Comment by vickykeen** [comment]
Hi Mr *Clément Roche *
cause below image shows it comes with the IO nvm thank you for replying.
[image: image.png]
