### ISSUE TITLE
Disable Keyboard Option

### ISSUE THREAD

**Issue by dash-james** [darkroomengineering/lenis#73]
I'm currently trying to disable the keyboard support while I have a modal open (there is an Embla slider on the modal that I have assigned keyboard support to while open). I can't seem to find a way.

Each time I press up or down keys, Lenis moves the page (which is not ideal as the page moves underneath while the modal is open) as well as my slider instance.

Is it possible add an option to just disable the keyboard for Lenis?

**Comment by clementroche** [comment]
Please reproduce it using this [template](https://codepen.io/pen?template=VwxgZEP)

At first sight I would say it's not related to Lenis, but that's the default behavior of scrolling a web page. You could use `e.stopPropagation()` inside your keyboard event listener

**Comment by dash-james** [comment]
It is still happening with

**Comment by dash-james** [comment]
It is still happening even with `e.stopPropagation()`

See here for Codepen: https://codepen.io/jamesdash/pen/eYKomEK

**Comment by clementroche** [comment]
I just removed Lenis from your pen and the same is happening ([see codepen](https://codepen.io/ClementRoche/pen/ZERZxoB?editors=1010)). I think you should remove ArrowUp/ArrowDown from your slider controls. Anyway that's not related to Lenis so I'm closing this issue.
