### ISSUE TITLE
ideas for smooth position sticky?

### ISSUE THREAD

**Issue by maxschulmeister** [darkroomengineering/lenis#77]
Hi Guys and thank you for this awesome library!
This is not a bug, but rather a question for the masterminds:

Do you have an idea on how to possibly smoothen the effect when an element sticks to it's defined position with `position: sticky`?
I'm just wondering if this leads back to needing a full js sticky solution that eases the element into it's final position or if there is another way.

Thanks!

**Comment by clementroche** [comment]
I think you have to use JavaScript
