### ISSUE TITLE
Smooth scrolling is broken on my website

### ISSUE THREAD

**Issue by theAlixer** [darkroomengineering/lenis#78]
Hey, yesterday smooth scrolling worked fine on a client of mine's website, but today scrolling just doesn't work. The only way i'm able to scroll is by using the keyboard arrow up and down keys, and by clicking and dragging the sidebar. Was this caused by a new recent release? 

It could be a problem on my end, but i'm thinking it might be due to the new release posted 14 hours ago at the time of writing this, which seems to line up with when scrolling stopped working. I've rolled back the webflow site to a backup from 14 days ago where I know for a fact it was working, and after publishing the site, the same thing occurs and i'm not able to scroll. 

Hope you can shed some light on whether its something on my end or yours.

**Comment by theAlixer** [comment]
Update:

I think it must be something with the new version 0.2.27.

I changed the declaration to say instead of pull in lenis@latest, pull in lenis@v0.2.26 and scrolling works perfectly now. (excuse me butchering the use of development terms, I'm not a developer 😂 )

Before:
<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@latest/bundled/lenis.js"></script>

After:
<script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@v0.2.26/bundled/lenis.js"></script>

**Comment by clementroche** [comment]
Can you reproduce on [codepen](https://codepen.io/pen?template=VwxgZEP) please ? My guess is your html element is not default sized

**Comment by kgr-soundvenue** [comment]
I have the same problem. Here is dev link with lates lenis.js:
https://zeit-guide.webflow.io/

And here is the same site rolled back to 0.2.26:
https://zeit.guide/

**Comment by clementroche** [comment]
Yep @kgr-soundvenue your html has height:100% applied. Just a question is it something webflow adds by default ?

**Comment by kgr-soundvenue** [comment]
> Yep @kgr-soundvenue your html has height:100% applied. Just a question is it something webflow adds by default ?

Which element are you referring to? Everything was working fine with the old build, have used it for multiple projects. So just wondering how it suddenly broke :)

**Comment by clementroche** [comment]
I changed the default content element from document.body (`<body>`) to document.documentElement (`<html>`) so if your `<html>` has height: 100% the size of the content  is wrong breaking the scroll

**Comment by kgr-soundvenue** [comment]
> I changed the default content element from document.body (`<body>`) to document.documentElement (`<html>`)

Ah makes sense. Yes I see the html element is 100% hmm. Let me check it quick.

**Comment by clementroche** [comment]
But in any case I do not advice you to use @latest to avoid this kind of issues.

**Comment by clementroche** [comment]
It seems like webflow ship html{height:100%} as default, that's not ideal... I'm wondering if I should rollback to document.body

**Comment by clementroche** [comment]
i made a rollback in v0.2.28

**Comment by kgr-soundvenue** [comment]
> i made a rollback in v0.2.28

Thank you for a quick fix and a great product <3

**Comment by clementroche** [comment]
But keep in mind this will change in the future (next major release). There is no reason to keep `document.body` as default other than Webflow adding useless CSS by default . Also as i said before do not use `lenis@latest` in production otherwise it will break your website again.

**Comment by kgr-soundvenue** [comment]
> But keep in mind this will change in the future (next major release). There is no reason to keep `document.body` as default other than Webflow is adding default CSS. Also as i said before do not use `lenis@latest` in production otherwise it will break your website again.

Makes sense. I will stick to 0.2.28, ty
