### ISSUE TITLE
Unminified version

### ISSUE THREAD

**Issue by PubliAlex** [darkroomengineering/lenis#86]
Hello,

This is not a bug but I don't know where to ask for this.

Would it be possible to provide an unminified version of the library. Generally, a js library jave a library.js file (unminified) and library.min.js file (minified).

Here, in the dist folder, the lenis.js is already minified.

Thank you

Alex

**Comment by clementroche** [comment]
Why do you want unminified version ? What is the use case ?

**Comment by PubliAlex** [comment]
Hello,

Thank you for your answer.

The use case of this is that I use a CMS that have it's own minification system. When my .env file in in development, I work with unminified version of JS files, which make life easier when you need to debug something because the code is readable.

When I put the .env file to production, the CMS combine and minify all files to improve performances. When I provide an already minified file, sometimes, it create bugs to the combined minified file provided by the CMS cause it try to minify an already minified file.

So there are 2 benefits to have non minified file : 
- Simplify debug during development
- Avoid problems when the CMS minify all assets with it's internal system.

That's why I ask for this.

Thank you

Alex

**Comment by clementroche** [comment]
in this case you have everything you need in src folder https://github.com/studio-freight/lenis/tree/main/src

**Comment by PubliAlex** [comment]
Not sure, I don't use all stuff like webpack, npm etc... (yes I'm old school I know). I don't understand why all theses files. Generally, I use a single .js file that is an unminified version of the .min.js file, but containing all needed stuff to not be obliged to include several files, for a single plugin.

Generally, when I try to include these "modular" files, it displays errors in the console.

**Comment by clementroche** [comment]
I've just published lenis v1.0.0-dev, can you check if [budled/lenis.js](https://github.com/studio-freight/lenis/blob/main/bundled/lenis.js) is what you need ?

**Comment by PubliAlex** [comment]
That seems just perfect 👍 thank you

**Comment by PubliAlex** [comment]
I reopen issue because I wanted to update the library, and noticed that the unminified version has disappeared from release.

**Comment by clementroche** [comment]
it's back: https://unpkg.com/@studio-freight/lenis@1.0.35/dist/lenis.js

**Comment by PubliAlex** [comment]
Thank you !
