### ISSUE TITLE
please add lenis.init() to reinitializes the scroll.

### ISSUE THREAD

**Issue by heyadeivan** [darkroomengineering/lenis#87]
I am using barba.js but I need to reinitialize the code `lenis.init()` after `lenis.destroy()`

**Comment by oguilleux** [comment]
I'm using Lenis + barba.js and I encountered some problems with scrolltrigger animations. Wasn't smart but I used gsap.defaults() et Scrolltrigger.defaults() that messed up my animations.

Also try initialising Lenis once before barba even inits.

**Comment by heyadeivan** [comment]
for now I init Lenis before barba init, and it works when switching pages without having to destroy, scrolltrigger is also no problem.

Previously I used Loco on my site, and I had a problem when switching pages the scrollbar doubled, I fixed it by destroying then reinstalling. So I was thinking is it ok to use Lenis + Barba without destroying and re-init again?

**Comment by oguilleux** [comment]
Indeed I do the same for locomotive scroll : I destroy it on afterLeave and init again on afterEnter. Fortunately you don't need to do that with Lenis.

I don't understand why you want to re-init again. You would be creating another Lenis requestAnimationFrame function : not good for performances.

**Comment by dngraphisme** [comment]
Hello guys,

I have such a strange problem with barbaJS.

I initiate lenis before barbaJS. But then even with .stop(), if I change pages, it adds class to the html but I can still scroll

Have you ever had this ?

Thanks Nicolas

**Comment by oguilleux** [comment]
Did you add the Lenis css to yours ?

**Comment by dngraphisme** [comment]
Hello Oguilleux, 

Yes of course :)

<img width="598" alt="Capture d’écran 2024-03-07 à 17 46 37" src="https://github.com/darkroomengineering/lenis/assets/5530905/7d4c4896-0d58-466d-a0c3-47bea7a19f89">


I explain more here : https://github.com/darkroomengineering/lenis/issues/310

Thanks !
