### ISSUE TITLE
Weird scrolling behavior when the cursor is over a vimeo/youtube video (iframe?)

### ISSUE THREAD

**Issue by azkalex** [darkroomengineering/lenis#95]
**Describe the bug**
I guess this happens if it's over an iframe? The scrolling is not consistent when the cursor is over a vimeo/youtube video and you scroll. It's like the `duration` changes to something really short, it doesn't scroll as it does for the rest of the page.

**To Reproduce**
https://codepen.io/azkalex/pen/yLqXmpj

Scroll like you normally would, and when you get inside the youtube video iframe, insist on scrolling when you're inside of it. You'll see it behaves differently than scrolling the rest of the page.

**Comment by clementroche** [comment]
Unfortunately there is no ideal solution. See #38

**Comment by ww-wolt** [comment]
probably the easiest workaround is to disable pointer-events for iframes while lenis scroll is active:

```
.lenis-scrolling iframe {
   pointer-events: none;
} 
```
It has the drawback that the iframe is unclickable when the page is still slightly moving, but a soon as the scroll stops and the page stands still, the interactivity works.
